import type { BankQuestion } from './questionBanks';

/**
 * The Success Hub placement item bank (working adults and professionals, CEFR A1 floor checks, A2-C1; 80 items).
 *
 * Reviewed by two independent expert reviewers (docs/placement-item-review.md, Success section) and revised. Designed from the placement-test research (docs/placement-test-research.md): a general-English core with a short
 * workplace layer. Workplace FUNCTIONS (requesting, explaining, postponing, disagreeing politely) are tested in
 * simple situations anyone can imagine, and business vocabulary is kept for the B2+ items, so a strong English
 * speaker with no office experience is not under-placed. American English throughout; four plausible parallel
 * options; one defensible answer; neutral feedback; no cultural knowledge needed.
 *
 * Options are shuffled on screen (except where `fixedOrder` is set, e.g. times), so the position of the key cannot be learned. Edit items here, keep ids stable.
 * `difficulty` bands: A1 0.05-0.27, A2 0.27-0.50, B1 0.48-0.68, B2 0.66-0.86, C1 0.85+ (expert estimates, refined
 * later from real answers).
 */
const NEUTRAL = { correct: 'Thanks!', incorrect: 'Thanks!' };

export const SUCCESS_BANK: BankQuestion[] = [
  { id: "su-01", question: "I ___ a teacher. I work at a school.", options: ["am", "is", "are", "be"], correctIndex: 0, difficulty: 0.1, targetLevel: "A1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-02", question: "I send emails on my ___.", options: ["computer", "kitchen", "window", "garden"], correctIndex: 0, difficulty: 0.1, targetLevel: "A1", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-03", question: "When is the office closed?", options: ["On weekends", "On Monday morning", "On Wednesday afternoon", "On Friday at 3 p.m."], correctIndex: 0, difficulty: 0.15, targetLevel: "A1", readingPassage: "Office hours: Monday to Friday, 9 a.m. to 5 p.m. Closed on weekends.", skill: "reading", feedback: NEUTRAL },
  { id: "su-04", question: "She ___ to work by train every day.", options: ["goes", "go", "going", "is go"], correctIndex: 0, difficulty: 0.27, targetLevel: "A2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-05", question: "Yesterday I ___ three emails to the client.", options: ["sent", "send", "sending", "sended"], correctIndex: 0, difficulty: 0.3, targetLevel: "A2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-06", question: "We ___ a meeting at 10 a.m. tomorrow.", options: ["are having", "having", "had", "have had"], correctIndex: 0, difficulty: 0.4, targetLevel: "A2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-07", question: "Could you ___ me the report, please?", options: ["send", "sending", "to send", "sent"], correctIndex: 0, difficulty: 0.27, targetLevel: "A2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-08", question: "Please ___ this form and give it to the manager.", options: ["fill out", "check out", "turn out", "run out"], correctIndex: 0, difficulty: 0.38, targetLevel: "A2", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-09", question: "I'm sorry I'm late. My train was ___.", options: ["delayed", "closed", "lost", "finished"], correctIndex: 0, difficulty: 0.4, targetLevel: "A2", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-10", question: "There aren't ___ chairs in the meeting room.", options: ["enough", "much", "a", "too"], correctIndex: 0, difficulty: 0.4, targetLevel: "A2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-11", question: "When is the meeting now?", options: ["On Thursday at 2 p.m.", "On Tuesday at 2 p.m.", "On Thursday at 4 p.m.", "On Tuesday in Room 4B"], correctIndex: 0, difficulty: 0.36, targetLevel: "A2", readingPassage: "Hi Tom, the meeting is moved from Tuesday to Thursday at 2 p.m. Please bring your laptop. Room 4B. Thanks, Lena", skill: "reading", feedback: NEUTRAL },
  { id: "su-12", question: "🎧 When is the appointment?", options: ["3:00", "3:20", "3:30", "4:30"], correctIndex: 2, difficulty: 0.4, targetLevel: "A2", type: 'listening_match', audio_script: "Hello, this is Maria from the dentist's office. Your appointment is on Wednesday at three thirty. Please arrive ten minutes early.", skill: "listening", fixedOrder: true, feedback: NEUTRAL },
  { id: "su-13", question: "🎧 What should employees do today?", options: ["Work from home", "Come to the office at ten", "Take the day off", "Call their manager"], correctIndex: 0, difficulty: 0.35, targetLevel: "A2", type: 'listening_match', audio_script: "Good morning. The office is closed today because there is no electricity. Please work from home and check your email for news.", skill: "listening", feedback: NEUTRAL },
  { id: "su-14", question: "The ___ shows the days and times of all our meetings.", options: ["calendar", "receipt", "ticket", "uniform"], correctIndex: 0, difficulty: 0.25, targetLevel: "A1", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-15", question: "Thank you ___ your email. I will reply tomorrow.", options: ["for", "to", "about", "with"], correctIndex: 0, difficulty: 0.3, targetLevel: "A2", skill: "business_writing", feedback: NEUTRAL },
  { id: "su-37", question: "A colleague says: 'Thanks for your help with the report!' What is the best reply?", options: ["No problem. Happy to help.", "No, thank you. It is fine.", "Yes, I am helpful.", "You are welcome for the report help."], correctIndex: 0, difficulty: 0.35, targetLevel: "A2", skill: "fluency", feedback: NEUTRAL },
  { id: "su-16", question: "I've worked at this company ___ 2019.", options: ["since", "for", "from", "during"], correctIndex: 0, difficulty: 0.5, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-17", question: "If the client ___ the offer, we'll start next week.", options: ["accepts", "will accept", "accepted", "accepting"], correctIndex: 0, difficulty: 0.46, targetLevel: "A2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-18", question: "The report ___ by the finance team last Friday.", options: ["was finished", "finished", "is finished", "was finishing"], correctIndex: 0, difficulty: 0.5, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-19", question: "He asked me ___ the file the day before.", options: ["if I had sent", "if did I send", "that I send", "did I sent"], correctIndex: 0, difficulty: 0.65, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-20", question: "We're looking forward ___ you next week.", options: ["to seeing", "to see", "for seeing", "at see"], correctIndex: 0, difficulty: 0.52, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-21", question: "I wish I ___ more time to finish the project.", options: ["had", "have", "would have", "will have"], correctIndex: 0, difficulty: 0.6, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-22", question: "This is the ___ project I have ever worked on.", options: ["most difficult", "more difficult", "much difficult", "very difficult"], correctIndex: 0, difficulty: 0.42, targetLevel: "A2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-23", question: "You ___ wear a suit. Casual clothes are fine.", options: ["don't have to", "mustn't", "can't", "shouldn't"], correctIndex: 0, difficulty: 0.55, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-24", question: "The manager, ___ office is on the third floor, wants to meet you.", options: ["whose", "who", "which", "whom"], correctIndex: 0, difficulty: 0.62, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-25", question: "Could you give me some ___ on how to improve my presentation?", options: ["advice", "advices", "an advice", "advise"], correctIndex: 0, difficulty: 0.5, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-26", question: "The company will ___ a new product next month.", options: ["launch", "found", "expand", "settle"], correctIndex: 0, difficulty: 0.55, targetLevel: "B1", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-27", question: "We can't ___ any more mistakes. The deadline is tomorrow.", options: ["afford", "spend", "cost", "owe"], correctIndex: 0, difficulty: 0.66, targetLevel: "B2", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-28", question: "The meeting was ___ because the manager was ill.", options: ["postponed", "prevented", "prepared", "promoted"], correctIndex: 0, difficulty: 0.52, targetLevel: "B1", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-29", question: "I'd like to ___ an appointment with Dr. Lee for Monday.", options: ["make", "do", "take", "give"], correctIndex: 0, difficulty: 0.42, targetLevel: "A2", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-30", question: "What should someone do if they cannot attend?", options: ["Tell Priya by Tuesday", "Bring their own lunch", "Come at 3:00 instead", "Book a session online"], correctIndex: 0, difficulty: 0.45, targetLevel: "A2", readingPassage: "Subject: Training day. Hi everyone, next Friday we will have a training day on the new software. It will start at 9:00 and finish at 3:00. Lunch will be provided. If you cannot attend, please tell me by Tuesday so that I can book a different session for you. Thanks, Priya", skill: "reading", feedback: NEUTRAL },
  { id: "su-31", question: "Why is the company thinking about a hybrid plan?", options: ["Most staff want to work at home some days, but not every day", "Most staff want to work at home every day of the week", "Staff say that travel takes more time than before", "Staff say that the office has become too small"], correctIndex: 0, difficulty: 0.55, targetLevel: "B1", readingPassage: "Our survey of 500 employees shows that most people prefer to work from home two or three days a week. They say they save time on travel and can concentrate better. However, some people miss talking to colleagues in person. As a result, the company is thinking about a hybrid plan.", skill: "reading", feedback: NEUTRAL },
  { id: "su-32", question: "What should staff do to get their parking money back?", options: ["Keep their receipts", "Park behind the building", "Ask for a parking permit", "Park all day on Elm Street"], correctIndex: 0, difficulty: 0.5, targetLevel: "B1", readingPassage: "Parking notice. From March 1, the parking lot behind the building will close for repairs for six weeks. Staff may use the public parking lot on Elm Street. The company will pay for up to two hours of parking each day. Please keep your receipts.", skill: "reading", feedback: NEUTRAL },
  { id: "su-33", question: "🎧 What is the problem?", options: ["The meeting is not in the calendar", "The client is late", "The room is not free", "Dan cannot find the client"], correctIndex: 0, difficulty: 0.5, targetLevel: "B1", type: 'listening_match', audio_script: "Hi, it's Dan from reception. A client is waiting for you downstairs. She says she has a meeting with you at eleven, but I don't see it in your calendar. Could you come down, or should I send her up?", skill: "listening", feedback: NEUTRAL },
  { id: "su-34", question: "🎧 Why was the room changed?", options: ["Many more employees registered than planned", "The session was canceled this morning", "The speaker is going to be late today", "Room 2 is being repaired this week"], correctIndex: 0, difficulty: 0.52, targetLevel: "B1", type: 'listening_match', audio_script: "Attention, please. The training session on customer service has moved from Room 2 to the main auditorium because more people signed up than expected. It will still start at two o'clock.", skill: "listening", feedback: NEUTRAL },
  { id: "su-35", question: "🎧 What does the speaker recommend?", options: ["Stay with the current supplier", "Choose the cheaper supplier", "Ask both suppliers for faster delivery", "Wait until next month"], correctIndex: 0, difficulty: 0.6, targetLevel: "B1", type: 'listening_match', audio_script: "I looked at the quote from the second supplier. It's about ten percent cheaper, but delivery takes three weeks instead of one. We need the equipment by the end of the month, so I think we should stay with our current supplier.", skill: "listening", feedback: NEUTRAL },
  { id: "su-36", question: "Which sentence is the most polite way to ask for a deadline extension?", options: ["Would it be possible to have until Friday to finish this?", "I need until Friday to finish this, so please wait.", "You have to give us until Friday to finish this.", "We are going to finish this on Friday, okay?"], correctIndex: 0, difficulty: 0.52, targetLevel: "B1", skill: "business_writing", feedback: NEUTRAL },
  { id: "su-38", question: "You did not understand something in a meeting. What can you say?", options: ["Sorry, could you explain that again?", "Sorry, I am not understanding you.", "Could you repeat me the sentence?", "Sorry, I did not listen the last part."], correctIndex: 0, difficulty: 0.4, targetLevel: "A2", skill: "fluency", feedback: NEUTRAL },
  { id: "su-60", question: "Which sentence is best for a formal email to a client?", options: ["I am writing to confirm that the meeting will take place on Monday.", "I am writing for to confirm that the meeting is on Monday.", "Just a quick note: the meeting is on Monday, see you there!", "This email is for tell you that the meeting is Monday."], correctIndex: 0, difficulty: 0.5, targetLevel: "B1", skill: "business_writing", feedback: NEUTRAL },
  { id: "su-39", question: "If we had checked the numbers, we ___ the mistake.", options: ["would have noticed", "would notice", "will notice", "noticed"], correctIndex: 0, difficulty: 0.64, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-40", question: "By the time the client called, we ___ the proposal.", options: ["had already sent", "have already sent", "would already send", "already sends"], correctIndex: 0, difficulty: 0.64, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-41", question: "When I started this job, I ___ getting up so early, but now it is no problem.", options: ["wasn't used to", "didn't use to", "wasn't use to", "wouldn't"], correctIndex: 0, difficulty: 0.66, targetLevel: "B2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-42", question: "The CEO is believed ___ the company before the scandal became public.", options: ["to have left", "to leave", "having left", "that he left"], correctIndex: 0, difficulty: 0.78, targetLevel: "B2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-43", question: "She suggested ___ the meeting to next week.", options: ["moving", "to move", "move", "moved"], correctIndex: 0, difficulty: 0.6, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-44", question: "___ the traffic, we arrived on time.", options: ["Despite", "Although", "However", "Because"], correctIndex: 0, difficulty: 0.6, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-46", question: "All staff must comply ___ the new safety rules.", options: ["with", "to", "for", "by"], correctIndex: 0, difficulty: 0.68, targetLevel: "B2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-47", question: "He denied ___ the document.", options: ["sending", "to send", "send", "sent"], correctIndex: 0, difficulty: 0.67, targetLevel: "B2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-48", question: "We are ___ to meet our targets this quarter, so there is no need to worry.", options: ["likely", "probably", "possibly", "surely"], correctIndex: 0, difficulty: 0.6, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-79", question: "I wish you ___ me earlier. Now it's too late to change the plan.", options: ["had told", "tell", "would tell", "have told"], correctIndex: 0, difficulty: 0.72, targetLevel: "B2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-66", question: "Sorry I'm late. There was ___ accident on the highway, and ___ traffic was terrible.", options: ["an ... the", "an ... a", "the ... the", "a ... the"], correctIndex: 0, difficulty: 0.42, targetLevel: "A2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-49", question: "The manager asked us to ___ the plan before sending it to the client.", options: ["revise", "receive", "reveal", "retire"], correctIndex: 0, difficulty: 0.65, targetLevel: "B1", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-50", question: "Sales have ___ by 15 percent since January.", options: ["risen", "raised", "lifted", "arisen"], correctIndex: 0, difficulty: 0.66, targetLevel: "B2", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-51", question: "We need to ___ the risks before we make a decision.", options: ["weigh up", "pick up", "give up", "set up"], correctIndex: 0, difficulty: 0.76, targetLevel: "B2", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-52", question: "The offer is only ___ until Friday, so we must decide soon.", options: ["valid", "useful", "probable", "capable"], correctIndex: 0, difficulty: 0.64, targetLevel: "B1", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-53", question: "I'd like to ___ your attention to a mistake on page two.", options: ["draw", "pull", "take", "hold"], correctIndex: 0, difficulty: 0.75, targetLevel: "B2", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-54", question: "What do the results of the trial suggest?", options: ["Shorter weeks did not harm productivity for most firms", "Workers produced much more in four days", "Pay had to be reduced after six months", "Hospitals have already adopted the model"], correctIndex: 0, difficulty: 0.66, targetLevel: "B2", readingPassage: "Many companies are now offering four-day working weeks. In a recent trial, 60 firms shortened the working week without cutting pay. After six months, most of them reported that productivity had stayed the same or improved, and fewer employees left their jobs. Yet some managers worry that customers may be harder to reach on the fifth day, and that the model may not suit every industry, such as hospitals or shops.", skill: "reading", feedback: NEUTRAL },
  { id: "su-55", question: "Why did the company decide not to renew the contract?", options: ["The cost went up and complaints were not dealt with quickly", "The cleaners had stopped coming to the office", "Staff said the cleaning was not done often enough", "The company wanted to save 20 percent on all contracts"], correctIndex: 0, difficulty: 0.7, targetLevel: "B2", readingPassage: "Dear colleagues, following last month's review, we have decided not to renew our contract with the current cleaning company. While their service was generally acceptable, costs rose by 20 percent and several complaints were not resolved promptly. We will ask other companies to send us offers next week, and any team leader who wishes to give input on requirements should contact me before Friday.", skill: "reading", feedback: NEUTRAL },
  { id: "su-56", question: "What does the writer think about the section on risks?", options: ["It may be too positive", "It is perfect as it is", "It is too long", "It should be removed"], correctIndex: 0, difficulty: 0.7, targetLevel: "B2", readingPassage: "Thanks for sending the draft. I read it twice and, while the structure is clear, I wonder whether the section on risks is perhaps a little optimistic. Could we look at it together before it goes to the board?", skill: "reading", feedback: NEUTRAL },
  { id: "su-57", question: "🎧 What does the speaker suggest?", options: ["Keep investing online and review the small stores", "Close the small stores now", "Stop investing online", "Open more stores in big cities"], correctIndex: 0, difficulty: 0.67, targetLevel: "B2", type: 'listening_match', audio_script: "Right, so the figures for the third quarter are in, and they're mixed. Online sales are up by about eight percent, which is encouraging, but the stores are still struggling, especially outside the big cities. I'd suggest we keep investing online and take a closer look at the smaller stores before deciding whether to close any.", skill: "listening", feedback: NEUTRAL },
  { id: "su-58", question: "🎧 What is the speaker's opinion about adding more people?", options: ["It might not make the work faster", "It will solve the problem", "It is too expensive", "It was already decided"], correctIndex: 0, difficulty: 0.72, targetLevel: "B2", type: 'listening_match', audio_script: "I know the deadline is tight, but I'm not convinced that adding more people at this stage would actually speed things up. New people need time to learn the system, and that would take attention away from the people who are already working on it.", skill: "listening", feedback: NEUTRAL },
  { id: "su-59", question: "🎧 What choice is the caller offering?", options: ["A later date, or the same date at extra cost", "A refund, or a later date at no cost", "The same date, but with a different truck", "Free delivery, but only on the twelfth"], correctIndex: 0, difficulty: 0.68, targetLevel: "B2", type: 'listening_match', audio_script: "Hello, this is Karen Wu from Brightside Logistics returning your call. Unfortunately, we can't deliver on the twelfth as you asked, because the truck is being repaired. We could do the fourteenth, or the twelfth by courier at an extra cost of about fifty dollars. Please let me know which you prefer.", skill: "listening", feedback: NEUTRAL },
  { id: "su-62", question: "We must reduce our costs. ___, we cannot lose our best employees.", options: ["At the same time", "As a result", "For instance", "In other words"], correctIndex: 0, difficulty: 0.72, targetLevel: "B2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-63", question: "You disagree with a colleague in a meeting. Which is the most diplomatic?", options: ["I see your point, but I wonder if we should also consider the cost.", "I understand, but you must consider the cost before we decide.", "I see your point, but you are ignoring the cost completely.", "I disagree because the cost is much too high for us."], correctIndex: 0, difficulty: 0.6, targetLevel: "B1", skill: "fluency", feedback: NEUTRAL },
  { id: "su-64", question: "No sooner ___ the office than it started to rain.", options: ["had she left", "she had left", "did she leave", "she left"], correctIndex: 0, difficulty: 0.87, targetLevel: "C1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-65", question: "Had the board been informed earlier, it ___ a different decision.", options: ["might have reached", "might reach", "would be reaching", "had reached"], correctIndex: 0, difficulty: 0.88, targetLevel: "C1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-67", question: "It was not until the audit began ___ the problem became clear.", options: ["that", "when", "which", "than"], correctIndex: 0, difficulty: 0.85, targetLevel: "C1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-68", question: "When asked about layoffs, the CEO gave a ___ answer that neither confirmed nor denied the rumors.", options: ["noncommittal", "straightforward", "emphatic", "spontaneous"], correctIndex: 0, difficulty: 0.88, targetLevel: "C1", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-69", question: "The two reports ___ each other: one says sales rose, the other says they fell.", options: ["contradict", "complement", "confirm", "resemble"], correctIndex: 0, difficulty: 0.7, targetLevel: "B2", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-70", question: "Several experts have questioned the ___ of the survey, saying the sample was too small.", options: ["validity", "novelty", "capacity", "sincerity"], correctIndex: 0, difficulty: 0.76, targetLevel: "B2", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-71", question: "The new law will have far-reaching ___ for small businesses.", options: ["implications", "locations", "applications", "explanations"], correctIndex: 0, difficulty: 0.8, targetLevel: "B2", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-72", question: "Profits ___ last year after the factory closed, and the company had to cut 200 jobs.", options: ["plummeted", "soared", "stabilized", "expanded"], correctIndex: 0, difficulty: 0.85, targetLevel: "C1", skill: "professional_vocabulary", feedback: NEUTRAL },
  { id: "su-73", question: "Why is the evidence described as inconclusive?", options: ["Most studies rely on people's own reports gathered at an unusual time", "Remote work has been tried in only a few companies", "The studies compared only large companies", "Few employees agreed to be interviewed"], correctIndex: 0, difficulty: 0.86, targetLevel: "C1", readingPassage: "Proponents of remote work often cite increased autonomy and reduced commuting as decisive advantages. Critics counter that the benefits are unevenly distributed: employees with spacious homes and reliable connections thrive, whereas others find the boundary between work and private life steadily eroding. The evidence, so far, is inconclusive, largely because most studies rely on self-reported data collected during an exceptional period.", skill: "reading", feedback: NEUTRAL },
  { id: "su-74", question: "What does the writer imply about the statement?", options: ["It looked open but left out key information", "It gave investors every figure", "It was written by the investors", "It refused to make any commitment"], correctIndex: 0, difficulty: 0.9, targetLevel: "C1", readingPassage: "The board's statement, while ostensibly a commitment to transparency, stopped short of disclosing the figures that investors had requested.", skill: "reading", feedback: NEUTRAL },
  { id: "su-75", question: "🎧 What is the speaker's main point?", options: ["Cutting costs everywhere would not fix the real problem", "Costs rose in every department equally", "The increase was a surprise to everyone", "Cuts should start with the largest department"], correctIndex: 0, difficulty: 0.87, targetLevel: "C1", type: 'listening_match', audio_script: "What's striking isn't that costs went up. Everyone expected that. It's that the increase was concentrated in a single department. Unless we understand why, any across-the-board cuts will simply treat the symptom, not the cause.", skill: "listening", feedback: NEUTRAL },
  { id: "su-80", question: "By this time next year, I ___ at this company for ten years.", options: ["will have worked", "will work", "have worked", "would have worked"], correctIndex: 0, difficulty: 0.74, targetLevel: "B2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-81", question: "We are having the new servers ___ next week.", options: ["installed", "install", "to install", "installing"], correctIndex: 0, difficulty: 0.7, targetLevel: "B2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-83", question: "The meeting is ___ Monday at 9 a.m.", options: ["on", "in", "at", "by"], correctIndex: 0, difficulty: 0.2, targetLevel: "A1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-84", question: "___ does the meeting start?", options: ["What time", "What hour", "How time", "At what clock"], correctIndex: 0, difficulty: 0.32, targetLevel: "A2", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-85", question: "Could you tell me where ___?", options: ["the station is", "is the station", "the station does", "does the station"], correctIndex: 0, difficulty: 0.58, targetLevel: "B1", skill: "grammar_accuracy", feedback: NEUTRAL },
  { id: "su-86", question: "🎧 What time is the meeting?", options: ["5:00", "9:00", "9:30", "10:00"], correctIndex: 1, difficulty: 0.2, targetLevel: "A1", type: 'listening_match', audio_script: "Good morning. The meeting is at nine o'clock in Room Five. Please be on time.", skill: "listening", fixedOrder: true, feedback: NEUTRAL },
];
