/**
 * How each word in a one- or two-word line is pronounced (CMU ARPAbet,
 * General American), sent to the voice as an SSML <phoneme> tag so the voice
 * cannot guess: the 2026-10-02 sound-level audit heard single words like
 * "hat" as /hat/, "bag" as /bɛg/, "nut" as /nɑt/, "chick" as /tʃek/ and
 * "wand" as /vand/. Generated from the CMU Pronouncing Dictionary for every
 * word in a short line (scripts/voice-phoneme-audit.py lists them); a few
 * entries are pinned to the classroom reading (wind = weather, stressed
 * "in/is/are/to" when said alone).
 *
 * MIRROR: supabase/functions/_shared/pronunciations.ts must stay byte-identical.
 */
export const ARPABET: Record<string, string> = {
  again: 'AH0 G EH1 N',
  age: 'EY1 JH',
  alligator: 'AE1 L AH0 G EY2 T ER0',
  always: 'AO1 L W EY2 Z',
  angry: 'AE1 NG G R IY0',
  ant: 'AE1 N T',
  apple: 'AE1 P AH0 L',
  are: 'AA1 R',
  armchair: 'AA1 R M CH EH2 R',
  baby: 'B EY1 B IY0',
  bag: 'B AE1 G',
  ball: 'B AO1 L',
  balloon: 'B AH0 L UW1 N',
  balls: 'B AO1 L Z',
  basketball: 'B AE1 S K AH0 T B AO2 L',
  bat: 'B AE1 T',
  bathroom: 'B AE1 TH R UW2 M',
  bear: 'B EH1 R',
  bears: 'B EH1 R Z',
  bed: 'B EH1 D',
  bedroom: 'B EH1 D R UW2 M',
  behind: 'B IH0 HH AY1 N D',
  bella: 'B EH1 L AH0',
  blocks: 'B L AA1 K S',
  blue: 'B L UW1',
  book: 'B UH1 K',
  bookcase: 'B UH1 K K EY2 S',
  box: 'B AA1 K S',
  butterfly: 'B AH1 T ER0 F L AY2',
  bye: 'B AY1',
  candy: 'K AE1 N D IY0',
  cape: 'K EY1 P',
  car: 'K AA1 R',
  carrot: 'K AE1 R AH0 T',
  castle: 'K AE1 S AH0 L',
  cat: 'K AE1 T',
  chair: 'CH EH1 R',
  cheese: 'CH IY1 Z',
  chest: 'CH EH1 S T',
  chick: 'CH IH1 K',
  chip: 'CH IH1 P',
  chop: 'CH AA1 P',
  circle: 'S ER1 K AH0 L',
  clock: 'K L AA1 K',
  cookie: 'K UH1 K IY0',
  cotton: 'K AA1 T AH0 N',
  dad: 'D AE1 D',
  day: 'D EY1',
  desk: 'D EH1 S K',
  dining: 'D AY1 N IH0 NG',
  dinosaur: 'D AY1 N AH0 S AO2 R',
  doll: 'D AA1 L',
  done: 'D AH1 N',
  door: 'D AO1 R',
  duck: 'D AH1 K',
  egg: 'EH1 G',
  eight: 'EY1 T',
  family: 'F AE1 M AH0 L IY0',
  fan: 'F AE1 N',
  figure: 'F IH1 G Y ER0',
  fin: 'F IH1 N',
  find: 'F AY1 N D',
  fish: 'F IH1 SH',
  five: 'F AY1 V',
  flag: 'F L AE1 G',
  four: 'F AO1 R',
  fox: 'F AA1 K S',
  friday: 'F R AY1 D IY0',
  friend: 'F R EH1 N D',
  friends: 'F R EH1 N D Z',
  frog: 'F R AA1 G',
  garden: 'G AA1 R D AH0 N',
  goat: 'G OW1 T',
  goodbye: 'G UH2 D B AY1',
  grapes: 'G R EY1 P S',
  great: 'G R EY1 T',
  green: 'G R IY1 N',
  hallway: 'HH AO1 L W EY2',
  ham: 'HH AE1 M',
  happy: 'HH AE1 P IY0',
  has: 'HH AE1 Z',
  hat: 'HH AE1 T',
  he: 'HH IY1',
  hello: 'HH EH0 L OW1',
  hi: 'HH AY1',
  hope: 'HH OW1 P',
  house: 'HH AW1 S',
  hungry: 'HH AH1 NG G R IY0',
  i: 'AY1',
  igloo: 'IH1 G L UW0',
  in: 'IH1 N',
  ink: 'IH1 NG K',
  insect: 'IH1 N S EH2 K T',
  irregular: 'IH2 R EH1 G Y AH0 L ER0',
  is: 'IH1 Z',
  "it's": 'IH1 T S',
  jelly: 'JH EH1 L IY0',
  job: 'JH AA1 B',
  key: 'K IY1',
  kitchen: 'K IH1 CH AH0 N',
  kite: 'K AY1 T',
  knock: 'N AA1 K',
  lamp: 'L AE1 M P',
  last: 'L AE1 S T',
  leaf: 'L IY1 F',
  leg: 'L EH1 G',
  leo: 'L IY1 OW0',
  lion: 'L AY1 AH0 N',
  living: 'L IH1 V IH0 NG',
  lollipop: 'L AA1 L IY0 P AA2 P',
  lunch: 'L AH1 N CH',
  man: 'M AE1 N',
  mat: 'M AE1 T',
  mia: 'M IY1 AH0',
  milk: 'M IH1 L K',
  mirror: 'M IH1 R ER0',
  mom: 'M AA1 M',
  monday: 'M AH1 N D IY0',
  moon: 'M UW1 N',
  mouse: 'M AW1 S',
  name: 'N EY1 M',
  nest: 'N EH1 S T',
  net: 'N EH1 T',
  next: 'N EH1 K S T',
  nice: 'N AY1 S',
  night: 'N AY1 T',
  nine: 'N AY1 N',
  nose: 'N OW1 Z',
  nut: 'N AH1 T',
  octopus: 'AA1 K T AH0 P UH2 S',
  on: 'AA1 N',
  one: 'W AH1 N',
  orange: 'AO1 R AH0 N JH',
  owl: 'AW1 L',
  pan: 'P AE1 N',
  party: 'P AA1 R T IY0',
  pen: 'P EH1 N',
  pencil: 'P EH1 N S AH0 L',
  perfect: 'P ER1 F IH2 K T',
  pig: 'P IH1 G',
  pin: 'P IH1 N',
  pip: 'P IH1 P',
  pizza: 'P IY1 T S AH0',
  play: 'P L EY1',
  plum: 'P L AH1 M',
  popcorn: 'P AA1 P K AO2 R N',
  practice: 'P R AE1 K T AH0 S',
  present: 'P R EH1 Z AH0 N T',
  purple: 'P ER1 P AH0 L',
  queen: 'K W IY1 N',
  rainbow: 'R EY1 N B OW2',
  red: 'R EH1 D',
  regular: 'R EH1 G Y AH0 L ER0',
  ribbon: 'R IH1 B AH0 N',
  ring: 'R IH1 NG',
  room: 'R UW1 M',
  rose: 'R OW1 Z',
  sad: 'S AE1 D',
  sam: 'S AE1 M',
  sat: 'S AE1 T',
  saturday: 'S AE1 T ER0 D IY0',
  school: 'S K UW1 L',
  see: 'S IY1',
  seven: 'S EH1 V AH0 N',
  she: 'SH IY1',
  sheep: 'SH IY1 P',
  shell: 'SH EH1 L',
  ship: 'SH IH1 P',
  shop: 'SH AA1 P',
  sip: 'S IH1 P',
  sit: 'S IH1 T',
  six: 'S IH1 K S',
  sleep: 'S L IY1 P',
  slept: 'S L EH1 P T',
  slide: 'S L AY1 D',
  snake: 'S N EY1 K',
  soccer: 'S AA1 K ER0',
  sock: 'S AA1 K',
  sofa: 'S OW1 F AH0',
  square: 'S K W EH1 R',
  star: 'S T AA1 R',
  stay: 'S T EY1',
  stir: 'S T ER1',
  student: 'S T UW1 D AH0 N T',
  sun: 'S AH1 N',
  sunday: 'S AH1 N D EY2',
  sunflower: 'S AH1 N F L AW2 ER0',
  swing: 'S W IH1 NG',
  table: 'T EY1 B AH0 L',
  tap: 'T AE1 P',
  taxi: 'T AE1 K S IY0',
  teacher: 'T IY1 CH ER0',
  teddy: 'T EH1 D IY0',
  ten: 'T EH1 N',
  they: 'DH EY1',
  thirsty: 'TH ER1 S T IY0',
  three: 'TH R IY1',
  thursday: 'TH ER1 Z D EY2',
  tiger: 'T AY1 G ER0',
  tired: 'T AY1 ER0 D',
  to: 'T UW1',
  toy: 'T OY1',
  train: 'T R EY1 N',
  tree: 'T R IY1',
  triangle: 'T R AY1 AE2 NG G AH0 L',
  truck: 'T R AH1 K',
  try: 'T R AY1',
  tuesday: 'T UW1 Z D IY0',
  turtle: 'T ER1 T AH0 L',
  two: 'T UW1',
  umbrella: 'AH0 M B R EH1 L AH0',
  under: 'AH1 N D ER0',
  van: 'V AE1 N',
  walked: 'W AO1 K T',
  wand: 'W AA1 N D',
  water: 'W AO1 T ER0',
  wave: 'W EY1 V',
  web: 'W EH1 B',
  wednesday: 'W EH1 N Z D IY0',
  welcome: 'W EH1 L K AH0 M',
  well: 'W EH1 L',
  whale: 'W EY1 L',
  what: 'W AH1 T',
  wheel: 'W IY1 L',
  whistle: 'W IH1 S AH0 L',
  wig: 'W IH1 G',
  willow: 'W IH1 L OW2',
  win: 'W IH1 N',
  wind: 'W IH1 N D',
  window: 'W IH1 N D OW0',
  wizard: 'W IH1 Z ER0 D',
  wow: 'W AW1',
  xylophone: 'Z AY1 L AH0 F OW2 N',
  yarn: 'Y AA1 R N',
  yellow: 'Y EH1 L OW0',
  yes: 'Y EH1 S',
  yesterday: 'Y EH1 S T ER0 D EY2',
  yo: 'Y OW1',
  zebra: 'Z IY1 B R AH0',
};

/** Wraps every word that has an entry in a <phoneme> tag (models that support
 *  them: English-only Turbo/Flash v2). Punctuation stays outside the tags. */
export function withPhonemes(text: string): string {
  return text.replace(/[A-Za-z][A-Za-z']*/g, (word) => {
    const ph = ARPABET[word.toLowerCase()];
    return ph ? `<phoneme alphabet="cmu-arpabet" ph="${ph}">${word}</phoneme>` : word;
  });
}
