// Activity catalog — metadata used by the selector. No randomness.

import type { ActivityCatalogEntry, ActivityType } from '../types';

export const ACTIVITY_CATALOG: Record<ActivityType, ActivityCatalogEntry> = {
  warmup: {
    type: 'warmup',
    modalities: ['listening', 'thinking'],
    fits_stages: ['hook'],
    fits_purposes: ['hook'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 1, academy: 0.8, success: 0.6 },
    load: 'low', productive: false,
    description: 'Short hook that activates curiosity and prior knowledge.',
  },
  poll: {
    type: 'poll',
    modalities: ['thinking', 'reflection'],
    fits_stages: ['hook', 'context', 'reflection'],
    fits_purposes: ['hook', 'reflection'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.5, academy: 0.9, success: 0.8 },
    load: 'low', productive: false,
    description: 'Quick opinion poll bound to the theme.',
  },
  opinion: {
    type: 'opinion',
    modalities: ['speaking', 'thinking'],
    fits_stages: ['communicative', 'production', 'reflection'],
    fits_purposes: ['communicative', 'reflection'],
    min_cefr: 'A2', max_cefr: 'C1',
    hub_fit: { playground: 0.3, academy: 1, success: 0.9 },
    load: 'medium', productive: true,
    description: 'Open opinion prompt grounded in lesson scenario.',
  },
  matching: {
    type: 'matching',
    modalities: ['reading', 'thinking'],
    fits_stages: ['input', 'controlled', 'review'],
    fits_purposes: ['input', 'controlled', 'review'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 1, academy: 0.8, success: 0.7 },
    load: 'low', productive: false,
    description: 'Match words/phrases/images to meanings.',
  },
  drag_drop: {
    type: 'drag_drop',
    modalities: ['reading', 'thinking'],
    fits_stages: ['controlled', 'discovery'],
    fits_purposes: ['controlled', 'discovery'],
    min_cefr: 'Pre-A1', max_cefr: 'B2',
    hub_fit: { playground: 1, academy: 0.7, success: 0.5 },
    load: 'medium', productive: false,
    description: 'Drag items into categories or sentence positions.',
  },
  fill_blank: {
    type: 'fill_blank',
    modalities: ['reading', 'writing'],
    fits_stages: ['controlled', 'discovery', 'review'],
    fits_purposes: ['controlled', 'review'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.7, academy: 0.9, success: 0.9 },
    load: 'medium', productive: false,
    description: 'Cloze items embedded in scenario sentences.',
  },
  sentence_builder: {
    type: 'sentence_builder',
    modalities: ['writing', 'thinking'],
    fits_stages: ['controlled', 'production'],
    fits_purposes: ['controlled', 'production'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.7, academy: 0.9, success: 0.9 },
    load: 'medium', productive: true,
    description: 'Construct sentences from scrambled tokens or prompts.',
  },
  pronunciation: {
    type: 'pronunciation',
    modalities: ['speaking', 'listening'],
    fits_stages: ['input', 'controlled', 'communicative'],
    fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 1, academy: 0.8, success: 0.8 },
    load: 'medium', productive: true,
    description: 'Repeat-after-me or minimal-pair pronunciation drill in context.',
  },
  reading: {
    type: 'reading',
    modalities: ['reading', 'thinking'],
    fits_stages: ['input', 'context'],
    fits_purposes: ['input'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.6, academy: 0.9, success: 0.9 },
    load: 'medium', productive: false,
    description: 'Short scenario passage with comprehension question(s).',
  },
  listening: {
    type: 'listening',
    modalities: ['listening', 'thinking'],
    fits_stages: ['input', 'context'],
    fits_purposes: ['input'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 0.9, academy: 0.9, success: 0.9 },
    load: 'medium', productive: false,
    description: 'Audio scene with focused comprehension task.',
  },
  roleplay: {
    type: 'roleplay',
    modalities: ['speaking', 'collaboration'],
    fits_stages: ['communicative', 'production'],
    fits_purposes: ['communicative', 'production'],
    min_cefr: 'A2', max_cefr: 'C1',
    hub_fit: { playground: 0.5, academy: 1, success: 1 },
    load: 'high', productive: true,
    description: 'Two-role scripted-then-free dialogue inside the scenario.',
  },
  debate: {
    type: 'debate',
    modalities: ['speaking', 'thinking'],
    fits_stages: ['communicative', 'production'],
    fits_purposes: ['communicative', 'production'],
    min_cefr: 'B1', max_cefr: 'C1',
    hub_fit: { playground: 0, academy: 0.8, success: 1 },
    load: 'high', productive: true,
    description: 'Take-a-side discussion grounded in the lesson scenario.',
  },
  speaking_mission: {
    type: 'speaking_mission',
    modalities: ['speaking'],
    fits_stages: ['production', 'communicative'],
    fits_purposes: ['production', 'communicative'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 0.8, academy: 1, success: 1 },
    load: 'high', productive: true,
    description: 'Real-world speaking goal the learner performs.',
  },
  storytelling: {
    type: 'storytelling',
    modalities: ['speaking', 'thinking'],
    fits_stages: ['production', 'context'],
    fits_purposes: ['production'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 1, academy: 0.8, success: 0.6 },
    load: 'high', productive: true,
    description: 'Continue or retell the lesson scenario.',
  },
  collaborative: {
    type: 'collaborative',
    modalities: ['collaboration', 'speaking'],
    fits_stages: ['communicative', 'production'],
    fits_purposes: ['communicative', 'production'],
    min_cefr: 'A2', max_cefr: 'C1',
    hub_fit: { playground: 0.5, academy: 1, success: 0.8 },
    load: 'high', productive: true,
    description: 'Pair/group task with shared goal inside the scenario.',
  },
  reflection: {
    type: 'reflection',
    modalities: ['reflection', 'thinking'],
    fits_stages: ['reflection'],
    fits_purposes: ['reflection'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 0.7, academy: 0.9, success: 1 },
    load: 'low', productive: false,
    description: 'Metacognitive prompt connecting lesson to learner identity.',
  },
  retrieval: {
    type: 'retrieval',
    modalities: ['thinking', 'writing'],
    fits_stages: ['review', 'reflection'],
    fits_purposes: ['review'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 0.7, academy: 0.8, success: 0.8 },
    load: 'medium', productive: false,
    description: 'Recall-from-memory check on target vocab/grammar.',
  },
  review_challenge: {
    type: 'review_challenge',
    modalities: ['thinking', 'speaking'],
    fits_stages: ['review', 'production'],
    fits_purposes: ['review'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.6, academy: 0.9, success: 1 },
    load: 'medium', productive: true,
    description: 'Higher-stakes mixed challenge to consolidate the lesson.',
  },
};

export const ALL_ACTIVITY_TYPES = Object.keys(ACTIVITY_CATALOG) as ActivityType[];
