// Activity catalog — metadata used by the selector. No randomness.

import type { ActivityCatalogEntry, ActivityType } from '../types';

export const ACTIVITY_CATALOG: Record<ActivityType, ActivityCatalogEntry> = {
  warmup: {
    type: 'warmup',
    modalities: ['listening', 'thinking'],
    fits_stages: ['hook'],
    fits_purposes: ['hook'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 1, academy: 0.8, success: 0.6 },
    load: 'low', productive: false,
    description: 'Short hook that activates curiosity and prior knowledge.',
  },
  poll: {
    type: 'poll',
    modalities: ['thinking', 'reflection'],
    fits_stages: ['hook', 'context', 'reflection'],
    fits_purposes: ['hook', 'reflection'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.5, academy: 0.9, success: 0.8 },
    load: 'low', productive: false,
    description: 'Quick opinion poll bound to the theme.',
  },
  opinion: {
    type: 'opinion',
    modalities: ['speaking', 'thinking'],
    fits_stages: ['communicative', 'production', 'reflection'],
    fits_purposes: ['communicative', 'reflection'],
    min_cefr: 'A2', max_cefr: 'C1',
    hub_fit: { playground: 0.3, academy: 1, success: 0.9 },
    load: 'medium', productive: true,
    description: 'Open opinion prompt grounded in lesson scenario.',
  },
  matching: {
    type: 'matching',
    modalities: ['reading', 'thinking'],
    fits_stages: ['input', 'controlled'],
    fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 1, academy: 0.8, success: 0.7 },
    load: 'low', productive: false,
    description: 'Match words/phrases/images to meanings.',
  },
  drag_drop: {
    type: 'drag_drop',
    modalities: ['reading', 'thinking'],
    fits_stages: ['controlled', 'discovery'],
    fits_purposes: ['controlled', 'discovery'],
    min_cefr: 'Pre-A1', max_cefr: 'B2',
    hub_fit: { playground: 1, academy: 0.7, success: 0.5 },
    load: 'medium', productive: false,
    description: 'Drag items into categories or sentence positions.',
  },
  fill_blank: {
    type: 'fill_blank',
    modalities: ['reading', 'writing'],
    fits_stages: ['controlled', 'discovery'],
    fits_purposes: ['controlled', 'reflection'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.7, academy: 0.9, success: 0.9 },
    load: 'medium', productive: false,
    description: 'Cloze items embedded in scenario sentences.',
  },
  sentence_builder: {
    type: 'sentence_builder',
    modalities: ['writing', 'thinking'],
    fits_stages: ['controlled', 'production'],
    fits_purposes: ['controlled', 'production'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.7, academy: 0.9, success: 0.9 },
    load: 'medium', productive: true,
    description: 'Construct sentences from scrambled tokens or prompts.',
  },
  pronunciation: {
    type: 'pronunciation',
    modalities: ['speaking', 'listening'],
    fits_stages: ['input', 'controlled', 'communicative'],
    fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 1, academy: 0.8, success: 0.8 },
    load: 'medium', productive: true,
    description: 'Repeat-after-me or minimal-pair pronunciation drill in context.',
  },
  reading: {
    type: 'reading',
    modalities: ['reading', 'thinking'],
    fits_stages: ['input', 'context'],
    fits_purposes: ['input'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.6, academy: 0.9, success: 0.9 },
    load: 'medium', productive: false,
    description: 'Short scenario passage with comprehension question(s).',
  },
  listening: {
    type: 'listening',
    modalities: ['listening', 'thinking'],
    fits_stages: ['input', 'context'],
    fits_purposes: ['input'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 0.9, academy: 0.9, success: 0.9 },
    load: 'medium', productive: false,
    description: 'Audio scene with focused comprehension task.',
  },
  roleplay: {
    type: 'roleplay',
    modalities: ['speaking', 'collaboration'],
    fits_stages: ['communicative', 'production'],
    fits_purposes: ['communicative', 'production'],
    min_cefr: 'A2', max_cefr: 'C1',
    hub_fit: { playground: 0.5, academy: 1, success: 1 },
    load: 'high', productive: true,
    description: 'Two-role scripted-then-free dialogue inside the scenario.',
  },
  debate: {
    type: 'debate',
    modalities: ['speaking', 'thinking'],
    fits_stages: ['communicative', 'production'],
    fits_purposes: ['communicative', 'production'],
    min_cefr: 'B1', max_cefr: 'C1',
    hub_fit: { playground: 0, academy: 0.8, success: 1 },
    load: 'high', productive: true,
    description: 'Take-a-side discussion grounded in the lesson scenario.',
  },
  speaking_mission: {
    type: 'speaking_mission',
    modalities: ['speaking'],
    fits_stages: ['production', 'communicative'],
    fits_purposes: ['production', 'communicative'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 0.8, academy: 1, success: 1 },
    load: 'high', productive: true,
    description: 'Real-world speaking goal the learner performs.',
  },
  storytelling: {
    type: 'storytelling',
    modalities: ['speaking', 'thinking'],
    fits_stages: ['production', 'context'],
    fits_purposes: ['production'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 1, academy: 0.8, success: 0.6 },
    load: 'high', productive: true,
    description: 'Continue or retell the lesson scenario.',
  },
  collaborative: {
    type: 'collaborative',
    modalities: ['collaboration', 'speaking'],
    fits_stages: ['communicative', 'production'],
    fits_purposes: ['communicative', 'production'],
    min_cefr: 'A2', max_cefr: 'C1',
    hub_fit: { playground: 0.5, academy: 1, success: 0.8 },
    load: 'high', productive: true,
    description: 'Pair/group task with shared goal inside the scenario.',
  },
  reflection: {
    type: 'reflection',
    modalities: ['reflection', 'thinking'],
    fits_stages: ['reflection'],
    fits_purposes: ['reflection'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 0.7, academy: 0.9, success: 1 },
    load: 'low', productive: false,
    description: 'Metacognitive prompt connecting lesson to learner identity.',
  },
  retrieval: {
    type: 'retrieval',
    modalities: ['thinking', 'writing'],
    fits_stages: ['reflection'],
    fits_purposes: ['review'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 0.7, academy: 0.8, success: 0.8 },
    load: 'medium', productive: false,
    description: 'Recall-from-memory check on target vocab/grammar.',
  },
  review_challenge: {
    type: 'review_challenge',
    modalities: ['thinking', 'speaking'],
    fits_stages: ['production'],
    fits_purposes: ['review'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.6, academy: 0.9, success: 1 },
    load: 'medium', productive: true,
    description: 'Higher-stakes mixed challenge to consolidate the lesson.',
  },
  // ───────── Phonics & Trace (Playground-first) ─────────
  trace_letter: {
    type: 'trace_letter',
    modalities: ['thinking', 'writing'],
    fits_stages: ['input', 'controlled'],
    fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'A1',
    hub_fit: { playground: 1, academy: 0, success: 0 },
    load: 'low', productive: false,
    description: 'Trace a single letter along an SVG stroke path; rainbow mode optional.',
  },
  trace_word: {
    type: 'trace_word',
    modalities: ['thinking', 'writing', 'reading'],
    fits_stages: ['controlled', 'production'],
    fits_purposes: ['controlled', 'production'],
    min_cefr: 'Pre-A1', max_cefr: 'A1',
    hub_fit: { playground: 1, academy: 0, success: 0 },
    load: 'medium', productive: false,
    description: 'Trace a CVC/decodable word along a stroke path while saying the sounds.',
  },
  phoneme_tap: {
    type: 'phoneme_tap',
    modalities: ['listening', 'thinking'],
    fits_stages: ['input', 'discovery'],
    fits_purposes: ['input', 'discovery'],
    min_cefr: 'Pre-A1', max_cefr: 'A1',
    hub_fit: { playground: 1, academy: 0.2, success: 0 },
    load: 'low', productive: false,
    description: 'Tap the box for each phoneme heard in a target word.',
  },
  blend_builder: {
    type: 'blend_builder',
    modalities: ['reading', 'thinking'],
    fits_stages: ['controlled', 'discovery'],
    fits_purposes: ['controlled', 'discovery'],
    min_cefr: 'Pre-A1', max_cefr: 'A2',
    hub_fit: { playground: 1, academy: 0.3, success: 0 },
    load: 'medium', productive: false,
    description: 'Drag onset + rime (or graphemes) together to build a target blend/word.',
  },
  rhyme_match: {
    type: 'rhyme_match',
    modalities: ['listening', 'thinking'],
    fits_stages: ['input', 'controlled'],
    fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'A1',
    hub_fit: { playground: 1, academy: 0.1, success: 0 },
    load: 'low', productive: false,
    description: 'Match words that rhyme (cat / hat / mat) using audio + image.',
  },
  cvc_builder: {
    type: 'cvc_builder',
    modalities: ['reading', 'writing'],
    fits_stages: ['controlled', 'production'],
    fits_purposes: ['controlled', 'production'],
    min_cefr: 'Pre-A1', max_cefr: 'A1',
    hub_fit: { playground: 1, academy: 0, success: 0 },
    load: 'medium', productive: true,
    description: 'Build a CVC word from three grapheme tiles to match an image.',
  },
  sound_hunt: {
    type: 'sound_hunt',
    modalities: ['listening', 'thinking', 'reading'],
    fits_stages: ['discovery', 'controlled'],
    fits_purposes: ['discovery', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'A2',
    hub_fit: { playground: 1, academy: 0.2, success: 0 },
    load: 'medium', productive: false,
    description: 'Find all images/words containing the target phoneme.',
  },
  decode_the_word: {
    type: 'decode_the_word',
    modalities: ['reading', 'speaking'],
    fits_stages: ['controlled', 'production'],
    fits_purposes: ['controlled', 'production'],
    min_cefr: 'Pre-A1', max_cefr: 'A2',
    hub_fit: { playground: 1, academy: 0.3, success: 0 },
    load: 'medium', productive: true,
    description: 'Sound out a decodable word grapheme-by-grapheme then say it.',
  },

  // ───────── Listening-first ─────────
  listen_and_match: {
    type: 'listen_and_match',
    modalities: ['listening', 'thinking'],
    fits_stages: ['input', 'controlled'],
    fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'B1',
    hub_fit: { playground: 1, academy: 0.8, success: 0.5 },
    load: 'low', productive: false,
    description: 'Hear a word/phrase; tap the matching image or text.',
  },
  audio_to_image_match: {
    type: 'audio_to_image_match',
    modalities: ['listening', 'thinking'],
    fits_stages: ['input', 'controlled'],
    fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'A2',
    hub_fit: { playground: 1, academy: 0.5, success: 0.2 },
    load: 'low', productive: false,
    description: 'Pure audio cue → choose correct picture from a 2–4 set.',
  },
  sound_discrimination: {
    type: 'sound_discrimination',
    modalities: ['listening', 'thinking'],
    fits_stages: ['input', 'discovery'],
    fits_purposes: ['input', 'discovery'],
    min_cefr: 'Pre-A1', max_cefr: 'B2',
    hub_fit: { playground: 1, academy: 0.8, success: 0.7 },
    load: 'low', productive: false,
    description: 'Same/different minimal-pair discrimination.',
  },
  echo_repetition: {
    type: 'echo_repetition',
    modalities: ['listening', 'speaking'],
    fits_stages: ['input', 'controlled', 'communicative'],
    fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 1, academy: 0.9, success: 0.8 },
    load: 'medium', productive: true,
    description: 'Listen then repeat (echo) — first lowest rung of the speaking ladder.',
  },

  // ───────── Phase 4 listening-first additions ─────────
  listening_hunt: {
    type: 'listening_hunt',
    modalities: ['listening', 'thinking'],
    fits_stages: ['input', 'controlled'],
    fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'B1',
    hub_fit: { playground: 1, academy: 0.7, success: 0.4 },
    load: 'low', productive: false,
    description: 'Find every audio clip that contains the target word/sound.',
  },
  audio_sequence: {
    type: 'audio_sequence',
    modalities: ['listening', 'thinking'],
    fits_stages: ['controlled', 'communicative'],
    fits_purposes: ['controlled', 'communicative'],
    min_cefr: 'A1', max_cefr: 'B2',
    hub_fit: { playground: 0.7, academy: 1, success: 0.8 },
    load: 'medium', productive: false,
    description: 'Order audio clips into the correct narrative sequence.',
  },
  dictation_builder: {
    type: 'dictation_builder',
    modalities: ['listening', 'writing'],
    fits_stages: ['controlled', 'production'],
    fits_purposes: ['controlled', 'production'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.5, academy: 1, success: 0.9 },
    load: 'high', productive: true,
    description: 'Listen and reconstruct the sentence from tiles or typed input.',
  },
  pronunciation_tap: {
    type: 'pronunciation_tap',
    modalities: ['listening', 'speaking'],
    fits_stages: ['input', 'controlled'],
    fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'B2',
    hub_fit: { playground: 1, academy: 0.8, success: 0.6 },
    load: 'low', productive: true,
    description: 'Tap the stressed syllable / target phoneme as it is spoken.',
  },
  minimal_pairs: {
    type: 'minimal_pairs',
    modalities: ['listening', 'thinking'],
    fits_stages: ['input', 'discovery'],
    fits_purposes: ['input', 'discovery'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 0.9, academy: 1, success: 0.9 },
    load: 'low', productive: false,
    description: 'Discriminate minimal pairs (ship/sheep, bit/beat) by ear.',
  },

  // ───────── Phase 5 visual grammar + drill ─────────
  grammar_color_builder: {
    type: 'grammar_color_builder',
    modalities: ['reading', 'writing'],
    fits_stages: ['discovery', 'controlled'],
    fits_purposes: ['discovery', 'controlled'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.7, academy: 1, success: 0.9 },
    load: 'medium', productive: false,
    description: 'Color-code aux/ending/base/time/negative/question parts in a sentence.',
  },
  timeline_drag: {
    type: 'timeline_drag',
    modalities: ['reading', 'thinking'],
    fits_stages: ['discovery', 'controlled'],
    fits_purposes: ['discovery', 'controlled'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.8, academy: 1, success: 0.9 },
    load: 'medium', productive: false,
    description: 'Drag sentences onto a past/present/future timeline.',
  },
  tense_transform: {
    type: 'tense_transform',
    modalities: ['reading', 'writing'],
    fits_stages: ['controlled', 'semi_controlled' as any],
    fits_purposes: ['controlled'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.5, academy: 1, success: 0.9 },
    load: 'high', productive: true,
    description: 'Transform a seed sentence: positive → negative → question → short answer.',
  },
  substitution_drill: {
    type: 'substitution_drill',
    modalities: ['speaking', 'reading'],
    fits_stages: ['controlled'],
    fits_purposes: ['controlled'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.6, academy: 1, success: 0.8 },
    load: 'medium', productive: true,
    description: 'Swap one slot at a time, keeping the structure constant.',
  },
  rapid_fire_drill: {
    type: 'rapid_fire_drill',
    modalities: ['speaking', 'thinking'],
    fits_stages: ['controlled'],
    fits_purposes: ['controlled'],
    min_cefr: 'A2', max_cefr: 'C1',
    hub_fit: { playground: 0.3, academy: 1, success: 0.9 },
    load: 'high', productive: true,
    description: 'Fast-paced cue → response chain (≤3s per item).',
  },
  grammar_sort: {
    type: 'grammar_sort',
    modalities: ['reading', 'thinking'],
    fits_stages: ['discovery', 'controlled'],
    fits_purposes: ['discovery', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'B2',
    hub_fit: { playground: 0.9, academy: 1, success: 0.7 },
    load: 'low', productive: false,
    description: 'Sort sentences/words into grammar buckets (e.g., past/present, countable/uncountable).',
  },
  sentence_expansion: {
    type: 'sentence_expansion',
    modalities: ['writing', 'speaking'],
    fits_stages: ['communicative' as any, 'production'],
    fits_purposes: ['production', 'communicative'],
    min_cefr: 'A1', max_cefr: 'C1',
    hub_fit: { playground: 0.6, academy: 1, success: 0.9 },
    load: 'high', productive: true,
    description: 'Expand a core sentence by adding one element at a time (who/when/where/why).',
  },
  chunk_builder: {
    type: 'chunk_builder',
    modalities: ['reading', 'speaking'],
    fits_stages: ['controlled', 'communicative' as any],
    fits_purposes: ['controlled', 'communicative'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 0.8, academy: 1, success: 0.9 },
    load: 'medium', productive: true,
    description: 'Assemble fluent utterances from pre-baked grammatical chunks.',
  },
  // ── Phase 7 premium expansion ──
  syllable_clap: { type: 'syllable_clap', modalities: ['listening', 'speaking'], fits_stages: ['input', 'controlled'], fits_purposes: ['input', 'controlled'], min_cefr: 'Pre-A1', max_cefr: 'A2', hub_fit: { playground: 1, academy: 0.3, success: 0 }, load: 'low', productive: true, description: 'Clap once per syllable while saying the word.' },
  onset_rime_builder: { type: 'onset_rime_builder', modalities: ['reading', 'listening'], fits_stages: ['input', 'controlled'], fits_purposes: ['input', 'controlled'], min_cefr: 'Pre-A1', max_cefr: 'A1', hub_fit: { playground: 1, academy: 0.2, success: 0 }, load: 'low', productive: false, description: 'Combine an onset (c-) with a rime (-at) to build words.' },
  drag_the_letters: { type: 'drag_the_letters', modalities: ['reading', 'thinking'], fits_stages: ['input', 'controlled'], fits_purposes: ['input', 'controlled'], min_cefr: 'Pre-A1', max_cefr: 'A1', hub_fit: { playground: 1, academy: 0.2, success: 0 }, load: 'low', productive: false, description: 'Drag scattered letters into order to spell the target word.' },
  missing_sound: { type: 'missing_sound', modalities: ['listening', 'reading'], fits_stages: ['input', 'controlled'], fits_purposes: ['input', 'controlled'], min_cefr: 'Pre-A1', max_cefr: 'A2', hub_fit: { playground: 1, academy: 0.3, success: 0 }, load: 'low', productive: false, description: 'Identify the missing phoneme in a heard word.' },
  phonics_bingo: { type: 'phonics_bingo', modalities: ['listening', 'reading'], fits_stages: ['controlled', 'reflection'], fits_purposes: ['controlled', 'reflection'], min_cefr: 'Pre-A1', max_cefr: 'A2', hub_fit: { playground: 1, academy: 0.2, success: 0 }, load: 'medium', productive: false, description: 'Mark the grapheme tile that matches the called sound.' },
  tap_the_grapheme: { type: 'tap_the_grapheme', modalities: ['listening', 'reading'], fits_stages: ['input', 'controlled'], fits_purposes: ['input', 'controlled'], min_cefr: 'Pre-A1', max_cefr: 'A2', hub_fit: { playground: 1, academy: 0.3, success: 0 }, load: 'low', productive: false, description: 'Tap the letter(s) that make the heard sound.' },
  sound_sorting: { type: 'sound_sorting', modalities: ['listening', 'thinking'], fits_stages: ['controlled', 'discovery'], fits_purposes: ['controlled', 'discovery'], min_cefr: 'Pre-A1', max_cefr: 'A2', hub_fit: { playground: 1, academy: 0.3, success: 0 }, load: 'medium', productive: false, description: 'Sort words/pictures into buckets by initial/medial/final sound.' },
  beginning_sound: { type: 'beginning_sound', modalities: ['listening'], fits_stages: ['input', 'controlled'], fits_purposes: ['input', 'controlled'], min_cefr: 'Pre-A1', max_cefr: 'A1', hub_fit: { playground: 1, academy: 0.2, success: 0 }, load: 'low', productive: false, description: 'Identify the beginning sound of a spoken word.' },
  ending_sound: { type: 'ending_sound', modalities: ['listening'], fits_stages: ['input', 'controlled'], fits_purposes: ['input', 'controlled'], min_cefr: 'Pre-A1', max_cefr: 'A1', hub_fit: { playground: 1, academy: 0.2, success: 0 }, load: 'low', productive: false, description: 'Identify the ending sound of a spoken word.' },
  sequencing: { type: 'sequencing', modalities: ['reading', 'thinking'], fits_stages: ['controlled', 'reflection'], fits_purposes: ['controlled', 'reflection'], min_cefr: 'A1', max_cefr: 'C1', hub_fit: { playground: 0.8, academy: 1, success: 0.9 }, load: 'medium', productive: false, description: 'Order story events / dialogue lines / steps into the correct sequence.' },
  evidence_hunt: { type: 'evidence_hunt', modalities: ['reading', 'thinking'], fits_stages: ['controlled', 'discovery'], fits_purposes: ['controlled', 'discovery'], min_cefr: 'A2', max_cefr: 'C1', hub_fit: { playground: 0.3, academy: 1, success: 0.9 }, load: 'high', productive: true, description: 'Find and quote textual evidence that supports a claim from the reading.' },
  dialogue_completion: { type: 'dialogue_completion', modalities: ['speaking', 'reading'], fits_stages: ['communicative' as any, 'production'], fits_purposes: ['communicative', 'production'], min_cefr: 'A1', max_cefr: 'C1', hub_fit: { playground: 0.7, academy: 1, success: 1 }, load: 'medium', productive: true, description: 'Complete missing turns in a contextual dialogue with the lesson characters.' },
  story_reconstruction: { type: 'story_reconstruction', modalities: ['reading', 'speaking'], fits_stages: ['reflection', 'production'], fits_purposes: ['reflection', 'production'], min_cefr: 'A1', max_cefr: 'C1', hub_fit: { playground: 0.6, academy: 1, success: 0.9 }, load: 'high', productive: true, description: 'Retell the story using target vocab + grammar with scaffolded cues.' },
  hotspot: { type: 'hotspot', modalities: ['reading', 'thinking'], fits_stages: ['input', 'discovery'], fits_purposes: ['input', 'discovery'], min_cefr: 'Pre-A1', max_cefr: 'C1', hub_fit: { playground: 1, academy: 0.9, success: 0.8 }, load: 'low', productive: false, description: 'Tap regions of an illustration to reveal labels, sounds, or micro-explanations.' },
  branching_choice: { type: 'branching_choice', modalities: ['reading', 'thinking', 'speaking'], fits_stages: ['communicative' as any, 'production'], fits_purposes: ['communicative', 'production'], min_cefr: 'A1', max_cefr: 'C1', hub_fit: { playground: 0.6, academy: 1, success: 1 }, load: 'high', productive: true, description: 'Choose-your-path scenario where each choice changes the story and recycles target language.' },
  interactive_story: { type: 'interactive_story', modalities: ['reading', 'listening', 'speaking'], fits_stages: ['input', 'discovery', 'communicative' as any], fits_purposes: ['input', 'discovery', 'communicative'], min_cefr: 'Pre-A1', max_cefr: 'C1', hub_fit: { playground: 1, academy: 0.9, success: 0.8 }, load: 'medium', productive: true, description: 'Cinematic story slide with embedded taps, mini-decisions, and speaking checkpoints.' },

  // ── Whole-set multi-item vocab matching board ──
  vocab_match_board: {
    type: 'vocab_match_board',
    modalities: ['listening', 'reading', 'thinking'],
    fits_stages: ['input', 'controlled', 'discovery'],
    fits_purposes: ['input', 'controlled', 'discovery'],
    min_cefr: 'Pre-A1', max_cefr: 'C1',
    hub_fit: { playground: 1, academy: 1, success: 0.9 },
    load: 'medium', productive: false,
    description: 'Whole vocabulary set on one board. Pair every word↔image, audio↔image, or audio↔word before the slide completes.',
  },

  // ── Unified Phonics System (Hear → See → Say → Do) ──
  phonics_card: {
    type: 'phonics_card', modalities: ['listening', 'reading', 'speaking', 'thinking'],
    fits_stages: ['input', 'discovery', 'controlled'], fits_purposes: ['input', 'discovery', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'A2',
    hub_fit: { playground: 1, academy: 0.85, success: 0.7 },
    load: 'low', productive: true,
    description: 'Hub-skinned phonics card: Hear (auto-play phoneme) → See (highlighted examples) → Say (record) → Do (one micro-interaction).',
  },
  phoneme_isolation: {
    type: 'phoneme_isolation', modalities: ['listening', 'thinking'],
    fits_stages: ['input', 'controlled'], fits_purposes: ['input', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'A1',
    hub_fit: { playground: 1, academy: 0.7, success: 0.6 },
    load: 'low', productive: false,
    description: 'Tap the picture whose name starts with the target phoneme.',
  },
  blending_animation: {
    type: 'blending_animation', modalities: ['listening', 'reading'],
    fits_stages: ['input', 'discovery', 'controlled'], fits_purposes: ['input', 'discovery', 'controlled'],
    min_cefr: 'Pre-A1', max_cefr: 'A1',
    hub_fit: { playground: 1, academy: 0.6, success: 0.5 },
    load: 'low', productive: false,
    description: 'Animated letter-by-letter blending of a CVC/digraph word, ending with full pronunciation.',
  },
  minimal_pair_tap: {
    type: 'minimal_pair_tap', modalities: ['listening', 'thinking'],
    fits_stages: ['controlled', 'discovery'], fits_purposes: ['controlled', 'discovery'],
    min_cefr: 'Pre-A1', max_cefr: 'B1',
    hub_fit: { playground: 0.9, academy: 1, success: 1 },
    load: 'low', productive: false,
    description: 'Hear one word from a minimal pair (ship/sheep); tap the word you heard.',
  },
  grapheme_hunt: {
    type: 'grapheme_hunt', modalities: ['reading', 'thinking'],
    fits_stages: ['controlled', 'communicative' as any], fits_purposes: ['controlled', 'communicative'],
    min_cefr: 'A1', max_cefr: 'B1',
    hub_fit: { playground: 0.9, academy: 1, success: 0.8 },
    load: 'medium', productive: false,
    description: 'Tap every occurrence of the target grapheme inside a short sentence.',
  },
  decoding_probe: {
    type: 'decoding_probe', modalities: ['reading', 'speaking'],
    fits_stages: ['controlled', 'production'], fits_purposes: ['controlled', 'production'],
    min_cefr: 'A1', max_cefr: 'B1',
    hub_fit: { playground: 1, academy: 0.9, success: 0.85 },
    load: 'medium', productive: true,
    description: 'Decode a mix of real words and pseudowords aloud — proves grapheme→phoneme transfer.',
  },
};


export const ALL_ACTIVITY_TYPES = Object.keys(ACTIVITY_CATALOG) as ActivityType[];
