// Example slide content for every ActivityType.
// Used by the Activity Catalog page (read-only documentation surface).
// These are illustrative payloads — not seeded into real lessons.

import type { ActivityType } from '../types';

export interface ActivityExample {
  title: string;
  prompt: string;
  payload: Record<string, any>;
}

export const ACTIVITY_EXAMPLES: Record<ActivityType, ActivityExample> = {
  warmup: { title: 'Café warm-up', prompt: 'What do you usually order?',
    payload: { question: 'What do you usually order at a café?', options: ['Coffee', 'Tea', 'Juice', 'Water'] } },
  poll: { title: 'Theme poll', prompt: 'Pick your weekend mood',
    payload: { question: 'Your ideal Saturday?', options: ['Hike', 'Movie', 'Brunch', 'Sleep'] } },
  opinion: { title: 'Open opinion', prompt: 'Why?',
    payload: { stem: 'Is working from home better than the office? Why or why not?' } },
  matching: { title: 'Word ↔ meaning', prompt: 'Match each word to its meaning',
    payload: { pairs: [['punctual', 'on time'], ['vague', 'not clear'], ['urgent', 'needs fast action']] } },
  drag_drop: { title: 'Sort the verbs', prompt: 'Drop each into the right tense',
    payload: { items: ['played', 'eat', 'will go', 'wrote'], buckets: ['Past', 'Present', 'Future'] } },
  fill_blank: { title: 'Cloze in context', prompt: 'Complete the sentence',
    payload: { sentence: 'I ___ to the gym every morning.', answers: ['go'] } },
  sentence_builder: { title: 'Build the sentence', prompt: 'Order the tokens',
    payload: { tokens: ['She', 'always', 'drinks', 'green tea', 'in the morning'] } },
  pronunciation: { title: 'Repeat the chunk', prompt: 'Say it like the model',
    payload: { target: "I'd like a coffee, please.", audio_url: '' } },
  reading: { title: 'Short scenario', prompt: 'Read and answer',
    payload: { passage: 'Maya runs a small bakery downtown. She opens at 7 a.m. and closes when the bread is gone.', q: 'What time does Maya open?' } },
  listening: { title: 'Listen for gist', prompt: 'What is the speaker doing?',
    payload: { audio_url: '', q: 'Where is this conversation happening?', options: ['Airport', 'Café', 'Office'] } },
  roleplay: { title: 'Ordering food', prompt: 'Play customer and waiter',
    payload: { roles: ['Customer', 'Waiter'], cues: ['Greet', 'Order', 'Pay'] } },
  debate: { title: 'Take a side', prompt: 'Defend your position for 60s',
    payload: { motion: 'Remote work is better than office work.' } },
  speaking_mission: { title: 'Real-world mission', prompt: 'Do this today',
    payload: { mission: 'Order a coffee in English and report back one new word you heard.' } },
  storytelling: { title: 'Continue the scene', prompt: 'Tell what happens next',
    payload: { seed: 'Maya opened the bakery door and saw...' } },
  collaborative: { title: 'Plan a trip together', prompt: 'Decide as a pair',
    payload: { task: 'Plan a 1-day trip for two using 5 target vocab words.' } },
  reflection: { title: 'Looking back', prompt: 'What stuck with you?',
    payload: { stem: 'Which phrase from today will you actually use this week?' } },
  retrieval: { title: 'Recall sprint', prompt: 'Write 5 target words from memory',
    payload: { instruction: 'No peeking — write five words you learned today.' } },
  review_challenge: { title: 'Mixed challenge', prompt: 'Use 3 words + past tense',
    payload: { instruction: 'Tell a 20-second story using three target words in the past tense.' } },

  trace_letter: { title: 'Trace "s"', prompt: 'Follow the path',
    payload: { letter: 's', stroke_path: 'M 30 20 C ... ', rainbow: true } },
  trace_word: { title: 'Trace "sun"', prompt: 'Say each sound as you trace',
    payload: { word: 'sun', sounds: ['s', 'u', 'n'] } },
  phoneme_tap: { title: 'Tap the sounds in "cat"', prompt: 'One tap per sound',
    payload: { word: 'cat', expected_taps: 3 } },
  blend_builder: { title: 'Make a word', prompt: 'Drag onset + rime',
    payload: { onset: 'c', rimes: ['at', 'ap', 'an'], target: 'cat' } },
  rhyme_match: { title: 'Find the rhymes', prompt: 'Match rhyming pairs',
    payload: { items: ['cat', 'hat', 'sun', 'fun', 'dog', 'log'] } },
  cvc_builder: { title: 'Build "pig"', prompt: 'Pick three letters',
    payload: { tiles: ['p', 'i', 'g', 'b', 'a', 'd'], target: 'pig' } },
  sound_hunt: { title: 'Hunt /s/', prompt: 'Tap every picture starting with /s/',
    payload: { target_phoneme: '/s/', items: ['sun', 'cat', 'snake', 'dog', 'sock'] } },
  decode_the_word: { title: 'Decode "ship"', prompt: 'Sound it out',
    payload: { word: 'ship', graphemes: ['sh', 'i', 'p'] } },

  listen_and_match: { title: 'Audio → image', prompt: 'Tap the picture you heard',
    payload: { audio_url: '', options: ['🍎', '🍌', '🍇'] } },
  audio_to_image_match: { title: 'Pure audio cue', prompt: 'Pick the right picture',
    payload: { audio_url: '', options_count: 4 } },
  sound_discrimination: { title: 'Same or different?', prompt: 'Tap SAME or DIFFERENT',
    payload: { pair: ['ship', 'sheep'], answer: 'different' } },
  echo_repetition: { title: 'Echo', prompt: 'Listen, then repeat',
    payload: { target: 'Nice to meet you.' } },
  listening_hunt: { title: 'Find every "discount"', prompt: 'Tap every clip with the target',
    payload: { target: 'discount', clips: 5 } },
  audio_sequence: { title: 'Order the clips', prompt: 'Drag into story order',
    payload: { clips: ['intro', 'problem', 'solution'] } },
  dictation_builder: { title: 'Reconstruct the sentence', prompt: 'Listen, then build',
    payload: { audio_url: '', answers: ['I', 'live', 'in', 'Madrid'] } },
  pronunciation_tap: { title: 'Tap the stress', prompt: 'Mark the stressed syllable',
    payload: { word: 'computer', stressed_index: 1 } },
  minimal_pairs: { title: 'ship / sheep', prompt: 'Which did you hear?',
    payload: { pair: ['ship', 'sheep'], audio_url: '' } },

  grammar_color_builder: { title: 'Color the parts', prompt: 'Color aux/base/ending',
    payload: { sentence: 'She is working from home.', roles: { aux: [4, 6], base: [7, 11], ending: [11, 14] } } },
  timeline_drag: { title: 'Past / Present / Future', prompt: 'Place each sentence',
    payload: { sentences: ['I ate breakfast.', 'I am eating.', 'I will eat.'] } },
  tense_transform: { title: 'Pos → Neg → Q', prompt: 'Transform the sentence',
    payload: { seed: 'She works late.' } },
  substitution_drill: { title: 'Swap the subject', prompt: 'Change one slot',
    payload: { frame: '___ goes to the gym every day.', slots: ['She', 'He', 'They', 'My friend'] } },
  rapid_fire_drill: { title: 'Rapid fire', prompt: '≤3s per response',
    payload: { cues: ['eat', 'sleep', 'work', 'go', 'have'], target: 'past simple' } },
  grammar_sort: { title: 'Countable / Uncountable', prompt: 'Sort the nouns',
    payload: { items: ['water', 'apples', 'rice', 'books'], buckets: ['countable', 'uncountable'] } },
  sentence_expansion: { title: 'Expand the core', prompt: 'Add who/when/where',
    payload: { core: 'I work.', adders: ['who with', 'when', 'where', 'why'] } },
  chunk_builder: { title: 'Assemble fluent chunks', prompt: 'Use 3 chunks',
    payload: { chunks: ['by the way', 'to be honest', 'as far as I know'] } },

  syllable_clap: { title: 'Clap "banana"', prompt: 'One clap per syllable',
    payload: { word: 'banana', expected_claps: 3 } },
  onset_rime_builder: { title: 'Onset + rime', prompt: 'Build the word',
    payload: { onset: 'c', rime: 'at' } },
  drag_the_letters: { title: 'Spell "dog"', prompt: 'Drag letters in order',
    payload: { letters: ['o', 'd', 'g'], target: 'dog' } },
  missing_sound: { title: 'Missing phoneme', prompt: 'What sound is missing?',
    payload: { heard: 'at', target: 'cat', missing: 'c' } },
  phonics_bingo: { title: 'Grapheme bingo', prompt: 'Mark the letter you hear',
    payload: { card: [['sh', 'ch', 'th'], ['ai', 'oa', 'ee']] } },
  tap_the_grapheme: { title: 'Tap the spelling', prompt: 'Tap the letters for /sh/',
    payload: { target_sound: '/sh/', options: ['sh', 'ch', 'th'] } },
  sound_sorting: { title: 'Sort by initial sound', prompt: 'Drop into buckets',
    payload: { items: ['sun', 'cat', 'snake', 'cup'], buckets: ['/s/', '/k/'] } },
  beginning_sound: { title: 'What starts "fish"?', prompt: 'Pick the first sound',
    payload: { word: 'fish', options: ['/f/', '/s/', '/sh/'] } },
  ending_sound: { title: 'What ends "dog"?', prompt: 'Pick the last sound',
    payload: { word: 'dog', options: ['/g/', '/k/', '/d/'] } },
  sequencing: { title: 'Order the events', prompt: 'Drag into order',
    payload: { items: ['Wake up', 'Brush teeth', 'Have breakfast', 'Go to work'] } },
  evidence_hunt: { title: 'Find the proof', prompt: 'Quote the line',
    payload: { passage: '...', claim: 'Maya opens early.' } },
  dialogue_completion: { title: 'Fill in the dialogue', prompt: 'Complete the missing turns',
    payload: { lines: [{ who: 'Waiter', text: 'What can I get you?' }, { who: 'You', text: '___' }] } },
  story_reconstruction: { title: 'Retell with cues', prompt: 'Use the target words',
    payload: { cues: ['Maya', 'bakery', 'morning', 'customer'] } },
  hotspot: { title: 'Tap the kitchen scene', prompt: 'Reveal labels',
    payload: { image: 'kitchen', hotspots: ['fridge', 'stove', 'sink'] } },
  branching_choice: { title: 'Choose your path', prompt: 'Pick what to say',
    payload: { choices: ['Be polite', 'Be direct'] } },
  interactive_story: { title: 'Tap-along story', prompt: 'Tap the highlighted items',
    payload: { scenes: 3, taps_per_scene: 2 } },

  vocab_match_board: { title: 'Whole-set match', prompt: 'Pair every word with its image',
    payload: { mode: 'word_image', pairs: [['apple', 'img/apple'], ['banana', 'img/banana'], ['grape', 'img/grape']] } },

  phonics_card: { title: 'Hear → See → Say → Do', prompt: 'Sound: /sh/',
    payload: { grapheme: 'sh', phoneme: '/ʃ/', examples: [{ word: 'ship', highlight: [0, 2] }, { word: 'fish', highlight: [2, 4] }] } },
  phoneme_isolation: { title: 'Starts with /s/', prompt: 'Tap pictures starting with /s/',
    payload: { target_phoneme: '/s/', items: [{ word: 'sun', starts_with_target: true }, { word: 'dog', starts_with_target: false }] } },
  blending_animation: { title: 'Blend c-a-t', prompt: 'Watch and say "cat"',
    payload: { letters: ['c', 'a', 't'], word: 'cat' } },
  minimal_pair_tap: { title: 'ship or sheep?', prompt: 'Tap what you heard',
    payload: { pair: ['ship', 'sheep'], correct: 'sheep' } },
  grapheme_hunt: { title: 'Hunt "sh"', prompt: 'Tap every "sh" in the sentence',
    payload: { sentence: 'She showed me her shiny shoes.', target_grapheme: 'sh' } },
  decoding_probe: { title: 'Real or pseudo?', prompt: 'Decode each word aloud',
    payload: { items: [{ word: 'ship', is_pseudoword: false }, { word: 'shup', is_pseudoword: true }] } },
};
