export type StoryPage = {
  id: string;
  image: string;
  /** Full sentences for the pre-read (assigned before the lesson). */
  text: string[];
  /**
   * Same sentences with a single blank marked as "___" per sentence.
   * Each blank has an answer + 2 distractors (all from Lessons 1–3 vocab).
   */
  gaps: { sentence: string; answer: string; options: string[] }[];
};

/**
 * Storybook content is supplied by the AI unit (Storybook Brain).
 * Bundled example story removed from the creator hub — structure preserved.
 */
export const STORY_TITLE = "";
export const STORY_PAGES: StoryPage[] = [];

export type Level = "preA1" | "A1" | "A2";

export type ComprehensionQ = {
  q: string;
  options: string[];
  answer: string;
};

/**
 * Comprehension questions are generated by the AI from the storybook.
 * Bundled examples removed — structure preserved per CEFR tier.
 */
export const COMPREHENSION: Record<Level, ComprehensionQ[]> = {
  preA1: [],
  A1: [],
  A2: [],
};

/* -------------------------------------------------------------------------- */
/*  Post-reading: Look & Say (A2 / B1 / B2)                                   */
/* -------------------------------------------------------------------------- */
export type LookSayLevel = "A2" | "B1" | "B2";

export type LookSaySlot = {
  label: string;
  prompt: string;
  frame: string;
  model: string;
};

export type LookSayCard = {
  pageId: StoryPage["id"];
  title: string;
  slots: LookSaySlot[];
};

/**
 * Look & Say organizer cards are generated by the AI from the storybook.
 * Bundled examples removed — structure preserved per CEFR tier.
 */
export const LOOK_AND_SAY: Record<LookSayLevel, LookSayCard[]> = {
  A2: [],
  B1: [],
  B2: [],
};
