import type { World } from './types';

// Source of truth for A1 Playground worlds.
// Mirrors the seeded curriculum_worlds rows. Keep slugs in sync with DB seed.
export const A1_PLAYGROUND_WORLDS: World[] = [
  {
    slug: 'welcome-town', name: 'Welcome Town', hub: 'playground', cefrBand: 'A1',
    visualStyle: { setting: 'cheerful town', props: ['balloons', 'schoolhouse', 'streets'] },
    emotionalTone: 'safe-welcoming', gameplayIdentity: 'greeting-quests',
    palette: ['#FFD166', '#FFB703', '#FB8500', '#8ECAE6'],
    mascots: ['Pip the Penguin', 'Mayor Marigold'], musicMood: 'cheerful-marching',
    suggestedActivityTypes: ['multiple_choice', 'match_pairs', 'drag_drop', 'speaking_repeat'],
    topicAffinity: ['greetings', 'introductions', 'classroom', 'colors', 'commands'],
    displayOrder: 1,
  },
  {
    slug: 'jungle-adventure', name: 'Jungle Adventure', hub: 'playground', cefrBand: 'A1',
    visualStyle: { setting: 'jungle', props: ['waterfalls', 'vines', 'tropical-canopy'] },
    emotionalTone: 'adventurous-energetic', gameplayIdentity: 'animal-rescue',
    palette: ['#2A9D8F', '#E9C46A', '#F4A261', '#264653'],
    mascots: ['Rumi the Tiger Cub', 'Sky the Parrot'], musicMood: 'tribal-drums-upbeat',
    suggestedActivityTypes: ['drag_drop', 'sound_discrimination', 'match_pairs', 'speaking_describe'],
    topicAffinity: ['animals', 'actions', 'movement', 'simple_present'],
    displayOrder: 2,
  },
  {
    slug: 'space-mission', name: 'Space Mission', hub: 'playground', cefrBand: 'A1',
    visualStyle: { setting: 'space station', props: ['planets', 'rockets', 'control-panels'] },
    emotionalTone: 'curious-futuristic', gameplayIdentity: 'rocket-navigation',
    palette: ['#3D348B', '#7678ED', '#F7B801', '#F18701'],
    mascots: ['Captain Nova', 'Beep the Robot'], musicMood: 'synthwave-curious',
    suggestedActivityTypes: ['drag_drop', 'dictation_builder', 'listen_and_match', 'speaking_command'],
    topicAffinity: ['numbers', 'directions', 'counting', 'locations', 'commands'],
    displayOrder: 3,
  },
  {
    slug: 'food-festival', name: 'Food Festival', hub: 'playground', cefrBand: 'A1',
    visualStyle: { setting: 'food market', props: ['stalls', 'lanterns', 'candy-bowls'] },
    emotionalTone: 'social-playful', gameplayIdentity: 'restaurant-roleplay',
    palette: ['#E63946', '#F1FAEE', '#A8DADC', '#457B9D'],
    mascots: ['Chef Cilla', 'Pico the Mouse'], musicMood: 'mariachi-light',
    suggestedActivityTypes: ['drag_drop', 'match_pairs', 'speaking_dialogue', 'multiple_choice'],
    topicAffinity: ['food', 'likes_dislikes', 'countables', 'ordering'],
    displayOrder: 4,
  },
  {
    slug: 'monster-academy', name: 'Monster Academy', hub: 'playground', cefrBand: 'A1',
    visualStyle: { setting: 'magical classroom', props: ['floating-books', 'potions', 'starry-ceiling'] },
    emotionalTone: 'funny-magical', gameplayIdentity: 'monster-customization',
    palette: ['#7209B7', '#3A0CA3', '#F72585', '#4CC9F0'],
    mascots: ['Professor Glob', 'Bibi the Tiny Monster'], musicMood: 'whimsical-organ',
    suggestedActivityTypes: ['visual_grammar', 'match_pairs', 'speaking_describe', 'drag_drop'],
    topicAffinity: ['emotions', 'appearance', 'personality', 'describing_people'],
    displayOrder: 5,
  },
  {
    slug: 'ocean-explorers', name: 'Ocean Explorers', hub: 'playground', cefrBand: 'A1',
    visualStyle: { setting: 'underwater reef', props: ['submarine', 'coral', 'bubbles'] },
    emotionalTone: 'calm-exploratory', gameplayIdentity: 'treasure-hunt',
    palette: ['#0077B6', '#00B4D8', '#90E0EF', '#CAF0F8'],
    mascots: ['Coral the Mermaid', 'Bub the Octopus'], musicMood: 'ambient-underwater',
    suggestedActivityTypes: ['drag_drop', 'sound_discrimination', 'speaking_question', 'match_pairs'],
    topicAffinity: ['sea_animals', 'actions', 'questions', 'habitats'],
    displayOrder: 6,
  },
  {
    slug: 'superhero-city', name: 'Superhero City', hub: 'playground', cefrBand: 'A1',
    visualStyle: { setting: 'comic-book city', props: ['skyscrapers', 'gadgets', 'action-lines'] },
    emotionalTone: 'empowering-exciting', gameplayIdentity: 'rescue-mission',
    palette: ['#D62828', '#003049', '#F77F00', '#FCBF49'],
    mascots: ['Captain Spark', 'Zippy the Sidekick'], musicMood: 'cinematic-power',
    suggestedActivityTypes: ['speaking_dialogue', 'multiple_choice', 'drag_drop', 'listen_and_match'],
    topicAffinity: ['abilities', 'can_cant', 'helping', 'daily_actions'],
    displayOrder: 7,
  },
  {
    slug: 'dinosaur-island', name: 'Dinosaur Island', hub: 'playground', cefrBand: 'A1',
    visualStyle: { setting: 'prehistoric jungle', props: ['volcano', 'fossils', 'ferns'] },
    emotionalTone: 'epic-adventurous', gameplayIdentity: 'fossil-collection',
    palette: ['#386641', '#6A994E', '#A7C957', '#F2E8CF'],
    mascots: ['Rexi the T-Rex', 'Tilly the Triceratops'], musicMood: 'epic-tribal',
    suggestedActivityTypes: ['drag_drop', 'match_pairs', 'visual_grammar', 'speaking_describe'],
    topicAffinity: ['sizes', 'comparisons', 'adjectives', 'nature'],
    displayOrder: 8,
  },
  {
    slug: 'magic-castle', name: 'Magic Castle', hub: 'playground', cefrBand: 'A1',
    visualStyle: { setting: 'enchanted castle', props: ['torches', 'tapestries', 'spiral-stairs'] },
    emotionalTone: 'mysterious-magical', gameplayIdentity: 'hidden-object-quest',
    palette: ['#22223B', '#4A4E69', '#9A8C98', '#C9ADA7'],
    mascots: ['Wizard Wim', 'Cat-cat the Familiar'], musicMood: 'celesta-mystery',
    suggestedActivityTypes: ['drag_drop', 'match_pairs', 'visual_grammar', 'speaking_describe'],
    topicAffinity: ['household', 'rooms', 'prepositions', 'object_descriptions'],
    displayOrder: 9,
  },
  {
    slug: 'future-tech-lab', name: 'Future Tech Lab', hub: 'playground', cefrBand: 'A1',
    visualStyle: { setting: 'holographic lab', props: ['screens', 'robots', 'blueprints'] },
    emotionalTone: 'innovative-intelligent', gameplayIdentity: 'invention-challenge',
    palette: ['#00F5D4', '#00BBF9', '#9B5DE5', '#F15BB5'],
    mascots: ['Dr. Volt', 'Nano the Bot'], musicMood: 'electronic-bright',
    suggestedActivityTypes: ['dictation_builder', 'multiple_choice', 'drag_drop', 'speaking_instruct'],
    topicAffinity: ['technology', 'instructions', 'routines', 'problem_solving'],
    displayOrder: 10,
  },
];
