import React, { createContext, useState, useContext, ReactNode } from "react";

// Add your language translations here
const languages = {
  english: {
    welcome: "Welcome",
    learningProgress: "Learning Progress",
    vocabulary: "Vocabulary",
    grammar: "Grammar",
    listening: "Listening",
    speakingSkill: "Speaking",
    reading: "Reading",
    yourRewards: "Your Rewards",
    upcomingClasses: "Upcoming Classes",
    viewAll: "View All",
    funActivities: "Fun Activities",
    start: "Start",
    points: "points",
    dueDate: "Due Date",
    completed: "Completed",
    typeAnswer: "Type your answer here...",
    attachFile: "Attach File",
    fileAttached: "File Attached",
    fileAttachedDesc: "Your file has been attached successfully",
    submissionRequired: "Submission Required",
    provideAnswer: "Please provide an answer or attach a file",
    homeworkSubmitted: "Homework Submitted",
    earnedPoints: "You earned {} points!",
    submitting: "Submitting...",
    submitHomework: "Submit Homework",
    vocabularyPractice: "Vocabulary Practice",
    question: "Question",
    of: "of",
    selectTranslation: "Select the correct translation",
    nextWord: "Next Word",
    finish: "Finish",
    practiceCompleted: "Practice Completed",
    youScored: "You scored",
    practiceAgain: "Practice Again",

    // Assessment system
    question: "Question",
    of: "of",
    submit: "Submit",
    selectOption: "Select an Option",
    pleaseSelectOption: "Please select an option before submitting",
    correct: "Correct!",
    incorrect: "Incorrect",
    correctFeedback: "Great job! You've got the right answer.",
    incorrectFeedback: "Not quite. Try to remember for next time.",
    quizCompleted: "Quiz Completed",
    yourScore: "Your Score",
    retakeQuiz: "Retake Quiz",
    nextQuestion: "Next Question",
    finish: "Finish",
    animalSoundsQuiz: "Animal Sounds Quiz",
    matchAnimalsWithSounds: "Match these animals with their sounds",
    
    // Interactive learning
    showVocabulary: "Show Vocabulary",
    hideVocabulary: "Hide Vocabulary", 
    newVocabulary: "New Vocabulary",
    finishStory: "Finish Story",
    interactiveStories: "Interactive Stories",
    
    // Learning path
    learningPath: "Learning Path",
    complete: "complete",
    activities: "activities",
    min: "min",
    
    // Teacher tools
    lessonPlanCreator: "Lesson Plan Creator",
    createLessonPlan: "Create Lesson Plan",
    editLessonPlan: "Edit Lesson Plan",
    lessonTitle: "Lesson Title",
    enterLessonTitle: "Enter lesson title",
    grade: "Grade",
    enterGrade: "Enter grade level",
    subject: "Subject",
    enterSubject: "Enter subject",
    objectives: "Objectives",
    addObjective: "Add Objective",
    objective: "Objective",
    activities: "Activities",
    addActivity: "Add Activity",
    activity: "Activity",
    title: "Title",
    enterActivityTitle: "Enter activity title",
    description: "Description",
    enterActivityDescription: "Enter activity description",
    duration: "Duration",
    materials: "Materials",
    addMaterial: "Add Material",
    material: "Material",
    additionalNotes: "Additional Notes",
    enterAdditionalNotes: "Enter any additional notes",
    validationError: "Validation Error",
    lessonTitleRequired: "Lesson title is required",
    objectivesRequired: "At least one objective is required",
    saveLessonPlan: "Save Lesson Plan",
    lessonPlanSaved: "Lesson Plan Saved",
    lessonPlanSavedDesc: "Your lesson plan has been saved successfully",
    
    // Classroom
    lessonContent: "Lesson",
    students: "Students",
    studentsInClass: "Students in Class",
    searchStudents: "Search students",
    noStudentsFound: "No students found",
    handRaised: "Hand Raised",
    handLowered: "Hand Lowered",
    teacherNotified: "Your teacher has been notified",
    handLoweredDesc: "Your hand has been lowered",
    microphoneEnabled: "Microphone Enabled",
    microphoneDisabled: "Microphone Disabled",
    youCanNowSpeak: "You can now speak to the class",
    youAreMuted: "You are now muted",
    cameraEnabled: "Camera Enabled",
    cameraDisabled: "Camera Disabled",
    youAreNowVisible: "You are now visible to the class",
    youAreNowHidden: "Your camera is now turned off",
    clickToPlayVideo: "Click to play the lesson video",
    play: "Play",
    resources: "Resources",
    chat: "Chat",
    participants: "Participants",
    teacher: "Teacher",
    host: "Host",
    you: "You",
    speakingNow: "Speaking",
    online: "Online",
    lastActive: "Last active",
    message: "Message",
    spotlight: "Spotlight",
    leaveClass: "Leave Class",
    
    // Resource Library (Added missing translations)
    resourceLibrary: "Resource Library",
    searchResources: "Search resources",
    type: "Type",
    video: "Video",
    audio: "Audio",
    interactive: "Interactive",
    level: "Level",
    beginner: "Beginner",
    intermediate: "Intermediate",
    advanced: "Advanced",
    download: "Download",
    viewResource: "View Resource",
    noResourcesFound: "No resources found",
    all: "All",
    
    // Student Header (Added missing translations)
    notifications: "Notifications",
    profile: "Profile",
    language: "Language",

    // Achievements/Gamification
    achievements: "Achievements",
    learning: "Learning",
    social: "Social",
    streak: "Streak",
    mastery: "Mastery",
    noAchievementsFound: "No achievements found in this category",

    // Add missing translations for StudyCalendar
    studyCalendar: "Study Calendar",
    class: "Class",
    homework: "Homework",
    test: "Test",
    practice: "Practice",
    selectDate: "Select date",
    noEventsForDay: "No events scheduled for this day",
    
    // Add missing translations for Progress
    yourProgress: "Your Progress",
    thisWeekActivities: "This week's activities",
    classesAttended: "Classes attended",
    pointsEarned: "Points earned",
    speaking: "Speaking",
  },

  spanish: {
    welcome: "Bienvenido",
    learningProgress: "Progreso de Aprendizaje",
    vocabulary: "Vocabulario",
    grammar: "Gramática",
    listening: "Comprensión Auditiva",
    speakingSkill: "Expresión Oral",
    reading: "Lectura",
    yourRewards: "Tus Recompensas",
    upcomingClasses: "Próximas Clases",
    viewAll: "Ver Todo",
    funActivities: "Actividades Divertidas",
    start: "Comenzar",
    points: "puntos",
    dueDate: "Fecha de Entrega",
    completed: "Completado",
    typeAnswer: "Escribe tu respuesta aquí...",
    attachFile: "Adjuntar Archivo",
    fileAttached: "Archivo Adjuntado",
    fileAttachedDesc: "Tu archivo ha sido adjuntado exitosamente",
    submissionRequired: "Entrega Requerida",
    provideAnswer: "Por favor proporciona una respuesta o adjunta un archivo",
    homeworkSubmitted: "Tarea Enviada",
    earnedPoints: "¡Has ganado {} puntos!",
    submitting: "Enviando...",
    submitHomework: "Enviar Tarea",
    vocabularyPractice: "Práctica de Vocabulario",
    question: "Pregunta",
    of: "de",
    selectTranslation: "Selecciona la traducción correcta",
    nextWord: "Siguiente Palabra",
    finish: "Terminar",
    practiceCompleted: "Práctica Completada",
    youScored: "Tu puntuación",
    practiceAgain: "Practicar de Nuevo",

    // Assessment system
    question: "Pregunta",
    of: "de",
    submit: "Enviar",
    selectOption: "Seleccionar una Opción",
    pleaseSelectOption: "Por favor selecciona una opción antes de enviar",
    correct: "¡Correcto!",
    incorrect: "Incorrecto",
    correctFeedback: "¡Buen trabajo! Has elegido la respuesta correcta.",
    incorrectFeedback: "No exactamente. Intenta recordar para la próxima.",
    quizCompleted: "Cuestionario Completado",
    yourScore: "Tu Puntaje",
    retakeQuiz: "Volver a Intentar",
    nextQuestion: "Siguiente Pregunta",
    finish: "Terminar",
    animalSoundsQuiz: "Cuestionario de Sonidos de Animales",
    matchAnimalsWithSounds: "Relaciona estos animales con sus sonidos",
    
    // Interactive learning
    showVocabulary: "Mostrar Vocabulario",
    hideVocabulary: "Ocultar Vocabulario", 
    newVocabulary: "Nuevo Vocabulario",
    finishStory: "Terminar Historia",
    interactiveStories: "Historias Interactivas",
    
    // Learning path
    learningPath: "Ruta de Aprendizaje",
    complete: "completo",
    activities: "actividades",
    min: "min",
    
    // Teacher tools
    lessonPlanCreator: "Creador de Plan de Lección",
    createLessonPlan: "Crear Plan de Lección",
    editLessonPlan: "Editar Plan de Lección",
    lessonTitle: "Título de la Lección",
    enterLessonTitle: "Ingresa el título de la lección",
    grade: "Grado",
    enterGrade: "Ingresa el nivel de grado",
    subject: "Asignatura",
    enterSubject: "Ingresa la asignatura",
    objectives: "Objetivos",
    addObjective: "Añadir Objetivo",
    objective: "Objetivo",
    activities: "Actividades",
    addActivity: "Añadir Actividad",
    activity: "Actividad",
    title: "Título",
    enterActivityTitle: "Ingresa el título de la actividad",
    description: "Descripción",
    enterActivityDescription: "Ingresa la descripción de la actividad",
    duration: "Duración",
    materials: "Materiales",
    addMaterial: "Añadir Material",
    material: "Material",
    additionalNotes: "Notas Adicionales",
    enterAdditionalNotes: "Ingresa cualquier nota adicional",
    validationError: "Error de Validación",
    lessonTitleRequired: "El título de la lección es obligatorio",
    objectivesRequired: "Se requiere al menos un objetivo",
    saveLessonPlan: "Guardar Plan de Lección",
    lessonPlanSaved: "Plan de Lección Guardado",
    lessonPlanSavedDesc: "Tu plan de lección ha sido guardado exitosamente",
    
    // Classroom
    lessonContent: "Lección",
    students: "Estudiantes",
    studentsInClass: "Estudiantes en Clase",
    searchStudents: "Buscar estudiantes",
    noStudentsFound: "No se encontraron estudiantes",
    handRaised: "Mano Levantada",
    handLowered: "Mano Bajada",
    teacherNotified: "Tu profesor ha sido notificado",
    handLoweredDesc: "Tu mano ha sido bajada",
    microphoneEnabled: "Micrófono Habilitado",
    microphoneDisabled: "Micrófono Desactivado",
    youCanNowSpeak: "Ahora puedes hablar con la clase",
    youAreMuted: "Ahora estás silenciado",
    cameraEnabled: "Cámara Habilitada",
    cameraDisabled: "Cámara Desactivada",
    youAreNowVisible: "Ahora eres visible para la clase",
    youAreNowHidden: "Tu cámara está apagada",
    clickToPlayVideo: "Haz clic para reproducir el video de la lección",
    play: "Reproducir",
    resources: "Recursos",
    chat: "Chat",
    participants: "Participantes",
    teacher: "Profesor",
    host: "Anfitrión",
    you: "Tú",
    speakingNow: "Hablando",
    online: "En línea",
    lastActive: "Última actividad",
    message: "Mensaje",
    spotlight: "Destacar",
    leaveClass: "Salir de Clase",

    // Resource Library (Added missing translations)
    resourceLibrary: "Biblioteca de Recursos",
    searchResources: "Buscar recursos",
    type: "Tipo",
    video: "Video",
    audio: "Audio",
    interactive: "Interactivo",
    level: "Nivel",
    beginner: "Principiante",
    intermediate: "Intermedio",
    advanced: "Avanzado",
    download: "Descargar",
    viewResource: "Ver Recurso",
    noResourcesFound: "No se encontraron recursos",
    all: "Todos",
    
    // Student Header (Added missing translations)
    notifications: "Notificaciones",
    profile: "Perfil",
    language: "Idioma",

    // Achievements/Gamification
    achievements: "Logros",
    all: "Todos",
    learning: "Aprendizaje",
    social: "Social",
    streak: "Racha",
    mastery: "Maestría",
    noAchievementsFound: "No se encontraron logros en esta categoría",

    // Add missing translations for StudyCalendar
    studyCalendar: "Calendario de Estudio",
    class: "Clase",
    homework: "Tarea",
    test: "Examen",
    practice: "Práctica",
    selectDate: "Seleccionar fecha",
    noEventsForDay: "No hay eventos programados para este día",
    
    // Add missing translations for Progress
    yourProgress: "Tu Progreso",
    thisWeekActivities: "Actividades de esta semana",
    classesAttended: "Clases asistidas",
    pointsEarned: "Puntos ganados",
    speaking: "Hablar",
  },
  
  // Add Arabic language support
  arabic: {
    welcome: "مرحبًا",
    learningProgress: "تقدم التعلم",
    vocabulary: "المفردات",
    grammar: "القواعد",
    listening: "الاستماع",
    speakingSkill: "المحادثة",
    reading: "القراءة",
    yourRewards: "مكافآتك",
    upcomingClasses: "الصفوف القادمة",
    viewAll: "عرض الكل",
    funActivities: "أنشطة ممتعة",
    start: "ابدأ",
    points: "نقاط",
    dueDate: "تاريخ الاستحقاق",
    completed: "مكتمل",
    typeAnswer: "اكتب إجابتك هنا...",
    attachFile: "إرفاق ملف",
    fileAttached: "تم إرفاق الملف",
    fileAttachedDesc: "تم إرفاق ملفك بنجاح",
    submissionRequired: "التقديم مطلوب",
    provideAnswer: "الرجاء تقديم إجابة أو إرفاق ملف",
    homeworkSubmitted: "تم تقديم الواجب المنزلي",
    earnedPoints: "لقد ربحت {} نقطة!",
    submitting: "جاري التقديم...",
    submitHomework: "تقديم الواجب المنزلي",
    vocabularyPractice: "تمرين المفردات",
    question: "سؤال",
    of: "من",
    selectTranslation: "اختر الترجمة الصحيحة",
    nextWord: "الكلمة التالية",
    finish: "إنهاء",
    practiceCompleted: "اكتمل التمرين",
    youScored: "نتيجتك",
    practiceAgain: "تمرين مرة أخرى",
    
    // Assessment system
    submit: "تقديم",
    selectOption: "اختر خيارًا",
    pleaseSelectOption: "الرجاء اختيار خيار قبل التقديم",
    correct: "صحيح!",
    incorrect: "غير صحيح",
    correctFeedback: "عمل رائع! لقد اخترت الإجابة الصحيحة.",
    incorrectFeedback: "ليس تمامًا. حاول أن تتذكر في المرة القادمة.",
    quizCompleted: "اكتمل الاختبار",
    yourScore: "نتيجتك",
    retakeQuiz: "إعادة الاختبار",
    nextQuestion: "السؤال التالي",
    animalSoundsQuiz: "اختبار أصوات الحيوانات",
    matchAnimalsWithSounds: "طابق هذه الحيوانات مع أصواتها",
    
    // Interactive learning
    showVocabulary: "إظهار المفردات",
    hideVocabulary: "إخفاء المفردات",
    newVocabulary: "مفردات جديدة",
    finishStory: "إنهاء القصة",
    interactiveStories: "قصص تفاعلية",
    
    // Learning path
    learningPath: "مسار التعلم",
    complete: "مكتمل",
    activities: "أنشطة",
    min: "دقيقة",
    
    // Teacher tools
    lessonPlanCreator: "منشئ خطة الدرس",
    createLessonPlan: "إنشاء خطة درس",
    editLessonPlan: "تعديل خطة الدرس",
    lessonTitle: "عنوان الدرس",
    enterLessonTitle: "أدخل عنوان الدرس",
    grade: "الصف",
    enterGrade: "أدخل مستوى الصف",
    subject: "المادة",
    enterSubject: "أدخل المادة",
    objectives: "الأهداف",
    addObjective: "إضافة هدف",
    objective: "هدف",
    addActivity: "إضافة نشاط",
    activity: "نشاط",
    title: "العنوان",
    enterActivityTitle: "أدخل عنوان النشاط",
    description: "الوصف",
    enterActivityDescription: "أدخل وصف النشاط",
    duration: "المدة",
    materials: "المواد",
    addMaterial: "إضافة مادة",
    material: "مادة",
    additionalNotes: "ملاحظات إضافية",
    enterAdditionalNotes: "أدخل أي ملاحظات إضافية",
    validationError: "خطأ في التحقق",
    lessonTitleRequired: "عنوان الدرس مطلوب",
    objectivesRequired: "مطلوب هدف واحد على الأقل",
    saveLessonPlan: "حفظ خطة الدرس",
    lessonPlanSaved: "تم حفظ خطة الدرس",
    lessonPlanSavedDesc: "تم حفظ خطة درسك بنجاح",
    
    // Classroom
    lessonContent: "الدرس",
    students: "الطلاب",
    studentsInClass: "الطلاب في الصف",
    searchStudents: "بحث عن طلاب",
    noStudentsFound: "لم يتم العثور على طلاب",
    handRaised: "تم رفع اليد",
    handLowered: "تم خفض اليد",
    teacherNotified: "تم إخطار المعلم",
    handLoweredDesc: "تم خفض يدك",
    microphoneEnabled: "تم تمكين الميكروفون",
    microphoneDisabled: "تم تعطيل الميكروفون",
    youCanNowSpeak: "يمكنك الآن التحدث إلى الصف",
    youAreMuted: "أنت الآن صامت",
    cameraEnabled: "تم تمكين الكاميرا",
    cameraDisabled: "تم تعطيل الكاميرا",
    youAreNowVisible: "أنت الآن مرئي للصف",
    youAreNowHidden: "تم إيقاف تشغيل الكاميرا الخاصة بك",
    clickToPlayVideo: "انقر لتشغيل فيديو الدرس",
    play: "تشغيل",
    resources: "الموارد",
    chat: "الدردشة",
    participants: "المشاركون",
    teacher: "المعلم",
    host: "المضيف",
    you: "أنت",
    speakingNow: "يتحدث",
    online: "متصل",
    lastActive: "آخر نشاط",
    message: "رسالة",
    spotlight: "تسليط الضوء",
    leaveClass: "مغادرة الصف",

    // Resource Library
    resourceLibrary: "مكتبة الموارد",
    searchResources: "بحث عن موارد",
    type: "النوع",
    video: "فيديو",
    audio: "صوت",
    interactive: "تفاعلي",
    level: "المستوى",
    beginner: "مبتدئ",
    intermediate: "متوسط",
    advanced: "متقدم",
    download: "تنزيل",
    viewResource: "عرض المورد",
    noResourcesFound: "لم يتم العثور على موارد",
    all: "الكل",
    
    // Student Header
    notifications: "الإشعارات",
    profile: "الملف الشخصي",
    language: "اللغة",
    
    // Achievements/Gamification
    achievements: "الإنجازات",
    learning: "التعلم",
    social: "اجتماعي",
    streak: "تتابع",
    mastery: "إتقان",
    noAchievementsFound: "لم يتم العثور على إنجازات في هذه الفئة",

    // Add missing translations for StudyCalendar
    studyCalendar: "تقويم الدراسة",
    class: "فصل",
    homework: "واجب منزلي",
    test: "اختبار",
    practice: "تمرين",
    selectDate: "اختر التاريخ",
    noEventsForDay: "لا توجد أحداث مجدولة لهذا اليوم",
    
    // Add missing translations for Progress
    yourProgress: "تقدمك",
    thisWeekActivities: "أنشطة هذا الأسبوع",
    classesAttended: "الصفوف التي حضرتها",
    pointsEarned: "النقاط المكتسبة",
    speaking: "التحدث",
  },
  
  // Add French language support
  french: {
    welcome: "Bienvenue",
    learningProgress: "Progrès d'apprentissage",
    vocabulary: "Vocabulaire",
    grammar: "Grammaire",
    listening: "Compréhension orale",
    speakingSkill: "Expression orale",
    reading: "Lecture",
    yourRewards: "Vos récompenses",
    upcomingClasses: "Cours à venir",
    viewAll: "Voir tout",
    funActivities: "Activités ludiques",
    start: "Commencer",
    points: "points",
    dueDate: "Date d'échéance",
    completed: "Terminé",
    typeAnswer: "Tapez votre réponse ici...",
    attachFile: "Joindre un fichier",
    fileAttached: "Fichier joint",
    fileAttachedDesc: "Votre fichier a été joint avec succès",
    submissionRequired: "Soumission requise",
    provideAnswer: "Veuillez fournir une réponse ou joindre un fichier",
    homeworkSubmitted: "Devoir soumis",
    earnedPoints: "Vous avez gagné {} points !",
    submitting: "Envoi en cours...",
    submitHomework: "Soumettre le devoir",
    vocabularyPractice: "Pratique du vocabulaire",
    question: "Question",
    of: "de",
    selectTranslation: "Sélectionnez la traduction correcte",
    nextWord: "Mot suivant",
    finish: "Terminer",
    practiceCompleted: "Pratique terminée",
    youScored: "Votre score",
    practiceAgain: "Pratiquer à nouveau",
    
    // Assessment system
    submit: "Soumettre",
    selectOption: "Sélectionner une option",
    pleaseSelectOption: "Veuillez sélectionner une option avant de soumettre",
    correct: "Correct !",
    incorrect: "Incorrect",
    correctFeedback: "Bon travail ! Vous avez la bonne réponse.",
    incorrectFeedback: "Pas tout à fait. Essayez de vous en souvenir pour la prochaine fois.",
    quizCompleted: "Quiz terminé",
    yourScore: "Votre score",
    retakeQuiz: "Refaire le quiz",
    nextQuestion: "Question suivante",
    animalSoundsQuiz: "Quiz sur les sons des animaux",
    matchAnimalsWithSounds: "Associez ces animaux à leurs sons",
    
    // Interactive learning
    showVocabulary: "Afficher le vocabulaire",
    hideVocabulary: "Masquer le vocabulaire",
    newVocabulary: "Nouveau vocabulaire",
    finishStory: "Terminer l'histoire",
    interactiveStories: "Histoires interactives",
    
    // Learning path
    learningPath: "Parcours d'apprentissage",
    complete: "complet",
    activities: "activités",
    min: "min",
    
    // Teacher tools
    lessonPlanCreator: "Créateur de plan de cours",
    createLessonPlan: "Créer un plan de cours",
    editLessonPlan: "Modifier le plan de cours",
    lessonTitle: "Titre de la leçon",
    enterLessonTitle: "Entrez le titre de la leçon",
    grade: "Niveau",
    enterGrade: "Entrez le niveau scolaire",
    subject: "Matière",
    enterSubject: "Entrez la matière",
    objectives: "Objectifs",
    addObjective: "Ajouter un objectif",
    objective: "Objectif",
    addActivity: "Ajouter une activité",
    activity: "Activité",
    title: "Titre",
    enterActivityTitle: "Entrez le titre de l'activité",
    description: "Description",
    enterActivityDescription: "Entrez la description de l'activité",
    duration: "Durée",
    materials: "Matériels",
    addMaterial: "Ajouter un matériel",
    material: "Matériel",
    additionalNotes: "Notes supplémentaires",
    enterAdditionalNotes: "Entrez des notes supplémentaires",
    validationError: "Erreur de validation",
    lessonTitleRequired: "Le titre de la leçon est requis",
    objectivesRequired: "Au moins un objectif est requis",
    saveLessonPlan: "Enregistrer le plan de cours",
    lessonPlanSaved: "Plan de cours enregistré",
    lessonPlanSavedDesc: "Votre plan de cours a été enregistré avec succès",
    
    // Classroom
    lessonContent: "Leçon",
    students: "Étudiants",
    studentsInClass: "Étudiants en classe",
    searchStudents: "Rechercher des étudiants",
    noStudentsFound: "Aucun étudiant trouvé",
    handRaised: "Main levée",
    handLowered: "Main baissée",
    teacherNotified: "Votre enseignant a été notifié",
    handLoweredDesc: "Votre main a été baissée",
    microphoneEnabled: "Microphone activé",
    microphoneDisabled: "Microphone désactivé",
    youCanNowSpeak: "Vous pouvez maintenant parler à la classe",
    youAreMuted: "Vous êtes maintenant en sourdine",
    cameraEnabled: "Caméra activée",
    cameraDisabled: "Caméra désactivée",
    youAreNowVisible: "Vous êtes maintenant visible pour la classe",
    youAreNowHidden: "Votre caméra est maintenant éteinte",
    clickToPlayVideo: "Cliquez pour lire la vidéo de la leçon",
    play: "Lecture",
    resources: "Ressources",
    chat: "Chat",
    participants: "Participants",
    teacher: "Enseignant",
    host: "Hôte",
    you: "Vous",
    speakingNow: "En train de parler",
    online: "En ligne",
    lastActive: "Dernière activité",
    message: "Message",
    spotlight: "Mettre en avant",
    leaveClass: "Quitter la classe",

    // Resource Library
    resourceLibrary: "Bibliothèque de ressources",
    searchResources: "Rechercher des ressources",
    type: "Type",
    video: "Vidéo",
    audio: "Audio",
    interactive: "Interactif",
    level: "Niveau",
    beginner: "Débutant",
    intermediate: "Intermédiaire",
    advanced: "Avancé",
    download: "Télécharger",
    viewResource: "Voir la ressource",
    noResourcesFound: "Aucune ressource trouvée",
    all: "Tous",
    
    // Student Header
    notifications: "Notifications",
    profile: "Profil",
    language: "Langue",
    
    // Achievements/Gamification
    achievements: "Réalisations",
    learning: "Apprentissage",
    social: "Social",
    streak: "Série",
    mastery: "Maîtrise",
    noAchievementsFound: "Aucune réalisation trouvée dans cette catégorie",

    // Add missing translations for StudyCalendar
    studyCalendar: "Calendrier d'études",
    class: "Cours",
    homework: "Devoir",
    test: "Test",
    practice: "Pratique",
    selectDate: "Sélectionner une date",
    noEventsForDay: "Aucun événement prévu pour ce jour",
    
    // Add missing translations for Progress
    yourProgress: "Votre progression",
    thisWeekActivities: "Activités de cette semaine",
    classesAttended: "Cours suivis",
    pointsEarned: "Points gagnés",
    speaking: "Expression orale",
  }
};

type LanguageOptions = keyof typeof languages;
type LanguageContextType = {
  language: LanguageOptions;
  languageText: (typeof languages)[LanguageOptions];
  setLanguage: (language: LanguageOptions) => void;
};

// Create the language context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

// Language provider component
export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<LanguageOptions>("english");

  const value = {
    language,
    languageText: languages[language],
    setLanguage,
  };

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
};

// Hook to use the language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
