import React, { useMemo, useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { ClipboardPaste, AlertTriangle, CheckCircle2 } from 'lucide-react';
import {
  PLAYGROUND_ALLOWED_BLOCK_TYPES,
  validatePlaygroundBlocks,
  type PlaygroundBlock,
} from '@/playground/importer/allowedBlockTypes';
import type { Slide } from '@/pages/PlaygroundDemo';

interface Props {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  /** Called with normalized Slide[] when the admin confirms a valid paste. */
  onImport: (slides: Slide[]) => void;
}

type ParseState =
  | { kind: 'empty' }
  | { kind: 'parse_error'; message: string }
  | { kind: 'invalid'; errors: ReturnType<typeof validatePlaygroundBlocks> extends { errors: infer E } ? E : never }
  | { kind: 'valid'; blocks: PlaygroundBlock[] };

/**
 * Lift a raw whitelisted JSON block into the Creator's `Slide` shape.
 * Fills minimal scaffolding (voice autoplay) when missing and carries
 * `order_index` matching its position in the pasted array.
 */
function mapJsonBlockToSlide(block: PlaygroundBlock, index: number): Slide {
  const base: Record<string, unknown> = { ...block };
  if (!base.voice || typeof base.voice !== 'object') {
    base.voice = { text: '', autoPlay: true };
  }
  base.order_index = index;
  return base as unknown as Slide;
}

export const PlaygroundJsonImporter: React.FC<Props> = ({ open, onOpenChange, onImport }) => {
  const [raw, setRaw] = useState('');

  const state: ParseState = useMemo(() => {
    const trimmed = raw.trim();
    if (!trimmed) return { kind: 'empty' };
    let parsed: unknown;
    try {
      parsed = JSON.parse(trimmed);
    } catch (e: any) {
      return { kind: 'parse_error', message: e?.message || 'Invalid JSON.' };
    }
    const result = validatePlaygroundBlocks(parsed);
    if (result.ok) return { kind: 'valid', blocks: result.blocks };
    return { kind: 'invalid', errors: result.errors as any };
  }, [raw]);

  const canImport = state.kind === 'valid' && state.blocks.length > 0;
  const blockCount = state.kind === 'valid' ? state.blocks.length : 0;

  const handleImport = () => {
    if (state.kind !== 'valid') return;
    const slides = state.blocks.map((b, i) => mapJsonBlockToSlide(b, i));
    onImport(slides);
    setRaw('');
    onOpenChange(false);
  };

  const handleOpenChange = (v: boolean) => {
    if (!v) setRaw('');
    onOpenChange(v);
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ClipboardPaste className="w-5 h-5 text-orange-500" />
            Import Lesson JSON
          </DialogTitle>
          <DialogDescription>
            Paste a JSON array generated by an external AI. Only Pre-A1 Playground block types are accepted.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-3">
          <div className="text-xs text-muted-foreground">
            <span className="font-semibold">Allowed types:</span>{' '}
            <code className="text-[11px]">{PLAYGROUND_ALLOWED_BLOCK_TYPES.join(', ')}</code>
          </div>

          <Textarea
            value={raw}
            onChange={(e) => setRaw(e.target.value)}
            placeholder='[{"type":"intro","title":"Hello!"}, {"type":"phonics_focus","phoneme":"/æ/"}, ...]'
            className="font-mono text-xs min-h-[280px]"
            spellCheck={false}
          />

          {state.kind === 'parse_error' && (
            <div className="flex items-start gap-2 rounded-lg border-2 border-red-300 bg-red-50 p-3 text-sm text-red-800">
              <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0" />
              <div>
                <div className="font-semibold">Invalid JSON</div>
                <div className="text-xs mt-0.5">{state.message}</div>
              </div>
            </div>
          )}

          {state.kind === 'invalid' && (
            <div className="rounded-lg border-2 border-red-300 bg-red-50 p-3 text-sm text-red-800">
              <div className="flex items-center gap-2 font-semibold mb-1">
                <AlertTriangle className="w-4 h-4" /> {state.errors.length} block{state.errors.length === 1 ? '' : 's'} rejected
              </div>
              <ul className="text-xs space-y-0.5 max-h-32 overflow-y-auto">
                {state.errors.map((err, i) => (
                  <li key={i} className="font-mono">
                    {err.index >= 0 ? `#${err.index}` : '—'}
                    {err.type ? ` [${err.type}]` : ''} — {err.reason}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {state.kind === 'valid' && (
            <div className="flex items-start gap-2 rounded-lg border-2 border-green-300 bg-green-50 p-3 text-sm text-green-800">
              <CheckCircle2 className="w-4 h-4 mt-0.5 shrink-0" />
              <div>
                <div className="font-semibold">
                  {blockCount} block{blockCount === 1 ? '' : 's'} ready to import
                </div>
                <div className="text-xs mt-0.5">
                  All blocks pass the Pre-A1 whitelist. They will be appended to the current lesson.
                </div>
              </div>
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="ghost" onClick={() => handleOpenChange(false)}>Cancel</Button>
          <Button
            onClick={handleImport}
            disabled={!canImport}
            className="bg-orange-500 hover:bg-orange-600 text-white font-bold"
          >
            Import {canImport ? `${blockCount} Block${blockCount === 1 ? '' : 's'}` : 'Lesson'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default PlaygroundJsonImporter;
