import {
  LESSON_1_SCENES, LESSON_1_TITLE, LESSON_1_OBJECTIVE,
  LESSON_2_SCENES, LESSON_2_TITLE, LESSON_2_OBJECTIVE,
  LESSON_3_SCENES, LESSON_3_TITLE, LESSON_3_OBJECTIVE,
  LESSON_4_SCENES, LESSON_4_TITLE, LESSON_4_OBJECTIVE,
  LESSON_5_SCENES, LESSON_5_TITLE, LESSON_5_OBJECTIVE,
  LESSON_6_SCENES, LESSON_6_TITLE, LESSON_6_OBJECTIVE,
  LESSON_U2L1_SCENES, LESSON_U2L1_TITLE, LESSON_U2L1_OBJECTIVE,
  LESSON_U2L2_SCENES, LESSON_U2L2_TITLE, LESSON_U2L2_OBJECTIVE,
  LESSON_U2L3_SCENES, LESSON_U2L3_TITLE, LESSON_U2L3_OBJECTIVE,
  LESSON_U2L4_SCENES, LESSON_U2L4_TITLE, LESSON_U2L4_OBJECTIVE,
  LESSON_U2L5_SCENES, LESSON_U2L5_TITLE, LESSON_U2L5_OBJECTIVE,
  LESSON_U2L6_SCENES, LESSON_U2L6_TITLE, LESSON_U2L6_OBJECTIVE,
  LESSON_U3L1_SCENES, LESSON_U3L1_TITLE, LESSON_U3L1_OBJECTIVE,
  LESSON_U3L2_SCENES, LESSON_U3L2_TITLE, LESSON_U3L2_OBJECTIVE,
  LESSON_U3L3_SCENES, LESSON_U3L3_TITLE, LESSON_U3L3_OBJECTIVE,
  LESSON_U3L4_SCENES, LESSON_U3L4_TITLE, LESSON_U3L4_OBJECTIVE,
  LESSON_U3L5_SCENES, LESSON_U3L5_TITLE, LESSON_U3L5_OBJECTIVE,
  LESSON_U3L6_SCENES, LESSON_U3L6_TITLE, LESSON_U3L6_OBJECTIVE,
  LESSON_U4L1_SCENES, LESSON_U4L1_TITLE, LESSON_U4L1_OBJECTIVE,
  LESSON_U4L2_SCENES, LESSON_U4L2_TITLE, LESSON_U4L2_OBJECTIVE,
  LESSON_U4L3_SCENES, LESSON_U4L3_TITLE, LESSON_U4L3_OBJECTIVE,
  LESSON_U4L4_SCENES, LESSON_U4L4_TITLE, LESSON_U4L4_OBJECTIVE,
  LESSON_U4L5_SCENES, LESSON_U4L5_TITLE, LESSON_U4L5_OBJECTIVE,
  LESSON_U4L6_SCENES, LESSON_U4L6_TITLE, LESSON_U4L6_OBJECTIVE,
  LESSON_U5L1_SCENES, LESSON_U5L1_TITLE, LESSON_U5L1_OBJECTIVE,
  LESSON_U5L2_SCENES, LESSON_U5L2_TITLE, LESSON_U5L2_OBJECTIVE,
  LESSON_U5L3_SCENES, LESSON_U5L3_TITLE, LESSON_U5L3_OBJECTIVE,
  LESSON_U5L4_SCENES, LESSON_U5L4_TITLE, LESSON_U5L4_OBJECTIVE,
  LESSON_U5L5_SCENES, LESSON_U5L5_TITLE, LESSON_U5L5_OBJECTIVE,
  LESSON_U5L6_SCENES, LESSON_U5L6_TITLE, LESSON_U5L6_OBJECTIVE,
  LESSON_U6L1_SCENES, LESSON_U6L1_TITLE, LESSON_U6L1_OBJECTIVE,
  LESSON_U6L2_SCENES, LESSON_U6L2_TITLE, LESSON_U6L2_OBJECTIVE,
  LESSON_U6L3_SCENES, LESSON_U6L3_TITLE, LESSON_U6L3_OBJECTIVE,
  LESSON_U6L4_SCENES, LESSON_U6L4_TITLE, LESSON_U6L4_OBJECTIVE,
  LESSON_U6L5_SCENES, LESSON_U6L5_TITLE, LESSON_U6L5_OBJECTIVE,
  LESSON_U6L6_SCENES, LESSON_U6L6_TITLE, LESSON_U6L6_OBJECTIVE,
  LESSON_U7L1_SCENES, LESSON_U7L1_TITLE, LESSON_U7L1_OBJECTIVE,
  LESSON_U7L2_SCENES, LESSON_U7L2_TITLE, LESSON_U7L2_OBJECTIVE,
  LESSON_U7L3_SCENES, LESSON_U7L3_TITLE, LESSON_U7L3_OBJECTIVE,
  LESSON_U7L4_SCENES, LESSON_U7L4_TITLE, LESSON_U7L4_OBJECTIVE,
  LESSON_U7L5_SCENES, LESSON_U7L5_TITLE, LESSON_U7L5_OBJECTIVE,
  LESSON_U7L6_SCENES, LESSON_U7L6_TITLE, LESSON_U7L6_OBJECTIVE,
  LESSON_U8L1_SCENES, LESSON_U8L1_TITLE, LESSON_U8L1_OBJECTIVE,
  LESSON_U8L2_SCENES, LESSON_U8L2_TITLE, LESSON_U8L2_OBJECTIVE,
} from './unit1/scenes';
import type { Scene } from './unit1/scenes';

export const SCENE_LESSON_REGISTRY: Record<string, Scene[]> = {
  '1-1': LESSON_1_SCENES, '1-2': LESSON_2_SCENES, '1-3': LESSON_3_SCENES,
  '1-4': LESSON_4_SCENES, '1-5': LESSON_5_SCENES, '1-6': LESSON_6_SCENES,
  '2-1': LESSON_U2L1_SCENES, '2-2': LESSON_U2L2_SCENES, '2-3': LESSON_U2L3_SCENES, '2-4': LESSON_U2L4_SCENES,
  '2-5': LESSON_U2L5_SCENES, '2-6': LESSON_U2L6_SCENES,
  '3-1': LESSON_U3L1_SCENES, '3-2': LESSON_U3L2_SCENES, '3-3': LESSON_U3L3_SCENES, '3-4': LESSON_U3L4_SCENES, '3-5': LESSON_U3L5_SCENES, '3-6': LESSON_U3L6_SCENES,
  '4-1': LESSON_U4L1_SCENES, '4-2': LESSON_U4L2_SCENES, '4-3': LESSON_U4L3_SCENES, '4-4': LESSON_U4L4_SCENES, '4-5': LESSON_U4L5_SCENES, '4-6': LESSON_U4L6_SCENES,
  '5-1': LESSON_U5L1_SCENES, '5-2': LESSON_U5L2_SCENES, '5-3': LESSON_U5L3_SCENES, '5-4': LESSON_U5L4_SCENES, '5-5': LESSON_U5L5_SCENES, '5-6': LESSON_U5L6_SCENES,
  '6-1': LESSON_U6L1_SCENES, '6-2': LESSON_U6L2_SCENES, '6-3': LESSON_U6L3_SCENES, '6-4': LESSON_U6L4_SCENES, '6-5': LESSON_U6L5_SCENES, '6-6': LESSON_U6L6_SCENES, '7-1': LESSON_U7L1_SCENES, '7-2': LESSON_U7L2_SCENES, '7-3': LESSON_U7L3_SCENES, '7-4': LESSON_U7L4_SCENES, '7-5': LESSON_U7L5_SCENES, '7-6': LESSON_U7L6_SCENES,
  '8-1': LESSON_U8L1_SCENES, '8-2': LESSON_U8L2_SCENES,
};

export function getSceneLesson(unitNumber: number, lessonNumber: number): Scene[] | null {
  return SCENE_LESSON_REGISTRY[`${unitNumber}-${lessonNumber}`] ?? null;
}

/**
 * Title/objective per lesson, kept in the SAME registry file as the scenes
 * themselves — previously `SceneLessonPlayerModal.tsx` hand-maintained its
 * own separate `LESSON_META` table that only covered '1-1'..'2-1' and
 * silently drifted out of sync as new lessons ('2-2' onward, '3-1', '3-2',
 * '5-1') were added here without a matching entry there. That mismatch
 * made every one of those already-built lessons show "This lesson isn't
 * ready yet." to students despite having real, playable scene content —
 * confirmed as a live bug, fixed by deriving meta from this one registry
 * instead of a second hand-maintained map.
 */
export const SCENE_LESSON_META: Record<string, { title: string; objective: string }> = {
  '1-1': { title: LESSON_1_TITLE, objective: LESSON_1_OBJECTIVE },
  '1-2': { title: LESSON_2_TITLE, objective: LESSON_2_OBJECTIVE },
  '1-3': { title: LESSON_3_TITLE, objective: LESSON_3_OBJECTIVE },
  '1-4': { title: LESSON_4_TITLE, objective: LESSON_4_OBJECTIVE },
  '1-5': { title: LESSON_5_TITLE, objective: LESSON_5_OBJECTIVE },
  '1-6': { title: LESSON_6_TITLE, objective: LESSON_6_OBJECTIVE },
  '2-1': { title: LESSON_U2L1_TITLE, objective: LESSON_U2L1_OBJECTIVE },
  '2-2': { title: LESSON_U2L2_TITLE, objective: LESSON_U2L2_OBJECTIVE },
  '2-3': { title: LESSON_U2L3_TITLE, objective: LESSON_U2L3_OBJECTIVE },
  '2-4': { title: LESSON_U2L4_TITLE, objective: LESSON_U2L4_OBJECTIVE },
  '2-5': { title: LESSON_U2L5_TITLE, objective: LESSON_U2L5_OBJECTIVE },
  '2-6': { title: LESSON_U2L6_TITLE, objective: LESSON_U2L6_OBJECTIVE },
  '3-1': { title: LESSON_U3L1_TITLE, objective: LESSON_U3L1_OBJECTIVE },
  '3-2': { title: LESSON_U3L2_TITLE, objective: LESSON_U3L2_OBJECTIVE },
  '3-3': { title: LESSON_U3L3_TITLE, objective: LESSON_U3L3_OBJECTIVE },
  '3-4': { title: LESSON_U3L4_TITLE, objective: LESSON_U3L4_OBJECTIVE },
  '3-5': { title: LESSON_U3L5_TITLE, objective: LESSON_U3L5_OBJECTIVE },
  '3-6': { title: LESSON_U3L6_TITLE, objective: LESSON_U3L6_OBJECTIVE },
  '4-1': { title: LESSON_U4L1_TITLE, objective: LESSON_U4L1_OBJECTIVE },
  '4-2': { title: LESSON_U4L2_TITLE, objective: LESSON_U4L2_OBJECTIVE },
  '4-3': { title: LESSON_U4L3_TITLE, objective: LESSON_U4L3_OBJECTIVE },
  '4-4': { title: LESSON_U4L4_TITLE, objective: LESSON_U4L4_OBJECTIVE },
  '4-5': { title: LESSON_U4L5_TITLE, objective: LESSON_U4L5_OBJECTIVE },
  '4-6': { title: LESSON_U4L6_TITLE, objective: LESSON_U4L6_OBJECTIVE },
  '5-1': { title: LESSON_U5L1_TITLE, objective: LESSON_U5L1_OBJECTIVE },
  '5-2': { title: LESSON_U5L2_TITLE, objective: LESSON_U5L2_OBJECTIVE },
  '5-3': { title: LESSON_U5L3_TITLE, objective: LESSON_U5L3_OBJECTIVE },
  '5-4': { title: LESSON_U5L4_TITLE, objective: LESSON_U5L4_OBJECTIVE },
  '5-5': { title: LESSON_U5L5_TITLE, objective: LESSON_U5L5_OBJECTIVE },
  '5-6': { title: LESSON_U5L6_TITLE, objective: LESSON_U5L6_OBJECTIVE },
  '6-1': { title: LESSON_U6L1_TITLE, objective: LESSON_U6L1_OBJECTIVE },
  '6-2': { title: LESSON_U6L2_TITLE, objective: LESSON_U6L2_OBJECTIVE },
  '6-3': { title: LESSON_U6L3_TITLE, objective: LESSON_U6L3_OBJECTIVE },
  '6-4': { title: LESSON_U6L4_TITLE, objective: LESSON_U6L4_OBJECTIVE },
  '6-5': { title: LESSON_U6L5_TITLE, objective: LESSON_U6L5_OBJECTIVE },
  '6-6': { title: LESSON_U6L6_TITLE, objective: LESSON_U6L6_OBJECTIVE },
  '7-1': { title: LESSON_U7L1_TITLE, objective: LESSON_U7L1_OBJECTIVE },
  '7-2': { title: LESSON_U7L2_TITLE, objective: LESSON_U7L2_OBJECTIVE },
  '7-3': { title: LESSON_U7L3_TITLE, objective: LESSON_U7L3_OBJECTIVE },
  '7-4': { title: LESSON_U7L4_TITLE, objective: LESSON_U7L4_OBJECTIVE },
  '7-5': { title: LESSON_U7L5_TITLE, objective: LESSON_U7L5_OBJECTIVE },
  '7-6': { title: LESSON_U7L6_TITLE, objective: LESSON_U7L6_OBJECTIVE },
  '8-1': { title: LESSON_U8L1_TITLE, objective: LESSON_U8L1_OBJECTIVE },
  '8-2': { title: LESSON_U8L2_TITLE, objective: LESSON_U8L2_OBJECTIVE },
};

export function getSceneLessonMeta(unitNumber: number, lessonNumber: number): { title: string; objective: string } | null {
  return SCENE_LESSON_META[`${unitNumber}-${lessonNumber}`] ?? null;
}

/** Which Little Explorers Phonics (`lep1-rich`) lesson owns this scene list
 *  (by identity — the players only receive `scenes`). Null for ad-hoc lists. */
export function identifySceneLesson(scenes: unknown): { contentFormat: 'lep1-rich'; unitNumber: number; lessonNumber: number; title: string } | null {
  for (const [key, list] of Object.entries(SCENE_LESSON_REGISTRY)) {
    if (list !== scenes) continue;
    const [u, l] = key.split('-').map(Number);
    return { contentFormat: 'lep1-rich', unitNumber: u, lessonNumber: l, title: SCENE_LESSON_META[key]?.title ?? '' };
  }
  return null;
}
