#!/usr/bin/env bun
/**
 * Programmatic Unit Factory.
 *
 *   bun scripts/generate-unit.ts src/playground-blueprint/manifests/produce.unit.json
 *
 * Reads a UnitManifest JSON and emits one compiled lesson route per lesson into
 *   src/playground-blueprint/generated/<unit_id>-l<n>.tsx
 *
 * The output is deterministic — no AI text generation — so OSASCOMP rules,
 * the 10-phase order, sessionStorage keys, and topic emoji locks land
 * identically every time.
 */
import fs from "node:fs";
import path from "node:path";

interface PhonicSeed { letter: string; sound: string; words: string[]; }
interface LessonSeed {
  vocab?: string[];
  sentence_frame?: string;
  phonic?: PhonicSeed;
}
interface UnitManifest {
  unit_id: string;
  unit_title: string;
  meta: {
    primary_color: string;
    accent_color: string;
    container_theme: string;
    brain_break_emojis: string[];
  };
  lessons: Record<string, LessonSeed & Record<string, unknown>>;
}

const manifestArg = process.argv[2];
if (!manifestArg) {
  console.error("usage: bun scripts/generate-unit.ts <manifest.json>");
  process.exit(1);
}

const manifest: UnitManifest = JSON.parse(fs.readFileSync(manifestArg, "utf8"));
const { unit_id, unit_title, meta } = manifest;

const outDir = path.resolve("src/playground-blueprint/generated");
fs.mkdirSync(outDir, { recursive: true });

const lessonKeys = Object.keys(manifest.lessons).filter(k => k !== "l4_storybook");

lessonKeys.forEach((key, idx) => {
  const lesson = manifest.lessons[key] as LessonSeed;
  const n = idx + 1;
  const vocab = lesson.vocab ?? [];
  const phonic = lesson.phonic ?? { letter: "", sound: "", words: [] };
  const frame = lesson.sentence_frame ?? "";

  const code = `// ⚠️ AUTOMATICALLY GENERATED BY scripts/generate-unit.ts — DO NOT EDIT BY HAND
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { VocabularyPhase } from "@/playground-blueprint/components/phases/Vocabulary";
import { Modeling as ModelingPhase } from "@/playground-blueprint/components/phases/Modeling";
import { MemoryMatchPhase } from "@/playground-blueprint/components/phases/MemoryMatch";
import { PracticePhase } from "@/playground-blueprint/components/phases/Practice";
import { SentencePhase } from "@/playground-blueprint/components/phases/Sentence";
import { PhonicsAnyPhase } from "@/playground-blueprint/components/phases/PhonicsAny";
import { SpellingPhase } from "@/playground-blueprint/components/phases/Spelling";
import { ChantPhase } from "@/playground-blueprint/components/phases/Chant";
import { BrainBreakPhase } from "@/playground-blueprint/components/phases/BrainBreak";
import { CoolDownPhase } from "@/playground-blueprint/components/phases/CoolDown";

// Immutable 10-phase blueprint. Order is locked by the factory, not the AI.
const PHASES = [
  "VOCABULARY","MODELING","MEMORY_MATCH","CONTROLLED_OUTPUT","PHONICS",
  "FREE_OUTPUT","SPELLING","CHANT","BRAIN_BREAK","COOL_DOWN",
] as const;

const STORAGE_KEY = "playground-${unit_id}-l${n}-progress";
const VOCAB = ${JSON.stringify(vocab)};
const FRAME = ${JSON.stringify(frame)};
const PHONIC = ${JSON.stringify(phonic)};
const BRAIN_BREAK_EMOJIS = ${JSON.stringify(meta.brain_break_emojis)};

export default function ${capitalize(unit_id)}L${n}() {
  const [i, setI] = useState<number>(() => {
    const s = sessionStorage.getItem(STORAGE_KEY);
    return s ? parseInt(s, 10) : 0;
  });
  useEffect(() => { sessionStorage.setItem(STORAGE_KEY, String(i)); }, [i]);
  const next = () => setI((p) => Math.min(p + 1, PHASES.length - 1));
  const active = PHASES[i];

  return (
    <main
      className="min-h-screen p-6"
      style={{ background: \`linear-gradient(160deg, ${meta.accent_color}, white)\` }}
    >
      <header className="mb-4 flex items-center justify-between">
        <h1 className="text-2xl font-bold" style={{ color: "${meta.primary_color}" }}>
          ${unit_title} · Lesson ${n}
        </h1>
        <span className="text-sm text-gray-500">{active} ({i + 1}/{PHASES.length})</span>
      </header>

      <section className="playground-card rounded-3xl p-8 min-h-[500px] bg-white shadow">
        {active === "VOCABULARY"        && <VocabularyPhase items={VOCAB} onComplete={next} />}
        {active === "MODELING"          && <ModelingPhase frame={FRAME} onComplete={next} />}
        {active === "MEMORY_MATCH"      && <MemoryMatchPhase scope={VOCAB} onComplete={next} />}
        {active === "CONTROLLED_OUTPUT" && <SentencePhase frame={FRAME} onComplete={next} />}
        {active === "PHONICS"           && <PhonicsAnyPhase letter={PHONIC.letter} sound={PHONIC.sound} words={PHONIC.words} onComplete={next} />}
        {active === "FREE_OUTPUT"       && <PracticePhase scope={VOCAB} onComplete={next} />}
        {active === "SPELLING"          && <SpellingPhase targetWords={VOCAB} onComplete={next} />}
        {active === "CHANT"             && <ChantPhase frame={FRAME} onComplete={next} />}
        {active === "BRAIN_BREAK"       && <BrainBreakPhase containerTheme="${meta.container_theme}" allowedEmojis={BRAIN_BREAK_EMOJIS} onComplete={next} />}
        {active === "COOL_DOWN"         && (
          <CoolDownPhase>
            <Link to="/playground/${unit_id}-l${n + 1}" className="underline">Next lesson →</Link>
          </CoolDownPhase>
        )}
      </section>
    </main>
  );
}
`;

  const file = path.join(outDir, `${unit_id}-l${n}.tsx`);
  fs.writeFileSync(file, code, "utf8");
  console.log(` ✅ Factory compiled: ${path.relative(process.cwd(), file)}`);
});

function capitalize(s: string): string {
  return s.replace(/(^|[-_])([a-z])/g, (_, __, c) => c.toUpperCase());
}
