// SessionPlan for A1-S01-E1 "Who Are You? · Cold Open". Matches the player script src/academy-player/samples/a1s01e1.ts.
import type { SessionPlan } from '../sessionPlan';

export const A1S01E1_PLAN: SessionPlan = {
  id: 'A1-S01-E1',
  seasonId: 'A1-S01',
  episode: 1,
  minutes: 60,
  lastTimeCard: {
    did: ['First session: nothing to recall yet.', 'Today we meet each other and find clue 1.', 'No tests. Wrong tries are how we learn.'],
    remember: 'Hello is a word you already know.',
  },
  newItems: ['hello', 'welcome', 'name', 'friend', 'new', 'student', 'teacher', 'class', 'meet', 'online', 'nice', 'group', 'member', 'introduce'],
  segments: [
    {
      name: 'Check-in', core: false, minutes: 5, technique: 'rapport and low-anxiety first speech',
      teacher: ['Smile, say hello, say your name. Ask nothing hard.', 'Read the energy from the first reaction; pick Chill track if low.'],
      student: ['Watches Vee, Ava and Theo say hello.'],
      comfort: ['Type or point instead of speaking', 'No camera needed'],
      fun: ['cast characters greet the student'],
    },
    {
      name: 'Remember?', core: true, minutes: 7, technique: 'retrieval of prior knowledge (no stakes, first session)',
      mechanic: 'pick-a-word-you-know',
      why: 'First session: show the student they already know English words (confidence), no items due yet.',
      teacher: ['Wait 7 seconds after the question.', 'Praise any answer: "Nice!"'],
      student: ['Picks one word they know: Hello, Friend or Class.'],
      comfort: ['Every option is right', 'Replay and Back available'],
    },
    {
      name: 'The Drop', core: true, minutes: 10, technique: 'comprehensible input with interest and surprise',
      mechanic: 'chat story + comic strip + gist choice',
      why: 'A mystery profile appears in the group: a story hook with 95 %+ known words.',
      teacher: ['Let the student tap the chat messages at their own speed.', 'Do not pre-teach: gist only (Who is Sam?).'],
      student: ['Reads the chat, replies "Hello, Sam! Welcome to the group.", reads the comic, answers Who is Sam?'],
      comfort: ['Tap-to-gloss on key words', 'Hint removes wrong answers first'],
      fun: ['mystery clue', 'chat story', 'comic panels'],
    },
    {
      name: 'Notice & Build', core: true, minutes: 10, technique: 'noticing + deliberate vocabulary (sets of 4) + sentence building',
      mechanic: 'flash sets of four + sentence-tile build',
      why: 'Meet 12 of the 14 words in context, then assemble My name is Sam and I am a new student.',
      teacher: ['Ask "Which word?" not "What does it mean?".', 'Let the student hear each card twice.'],
      student: ['Taps cards, checks, builds two short sentences from tiles.'],
      comfort: ['Undo word', 'Wrong tile: "Not yet — try again."'],
      fun: ['word cards'],
    },
    {
      name: 'Energiser', core: false, minutes: 4, technique: 'attention reset with retrieval',
      mechanic: 'odd one out (two rounds)',
      teacher: ['Play along, no timer.'],
      student: ['Finds the odd word twice.'],
      comfort: ['No countdown', 'Skippable'],
      fun: ['quick game'],
    },
    {
      name: 'Mission', core: true, minutes: 12, technique: 'pushed output with task repetition (Take 1 -> feedback -> Take 2)',
      mechanic: 'sentence build, three levels',
      teacher: ['Set the dial with the student.', 'Log errors silently; give one fix, end on a success.'],
      student: ['Picks Chill, Normal or Push; builds an introduction; tries again with one change.'],
      comfort: ['Dial is the student\'s choice', 'Hint tier 2 highlights the next tile'],
      fun: ['introduce two cast members', 'dial choice'],
    },
    {
      name: 'Release', core: true, minutes: 7, technique: 'generation and ownership',
      mechanic: 'private say-it-or-type-it',
      teacher: ['Model once, then wait.', 'Never correct the first attempt.'],
      student: ['Says or types "Hello, Sam! Welcome to the group."'],
      comfort: ['Type instead of speak', 'Nothing is recorded in this version'],
    },
    {
      name: 'Wrap', core: true, minutes: 5, technique: 'metacognition (can-do self-rating)',
      teacher: ['Name one Best Line of the session.', 'Say that "Not yet" is useful.'],
      student: ['Rates three can-dos Yes / Almost / Not yet; hears the next clue.'],
      comfort: ['"Not yet" is a safe answer'],
      fun: ['next clue teaser'],
    },
  ],
  mission: {
    dial: {
      chill: 'Take 1: "Hello, my friend." Take 2: "Hello, I am Ava."',
      normal: 'Take 1: "This is my friend Ava." Take 2: "Hello, this is my friend Ava."',
      push: 'Take 1: "This is my new friend Ava." Take 2: "Hello Theo, this is my new friend Ava."',
    },
    planningSeconds: 60,
    take2: 'Add one thing: a name (Chill), hello first (Normal), hello and his name (Push).',
    criteria: ['I used the right order of words.', 'I started with hello in Take 2.'],
  },
  release: { spec: 'Say or type one welcome sentence to Sam. Private; the teacher can read it.', rubricId: 'A1-S01-E1-release' },
  wrap: {
    canDo: ['I know: hello, welcome, friend.', 'I know: student, teacher, class.', 'I know: Nice to meet you.'],
    homework: ['Say hello to one friend.'],
    dailyTenPackId: 'A1-S01-daily-1',
    nextClue: 'Clue 1 of 8: Sam is a new member of the group, but Sam is not in our class.',
  },
  chillTrack: 'Skip the dial and Take 2: build "Hello, my friend." then go straight to the Release.',
  planB: 'If the player fails: read the chat aloud with the student, ask "Who is Sam?", and write the four people words on the whiteboard. Say the welcome sentence together.',
  errorLogCategories: ['word order', 'missing word', 'wrong word (teacher/student)', 'hesitation over 10 seconds'],
  teacherNotes: [
    'Wait 5-7 seconds. Silence is thinking.',
    'Likely errors: "I am name Sam" (word order). Prompt: "Which word comes after My?"',
    'Log: tiles undone, hint tier used, minutes asked for.',
    'Do not: translate every word, correct pronunciation in the first minutes, use the camera as a requirement.',
    'No recording is made in this version; the recording booth and guardian consent are not built yet.',
  ],
};
