// SessionPlan for A1-S01-E1 "Who Are You? · Cold Open". Matches the player script src/academy-player/samples/a1s01e1.ts
// and the Academy lesson blueprint for this session (docs/academy-a1s01e1-spec.md).
import type { SessionPlan } from '../sessionPlan';

export const A1S01E1_PLAN: SessionPlan = {
  id: 'A1-S01-E1',
  seasonId: 'A1-S01',
  episode: 1,
  minutes: 60,
  lastTimeCard: {
    did: ['First session: nothing to recall yet.', 'Today we meet Vee, Ava and Theo and open the mystery of Sam.', 'No tests. Wrong tries are how we learn.'],
    remember: 'You already know some English words.',
  },
  newItems: ['hello', 'welcome', 'name', 'friend', 'new', 'student', 'teacher', 'class', 'meet', 'online', 'nice', 'group', 'member', 'introduce'],
  segments: [
    {
      name: 'Check-in', core: false, minutes: 5, technique: 'rapport and low-anxiety first speech',
      teacher: ['Smile, say hello, say your name. Wait 5-7 seconds after "What is your name?".', 'Read the energy emoji; if low, plan the Chill track.', 'Say that any name or nickname is fine.'],
      student: ['Watches Vee, Ava and Theo say hello.', 'Types a name or nickname, picks an energy emoji and a theme emoji.'],
      comfort: ['Any name or nickname', 'Type instead of speak', 'No camera needed'],
      fun: ['cast greet the student by name', 'student picks a theme'],
    },
    {
      name: 'Remember?', core: true, minutes: 7, technique: 'retrieval of prior knowledge (no stakes, first session)',
      mechanic: 'word sort (I know it / Not yet) + five quick retrieval questions',
      why: 'First session: show the student they already know English words (confidence) and give the teacher a word-level baseline.',
      teacher: ['Look at which words were "Not yet" and note them.', 'Praise any answer: "Nice!".'],
      student: ['Sorts 12 words; answers five quick questions with the words.'],
      comfort: ['No wrong answer in the sort', 'Replay and Back available'],
    },
    {
      name: 'The Drop', core: true, minutes: 10, technique: 'comprehensible input with interest and surprise; gist before detail',
      mechanic: 'class group chat + profile card with odd-thing hotspots + comic strip + gist checks + own-words idea',
      why: 'A mystery profile appears in Ava\'s class group: a story hook with at least 95 % known or glossed words (Hu & Nation 2000; Laufer 1989).',
      teacher: ['Let the student read at their own speed; do not pre-teach.', 'Ask "What is odd?" and wait before they tap.', 'Accept a one-word answer to "Sam is a ___".'],
      student: ['Reads the chat and replies to Sam, finds three odd things on Sam\'s profile, reads the comic, answers four gist questions, says in their own words who Sam is.'],
      comfort: ['Tap-to-gloss on key words', 'Hint removes wrong answers first', 'Show me button on the profile'],
      fun: ['mystery clue', 'group chat story', 'spot-what-is-odd', 'comic panels'],
    },
    {
      name: 'Notice & Build', core: true, minutes: 10, technique: 'deliberate vocabulary in sets of 3-4 + noticing a frame + sentence building',
      mechanic: 'four flash sets (14 words), match question to answer, tile builder',
      why: 'Pre-teaching words right after the story helps beginners\' comprehension (Japanese high-school EFL study); the frame is noticed before it is used.',
      teacher: ['Ask "Which word?" not "What does it mean?".', 'Point at the frame: My name is ___. I am a ___.'],
      student: ['Meets 14 words in four sets, checks each set, matches five question-answer pairs, builds "I am a new student."'],
      comfort: ['Undo word', 'Wrong tile: "Not yet — try again."'],
      fun: ['word cards'],
    },
    {
      name: 'Energiser', core: false, minutes: 4, technique: 'attention reset with retrieval',
      mechanic: 'would-you-rather, person-or-not sort, word-in-gap match, odd one out',
      teacher: ['Play along, no timer.'],
      student: ['Picks a side, sorts eight words, fills four gaps, finds two odd words.'],
      comfort: ['No countdown', 'Skippable'],
      fun: ['quick game', 'would-you-rather'],
    },
    {
      name: 'Mission', core: true, minutes: 12, technique: 'pushed output with task repetition (Take 1 -> feedback -> Take 2); share an opinion',
      mechanic: 'say-or-type introduction, then an opinion about Sam',
      teacher: ['Set the dial with the student.', 'Log errors silently; give one fix, end on a success.', 'Do not correct the first attempt.'],
      student: ['Picks Chill, Normal or Push; introduces self to Theo (Take 1), hears feedback, repeats with one addition (Take 2); answers Ava; gives an opinion "I think Sam is a ___".'],
      comfort: ['Dial is the student\'s choice', 'Type instead of speak', 'Hint tier 2 highlights the next tile'],
      fun: ['introduce yourself to a cast member', 'dial choice', 'opinion about the mystery'],
    },
    {
      name: 'Release', core: true, minutes: 7, technique: 'generation and ownership; private first',
      mechanic: 'own profile form shown back as a card + say-or-type hello + one-sentence reaction',
      teacher: ['Model once, then wait.', 'Never correct the first attempt.', 'Read the typed lines if the student agrees.'],
      student: ['Picks "I am a ..." and "I am ..." for their own profile card; says or types a two-sentence introduction; says or types one sentence about Sam.'],
      comfort: ['Private first', 'Type instead of speak', 'Nothing is recorded in this version'],
      fun: ['own profile card'],
    },
    {
      name: 'Wrap', core: true, minutes: 5, technique: 'metacognition (can-do self-rating)',
      teacher: ['Name one Best Line of the session (from the typed or spoken lines).', 'Say that "Not yet" is useful.'],
      student: ['Rates three can-dos Yes / Almost / Not yet; picks a theme for next time; hears the clue and the teaser.'],
      comfort: ['"Not yet" is a safe answer'],
      fun: ['next clue teaser', 'student picks the next theme'],
    },
  ],
  mission: {
    dial: {
      chill: 'Take 1: copy "Hello, my name is Ava." Take 2: say it with your name; then build "What is your name?".',
      normal: 'Take 1: "Hello, my name is ___. Nice to meet you." Take 2: add "What is your name?".',
      push: 'Take 1: say hello, your name, and ask for his name. Take 2: introduce Ava to Theo.',
    },
    planningSeconds: 60,
    take2: 'Repeat with one addition: your own name (Chill), the question "What is your name?" (Normal), introducing a friend (Push).',
    criteria: ['I said hello and my name.', 'In Take 2 I added the new part.', 'I gave an idea about Sam.'],
  },
  release: { spec: 'A profile card (I am a ..., I am ...), a two-sentence introduction and one sentence about Sam. Private; the teacher can read it.', rubricId: 'A1-S01-E1-release' },
  wrap: {
    canDo: ['I know: hello, student, teacher, friend.', 'I say: Hello, my name is ___.', 'I know who Sam is.'],
    homework: ['Say hello to one friend.'],
    dailyTenPackId: 'A1-S01-daily-1',
    nextClue: 'Clue 1 of 8: Sam is a new member of the group, but Sam is not in our class.',
  },
  chillTrack: 'Skip the dial, the Energiser sort and Take 2: copy "Hello, my name is Ava.", then say it with your name, then go straight to the Release profile card.',
  planB: 'If the player fails: read the chat aloud together and write Sam\'s profile on a shared whiteboard; ask "What is odd?"; say "Hello, my name is ___. Nice to meet you." together; the student writes their own three-line profile in the chat.',
  errorLogCategories: ['word order', 'missing word', 'wrong word (teacher/student)', 'hesitation over 10 seconds', 'frame not used'],
  teacherNotes: [
    'Wait 5-7 seconds. Silence is thinking.',
    'Likely errors: "I am name Sam" (word order). Prompt: "Which word comes after My?"',
    'Log: tiles undone, hint tier used, minutes asked for, words marked "Not yet" in the Remember? sort.',
    'Do not: translate every word, correct pronunciation in the first minutes, use the camera as a requirement.',
    'No recording is made in this version; the recording booth and guardian consent are not built yet.',
  ],
};
