// A1 (10 Seasons, 80 sessions, ~800 cumulative items). CEFR A1: understands and uses familiar everyday expressions and
// very basic phrases; introduces self and others; asks and answers simple questions about personal details.
// Supports are at their maximum: full sentence frames, first-language hint, 0.8x audio. Input texts ~30-60 words [U].
import type { RawSeason } from '../authoring';

export const A1_SEASONS: RawSeason[] = [
  {
    title: 'Who Are You?',
    theme: 'Online profiles and meeting people',
    hook: "A fake profile has appeared in Ava's group chat. Who made it - and can you spot what is wrong with it?",
    release: 'My profile card plus a 30-second voice introduction',
    canDo: [
      'I can say hello, say my name, age and country, and ask someone the same.',
      'I can spell my name and read a short online profile.',
    ],
    functions: ['greeting and leave-taking', 'introducing yourself', 'asking for personal information', 'spelling'],
    structures: ['be-present', 'possessive-adjectives'],
    lexicalFields: ['personal information', 'countries and nationalities', 'numbers 0-20', 'the alphabet', 'classroom language'],
    items: 80,
    pron: ['the alphabet (letter names that sound alike: e/i, b/p)', 'word stress in country names'],
    skins: ['gaming', 'music', 'football', 'social'],
  },
  {
    title: 'My Room, My Stuff',
    theme: 'Rooms, gadgets and where things are',
    hook: "Theo's charger keeps vanishing. Follow the clues around his room to find out where it went.",
    release: 'A voice-note tour of my room',
    canDo: [
      'I can say what there is in a room and where things are.',
      'I can name common objects and gadgets and say what colour they are.',
    ],
    functions: ['describing a place', 'saying where things are', 'asking where something is'],
    structures: ['there-is-are', 'prepositions-place'],
    lexicalFields: ['furniture and rooms', 'gadgets and everyday objects', 'colours', 'plural nouns'],
    items: 80,
    pron: ['plural endings /s/ /z/ /iz/', 'the /ɪ/ vs /iː/ contrast (it / eat)'],
    skins: ['tech', 'gaming', 'art', 'animals'],
  },
  {
    title: 'Free Time Club',
    theme: 'Hobbies and the Club Fair',
    hook: 'At the Club Fair, Ava needs three members before Friday or her club closes. Can you help her find them?',
    release: 'A 45-second pitch for a club I would start',
    canDo: [
      'I can say what I like and do in my free time.',
      'I can ask a classmate what they like doing and understand the answer.',
    ],
    functions: ['talking about likes and dislikes', 'talking about hobbies', 'asking about interests'],
    structures: ['present-simple', 'like-ing'],
    lexicalFields: ['hobbies and sports', 'music and media', 'places for free time'],
    items: 80,
    pron: ['-ing endings', 'sentence stress on key words'],
    skins: ['football', 'music', 'gaming', 'anime', 'art'],
  },
  {
    title: 'Café Night',
    theme: 'Food, drinks and ordering',
    hook: "Mia is running a pop-up café for one night with a tiny budget. Help her take orders and keep the customers happy.",
    release: 'A short café role-play with my own menu',
    canDo: [
      'I can ask for food and drink politely and understand the price.',
      'I can say what I want and what I have not got.',
    ],
    functions: ['ordering food and drink', 'asking for and giving prices', 'polite requests'],
    structures: ['some-any', 'would-like'],
    lexicalFields: ['food and drink', 'menu items and prices', 'quantities and containers'],
    items: 80,
    pron: ['the /θ/ and /s/ in "thanks / sandwich" (listen first)', 'rising tone in polite questions'],
    skins: ['food', 'fitness', 'travel', 'film'],
  },
  {
    title: 'A Day in My Life',
    theme: 'Daily routines and the school day',
    hook: "Mia is filming a 'day in my life' vlog challenge. Can you describe your day better than hers?",
    release: 'A short vlog script and recording of my day',
    canDo: [
      'I can say what I do every day and at what time.',
      'I can tell the time and talk about my school day.',
    ],
    functions: ['describing routines', 'telling the time', 'saying how often you do things'],
    structures: ['present-simple-3rd', 'frequency-adverbs'],
    lexicalFields: ['daily routine verbs', 'school subjects and timetable', 'times of day and days of the week'],
    items: 80,
    pron: ['third-person -s endings /s/ /z/ /iz/', 'the /h/ sound in "he / has / hour"'],
    skins: ['social', 'football', 'music', 'fitness'],
  },
  {
    title: 'Family and Friends',
    theme: 'People close to me',
    hook: 'A family photo from Theo\'s grandparents has no names on the back. Work out who is who from the clues.',
    release: 'My family or friends tree with a spoken description of three people',
    canDo: [
      'I can say who the people in my life are and describe what they look like.',
      'I can say what people have and whose things they are.',
    ],
    functions: ['talking about family', 'describing people', 'talking about possessions'],
    structures: ['have-got', 'possessive-s'],
    lexicalFields: ['family members', 'appearance and personality adjectives', 'ages and birthdays'],
    items: 80,
    pron: ['the /ð/ sound in "mother, father, brother" (aim for intelligible)', 'stress in adjective + noun phrases'],
    skins: ['animals', 'film', 'anime', 'fashion'],
  },
  {
    title: 'Treasure Map Town',
    theme: 'Places in town and giving directions',
    hook: 'Vee has hidden a treasure somewhere in town and left a map with missing words. Fill in the directions to reach it.',
    release: 'A voice guide that leads a friend to a hidden place on a map',
    canDo: [
      'I can name places in a town and say where they are.',
      'I can ask for and give simple directions.',
    ],
    functions: ['giving directions', 'asking where a place is', 'giving simple instructions'],
    structures: ['imperatives', 'prepositions-movement-basic'],
    lexicalFields: ['places in town', 'directions and landmarks', 'transport'],
    items: 80,
    pron: ['stress in compound nouns (bus stop, car park)', 'clear final consonants (turn, left)'],
    skins: ['travel', 'gaming', 'nature', 'football'],
  },
  {
    title: 'Can Do!',
    theme: 'Talents and abilities',
    hook: 'Theo secretly entered the school talent show. Find out what each friend can do before the curtain goes up.',
    release: 'A talent card: what I can and cannot do, with one demonstration',
    canDo: [
      'I can say what I can and cannot do.',
      'I can ask others what they can do and join two ideas with and or but.',
    ],
    functions: ['talking about ability', 'asking for and giving help', 'simple linking of ideas'],
    structures: ['can-ability', 'linking-and-but'],
    lexicalFields: ['abilities and skills', 'sports and performing arts', 'common verbs of action'],
    items: 80,
    pron: ['can /kən/ vs can\'t /kɑːnt/ (the vowel carries the meaning)', 'the /ŋ/ in "singing, dancing"'],
    skins: ['music', 'football', 'gaming', 'art', 'fitness'],
  },
  {
    title: 'Market Day',
    theme: 'Clothes, shopping and money',
    hook: "Ava has a stall at the vintage market and ten pounds to spend. Can you bargain better than she can?",
    release: 'A market role-play: buying and selling with prices',
    canDo: [
      'I can ask how much something is and say what I want to buy.',
      'I can point to things and say which one I mean.',
    ],
    functions: ['shopping', 'asking for and giving prices', 'choosing between things'],
    structures: ['demonstratives', 'how-much-many'],
    lexicalFields: ['clothes and accessories', 'colours and sizes', 'numbers to 100 and money'],
    items: 80,
    pron: ['teens vs tens (13/30, 14/40) - stress on the right syllable', 'the /ɪ/ vs /iː/ contrast (this / these)'],
    skins: ['fashion', 'tech', 'music', 'gaming'],
  },
  {
    title: 'Right Now',
    theme: 'What is happening now: a live stream',
    hook: "Vee is going live from the town square and needs a co-host who can describe what is happening, right now.",
    release: 'A 60-second live commentary clip',
    canDo: [
      'I can say what is happening at this moment.',
      'I can ask and answer simple questions with who, what, where, when and why.',
    ],
    functions: ['describing what is happening now', 'asking wh-questions', 'talking about the weather'],
    structures: ['present-continuous-now', 'wh-questions'],
    lexicalFields: ['actions and activities', 'weather and seasons', 'places and events'],
    items: 80,
    pron: ['-ing and weak "are" in "What are you doing?"', 'falling intonation in wh-questions'],
    skins: ['social', 'football', 'travel', 'film', 'nature'],
    notes: 'Level check Season: E8 includes the A1 level check (separate from XP).',
  },
];
