// A2 (12 Seasons, 96 sessions, ~1,650 cumulative items). CEFR A2: understands frequently used expressions on immediate
// topics; handles simple routine exchanges; describes in simple terms background, immediate environment and past events.
// Supports: half frames, tiered hints, 0.9x audio on request. Input texts ~80-150 words [U].
// Ordering decisions (see structureLevels.ts): going to (S4) and will (S9) are separate Seasons; must/mustn't (S6) is not paired
// with the don't-have-to contrast (B1); the present perfect is held back to B1.
import type { RawSeason } from '../authoring';

export const A2_SEASONS: RawSeason[] = [
  {
    title: 'Last Weekend',
    theme: 'Telling a story about the past',
    hook: "Ava posted photos from a weekend nobody remembers her having. Piece together what really happened.",
    release: 'A voice note telling the story of my last weekend',
    canDo: [
      'I can say what I did and where I was at a time in the past.',
      'I can understand a short story about past events.',
    ],
    functions: ['describing past events', 'saying where you were', 'sequencing events (first, then, after that)'],
    structures: ['past-be', { id: 'past-simple-regular' }],
    lexicalFields: ['weekend activities', 'time expressions for the past', 'places and events', 'feelings'],
    items: 69,
    pron: ['-ed endings /t/ /d/ /ɪd/', 'was / were in fast speech (weak forms)'],
    skins: ['social', 'football', 'music', 'travel'],
  },
  {
    title: 'Travel Trouble',
    theme: 'Journeys that went wrong',
    hook: "Theo's school trip had a lost passport, a missed train and one very strange taxi. Find out what he did next.",
    release: 'A postcard or message about a trip that went wrong',
    canDo: [
      'I can tell a simple story about a trip, using common past verbs.',
      'I can ask and answer questions about what happened.',
    ],
    functions: ['narrating past events', 'asking about past events', 'describing a problem while travelling'],
    structures: ['past-simple-irregular'],
    lexicalFields: ['travel and transport', 'holiday problems', 'common irregular verbs', 'places abroad'],
    items: 69,
    pron: ['vowel changes in irregular verbs (go / went, buy / bought)', 'did you ... linking /dɪdʒu/ (listening focus)'],
    skins: ['travel', 'gaming', 'film', 'food'],
  },
  {
    title: 'Gadget Wars',
    theme: 'Comparing technology',
    hook: "Two rival phone brands are fighting over Mia's choice for her birthday. Compare them and settle the argument.",
    release: 'A written review comparing two things I own or want',
    canDo: [
      'I can compare two or more things and say which is best.',
      'I can give a short reason for my choice.',
    ],
    functions: ['comparing', 'recommending', 'giving a reason'],
    structures: ['comparatives-superlatives'],
    lexicalFields: ['technology and features', 'adjectives for quality and size', 'prices and money'],
    items: 69,
    pron: ['weak "than" /ðən/', 'word stress in adjectives (expensive, comfortable)'],
    skins: ['tech', 'gaming', 'fashion', 'music'],
  },
  {
    title: 'Plans and Dreams',
    theme: 'Plans for next week and next summer',
    hook: "Vee asks everyone to hand in a plan for the summer. Ava's plan is very bold. Can you make a better one?",
    release: 'My plan for next summer, spoken and as a short written list',
    canDo: [
      'I can say what I am going to do and when.',
      'I can ask others about their plans and understand the answers.',
    ],
    functions: ['talking about plans', 'asking about plans', 'giving reasons for plans'],
    structures: ['going-to'],
    lexicalFields: ['holiday and summer activities', 'future time expressions', 'places to visit'],
    items: 69,
    pron: ['"going to" reduced to /ˈɡəʊɪŋ tə/ in connected speech (listening)', 'sentence stress in plans'],
    skins: ['travel', 'music', 'football', 'art'],
  },
  {
    title: 'Body and Health',
    theme: 'Feeling ill and giving advice',
    hook: "Theo has been playing games all night and feels awful. Use your best advice to get him back on his feet.",
    release: 'A short advice message or voice note to a friend who feels ill',
    canDo: [
      'I can say what is wrong with me and understand simple health advice.',
      'I can give advice to a friend.',
    ],
    functions: ['describing symptoms', 'giving advice', 'talking about health habits'],
    structures: ['should', { id: 'too-enough' }],
    lexicalFields: ['parts of the body', 'common illnesses and symptoms', 'sleep, food and exercise'],
    items: 69,
    pron: ['stress in body-part and symptom words (stomach, headache)', 'should / shouldn\'t: the weak vowel'],
    skins: ['fitness', 'gaming', 'food', 'football'],
  },
  {
    title: 'House Rules',
    theme: 'Rules at home, at school and in games',
    hook: 'Mia has to write the rules for the school gaming club. Can you help her make rules everyone will follow?',
    release: 'A short guide to the rules of a place or game I know well',
    canDo: [
      'I can say what you must and must not do in a place or game.',
      'I can say what I have to do at home or at school.',
    ],
    functions: ['talking about rules', 'saying what is necessary', 'prohibiting'],
    structures: ['must-mustnt', { id: 'have-to' }],
    lexicalFields: ['school and club rules', 'safety signs', 'household duties', 'games and sports rules'],
    items: 69,
    pron: ['"mustn\'t" - silent t and final cluster', 'sentence stress in rules'],
    skins: ['gaming', 'football', 'tech', 'fitness'],
  },
  {
    title: 'Food Cultures',
    theme: 'What people eat around the world',
    hook: "Vee's friend is hosting an international dinner and needs a menu. How much of everything do you need for ten people?",
    release: 'A short recipe video script and recording of a dish I know',
    canDo: [
      'I can talk about how much or how many of something there is.',
      'I can follow and give a simple recipe.',
    ],
    functions: ['talking about quantity', 'giving instructions for a recipe', 'comparing food customs'],
    structures: ['quantifiers-much-many'],
    lexicalFields: ['ingredients and quantities', 'cooking verbs', 'meals and customs around the world'],
    items: 69,
    pron: ['stress in food words (chocolate, vegetable)', 'linking in "a lot of"'],
    skins: ['food', 'travel', 'fitness', 'film'],
  },
  {
    title: 'Getting Around',
    theme: 'Transport and city life',
    hook: "Ava is new in the city and has two hours to get across it. Plan her route before she misses her interview.",
    release: 'A route guide for a visitor, spoken and as a simple map',
    canDo: [
      'I can explain how to get from one place to another and why I go there.',
      'I can understand simple travel announcements and instructions.',
    ],
    functions: ['giving travel directions', 'explaining purpose', 'buying a ticket'],
    structures: ['infinitive-purpose', { id: 'prepositions-movement' }],
    lexicalFields: ['transport and tickets', 'city places and buildings', 'travel announcements'],
    items: 69,
    pron: ['weak "to" /tə/ in "I go there to study"', 'number and time stress in announcements'],
    skins: ['travel', 'tech', 'music', 'nature'],
  },
  {
    title: "Tomorrow's World",
    theme: 'Predictions and quick decisions',
    hook: "A time capsule from 2010 predicted what 2030 would be like. Check its predictions and write your own for the next capsule.",
    release: 'A one-minute predictions podcast clip: my world in 2040',
    canDo: [
      'I can make simple predictions and say what I think will happen.',
      'I can make quick decisions and offer to help.',
    ],
    functions: ['making predictions', 'making offers and quick decisions', 'agreeing and disagreeing simply'],
    structures: ['will-decisions-predictions'],
    lexicalFields: ['technology and the future', 'jobs of the future', 'weather and environment'],
    items: 69,
    pron: ["contracted 'll /l/ ('I'll, she'll)", 'won\'t vs want (vowel length)'],
    skins: ['science', 'tech', 'gaming', 'nature'],
  },
  {
    title: 'Storm Warning',
    theme: 'Weather and an adventure that went wrong',
    hook: 'Four friends were camping when the storm hit. Each of them remembers a different version of that night.',
    release: 'An eyewitness account: what was happening when the storm started',
    canDo: [
      'I can say what was happening at a moment in the past.',
      'I can link two short sentences with so and because.',
    ],
    functions: ['describing a scene in the past', 'giving reasons and results', 'telling a short story'],
    structures: ['past-continuous', { id: 'linking-so-because' }],
    lexicalFields: ['weather and nature', 'camping and outdoor equipment', 'emergencies and feelings'],
    items: 69,
    pron: ['was / were /wəz/ /wə/ in connected speech', 'stress in two-syllable weather words'],
    skins: ['nature', 'film', 'gaming', 'travel'],
  },
  {
    title: 'Dream Jobs',
    theme: 'Jobs, skills and how people do things',
    hook: 'Career Day is coming and Theo has no idea what he wants to be. Interview three people and help him decide.',
    release: 'A short job-interview role-play: me as the candidate',
    canDo: [
      'I can describe a job and the skills it needs.',
      'I can say how well someone does something.',
    ],
    functions: ['talking about jobs', 'describing how things are done', 'answering simple interview questions'],
    structures: ['adverbs-manner'],
    lexicalFields: ['jobs and workplaces', 'personal qualities', 'skills and abilities'],
    items: 69,
    pron: ['-ly adverb stress (carefully, quickly)', 'rising tone for yes/no questions'],
    skins: ['business', 'tech', 'fitness', 'art', 'animals'],
  },
  {
    title: 'Event Planners',
    theme: 'Organising a school festival',
    hook: "The school festival is in two weeks and the committee has no ideas. Make suggestions, take decisions and save the day.",
    release: 'A festival invitation plus a one-minute pitch for the committee',
    canDo: [
      'I can make, accept and refuse suggestions politely.',
      'I can write a short invitation with the key information.',
    ],
    functions: ['making suggestions', 'accepting and refusing politely', 'writing an invitation'],
    structures: ['suggestions'],
    lexicalFields: ['festivals and events', 'dates and times', 'food, music and decorations'],
    items: 69,
    pron: ["intonation in polite suggestions (Let's go! / Shall we ...?)", 'dates: ordinal numbers stress'],
    skins: ['music', 'food', 'art', 'fashion', 'football'],
    notes: 'Level check Season: E8 includes the A2 level check (separate from XP).',
  },
];
