// B1 (16 Seasons, 128 sessions, ~2,750 cumulative items). CEFR B1: copes with most situations while travelling; produces
// simple connected text on familiar topics; describes experiences, events, hopes and ambitions; gives reasons and opinions.
// Method shifts to task-first (Mission before the rule). Mediation starts: every Season has one task. Supports: first words
// of a frame, hints on request. Input texts ~150-300 words [U]. Presentations of the present perfect are split by sub-use.
import type { RawSeason } from '../authoring';

export const B1_SEASONS: RawSeason[] = [
  {
    title: 'Have You Ever...?',
    theme: 'Experiences and bucket lists',
    hook: "Vee dares the group to complete a bucket list in one term. Who has already done the most?",
    release: 'My bucket list: three things I have done and three I want to do',
    canDo: [
      'I can talk about experiences I have had or never had.',
      'I can ask others about their experiences and respond with interest.',
    ],
    functions: ['talking about life experiences', 'asking follow-up questions', 'showing interest and surprise'],
    structures: ['present-perfect-experience'],
    lexicalFields: ['adventure and activities', 'feelings about experiences', 'places and countries visited'],
    items: 75,
    pron: ["contracted 'have' /əv/ and 'been' /bɪn/ vs /biːn/", 'intonation of surprise'],
    mediation: 'Relay to a friend, in simple English, the main points of a short article about an unusual experience.',
    skins: ['travel', 'gaming', 'music', 'fitness'],
  },
  {
    title: 'Then and Now',
    theme: 'Memories and how things have changed',
    hook: "Theo finds his old phone with photos from five years ago. Compare then and now - and spot what has changed.",
    release: 'A "then and now" photo story: how my life or my town has changed',
    canDo: [
      'I can describe past habits and states and compare them with now.',
      'I can understand a short text about how life has changed.',
    ],
    functions: ['talking about past habits', 'comparing past and present', 'reminiscing'],
    structures: ['used-to'],
    lexicalFields: ['childhood and school memories', 'technology then and now', 'town and lifestyle changes'],
    items: 75,
    pron: ['"used to" /juːst tə/ in connected speech', 'sentence stress in contrasts'],
    mediation: 'Summarise for a younger cousin a short text about how a daily habit has changed.',
    skins: ['tech', 'music', 'film', 'food'],
  },
  {
    title: 'Still Going',
    theme: 'Things that began in the past and continue now',
    hook: "Ava has kept the same hobby for six years and Mia has never kept anything for six weeks. Who is telling the truth?",
    release: 'An interview with a friend about a long-term hobby or friendship, recorded',
    canDo: [
      'I can say how long something has been true.',
      'I can ask and answer questions about duration.',
    ],
    functions: ['talking about duration', 'interviewing someone', 'giving a short personal profile'],
    structures: ['present-perfect-for-since'],
    lexicalFields: ['hobbies, clubs and habits', 'time periods and dates', 'relationships and routines'],
    items: 75,
    pron: ['for /fə/ and since /sɪns/ in connected speech', 'question intonation in interviews'],
    mediation: "Pass on to a friend, in plain English, what a person said in a short interview.",
    skins: ['football', 'gaming', 'art', 'animals', 'music'],
  },
  {
    title: 'Breaking News',
    theme: 'Recent events and news stories',
    hook: "A rumour about the school is spreading through Ava's group chat. Is it true? Choose the right tense and report the news without making it worse.",
    release: 'A 60-second audio news bulletin',
    canDo: [
      'I can report recent news and say when something happened.',
      'I can choose between the present perfect and the past simple for a news story.',
    ],
    functions: ['reporting news', 'giving details of a past event', 'announcing results'],
    structures: ['present-perfect-vs-past-simple'],
    lexicalFields: ['news and media', 'events and results', 'accidents and surprises'],
    items: 75,
    pron: ['news-reader rhythm and sentence stress', 'past participle forms (said, been, seen)'],
    mediation: 'Turn a short written news item into a spoken summary for someone who has not read it.',
    skins: ['social', 'football', 'film', 'science'],
  },
  {
    title: 'If This, Then That',
    theme: 'Rules, systems and game design',
    hook: "Mia is designing a board game and the rules keep breaking. Fix them with the right if-sentences.",
    release: 'The rules of a game I designed, explained step by step',
    canDo: [
      'I can say what always happens and what will happen if something happens.',
      'I can explain rules and instructions clearly.',
    ],
    functions: ['explaining rules', 'predicting consequences', 'giving warnings and instructions'],
    structures: ['zero-first-conditional'],
    lexicalFields: ['games and rules', 'cause and effect', 'instructions and warnings'],
    items: 75,
    pron: ['intonation and pause after the if-clause', 'contracted will /l/'],
    mediation: 'Explain the rules of a game described in a short text to someone who has never played it.',
    skins: ['gaming', 'tech', 'football', 'science'],
  },
  {
    title: 'What If...?',
    theme: 'Imaginary situations and dilemmas',
    hook: "Vee asks one impossible question each morning. Today: what would you do if you could be invisible for a day?",
    release: 'A spoken debate: three "what if" dilemmas and my answers',
    canDo: [
      'I can talk about imaginary situations and what I would do.',
      'I can give reasons for my choices and respond to others.',
    ],
    functions: ['talking about imaginary situations', 'giving opinions', 'agreeing and disagreeing'],
    structures: ['second-conditional'],
    lexicalFields: ['dilemmas and choices', 'superpowers and fantasy', 'money, fame and school life'],
    items: 75,
    pron: ["'d /d/ (I'd, she'd) vs 'would'", 'stress for contrast'],
    mediation: 'Summarise two different answers to a dilemma for a third person.',
    skins: ['film', 'gaming', 'anime', 'science'],
  },
  {
    title: 'Made in the World',
    theme: 'How things are made and where they come from',
    hook: "Theo wants to know where his sneakers, his phone and his lunch really come from. Trace one product from start to finish.",
    release: "A short 'how it is made' explainer clip",
    canDo: [
      'I can describe how something is made or done without saying who did it.',
      'I can understand a short factual text about a process.',
    ],
    functions: ['describing a process', 'giving factual information', 'sequencing steps'],
    structures: ['passive-simple'],
    lexicalFields: ['manufacturing and materials', 'food production', 'inventions and discoveries'],
    items: 75,
    pron: ['past participle endings /t/ /d/ /ɪd/', 'stress in compound nouns'],
    mediation: 'Relay the steps of a process from a diagram or text to a friend who is trying to do it.',
    skins: ['fashion', 'food', 'tech', 'science'],
  },
  {
    title: "Who's Who",
    theme: 'Describing people, places and things precisely',
    hook: "Mia's guessing game goes wrong when two people turn out to have the same description. Add details until only one fits.",
    release: 'A "guess who / what" game I wrote and played with a partner',
    canDo: [
      'I can add detail to a description using who, which, that and where.',
      'I can ask for and give clarification.',
    ],
    functions: ['describing and defining', 'adding detail', 'clarifying'],
    structures: ['defining-relative-clauses'],
    lexicalFields: ['people and personalities', 'places and objects', 'definitions and descriptions'],
    items: 75,
    pron: ['pausing and chunking before relative pronouns', 'stress on the new information'],
    mediation: 'Explain what an unfamiliar object or person is, using a short description from a text.',
    skins: ['film', 'music', 'animals', 'anime'],
  },
  {
    title: 'Case Closed',
    theme: 'Mystery and deduction',
    hook: "A trophy has disappeared from the school hall and Vee asks you to lead the investigation with Ava and Theo. Gather the clues and work out what must have happened, or might have.",
    release: 'A detective briefing: my theory of the case with evidence',
    canDo: [
      'I can say how certain I am about something using must, might and can\'t.',
      'I can explain my reasoning using evidence.',
    ],
    functions: ['speculating', 'expressing certainty and doubt', 'explaining a theory'],
    structures: ['modals-deduction'],
    lexicalFields: ['crime and mystery', 'clues and evidence', 'suspects and alibis'],
    items: 75,
    pron: ['modal verbs: strong vs weak forms', 'intonation of doubt'],
    mediation: 'Summarise a witness account for the detective in your own words.',
    skins: ['film', 'gaming', 'anime', 'science'],
  },
  {
    title: 'Plans and Promises',
    theme: 'Arrangements and commitments',
    hook: "Vee's class trip is on but nobody has booked anything. Make arrangements with Mia and Theo and promise what you will do.",
    release: 'A trip plan with arrangements and promises, as an invitation and short call',
    canDo: [
      'I can talk about arrangements I have made.',
      'I can make promises and simple predictions about the future.',
    ],
    functions: ['arranging to meet', 'making promises', 'predicting'],
    structures: [
      { id: 'present-continuous-future', use: 'future arrangements' },
      { id: 'will-promises-predictions', use: 'promises and predictions' },
    ],
    lexicalFields: ['travel and booking', 'diaries and appointments', 'promises and commitments'],
    items: 75,
    pron: ['stress on time expressions', "contracted will in promises (I'll be there)"],
    mediation: 'Pass on the key details of a booking message to a friend who must act on it.',
    skins: ['travel', 'music', 'football', 'food'],
    notes: 'Future arrangements are taught only after "now" use is automatic (A1) and going to is secure (A2).',
  },
  {
    title: 'Learning Machines',
    theme: 'Technology, AI and how we learn',
    hook: "Vee's class is testing an AI tutor. Is it better to enjoy learning with it or to avoid using it too much? Decide.",
    release: 'A short review of a learning tool, with a recommendation',
    canDo: [
      'I can give my opinion about technology and say what I enjoy, avoid or hope to do.',
      'I can write a short review with reasons.',
    ],
    functions: ['giving opinions', 'recommending', 'comparing options'],
    structures: ['gerund-infinitive'],
    lexicalFields: ['technology and AI', 'learning and study habits', 'opinion adjectives'],
    items: 75,
    pron: ['-ing and to + verb: weak forms', 'stress and intonation in opinions'],
    mediation: 'Explain the pros and cons given in a short text to a classmate who must decide.',
    skins: ['tech', 'gaming', 'science', 'social'],
  },
  {
    title: 'Word on the Street',
    theme: 'Reporting what people said',
    hook: "A message went through Ava, Theo, Mia and three others and arrived completely different. Trace it back and find who changed the story.",
    release: 'A story told through other people\'s words: what they said and what I replied',
    canDo: [
      'I can report what someone told me or said to me.',
      'I can change pronouns and time words when I report.',
    ],
    functions: ['reporting speech', 'passing on messages', 'clarifying what was said'],
    structures: ['reported-statements'],
    lexicalFields: ['communication verbs (say, tell, ask)', 'messages and social media', 'gossip and rumours'],
    items: 75,
    pron: ['reporting verbs: said /sɛd/, told /təʊld/', 'sentence rhythm in reported clauses'],
    mediation: 'Pass on a voicemail message accurately and politely to the person it is for.',
    skins: ['social', 'film', 'music', 'gaming'],
  },
  {
    title: 'Before the Storm',
    theme: 'Narrative writing: what had already happened',
    hook: "Ava, Theo, Mia and Vee arrive at a cabin and find the table set for dinner. Someone had been there. Work out the story behind it.",
    release: 'A short story of 150-200 words with a twist, written and read aloud',
    canDo: [
      'I can tell a story that includes what had happened earlier.',
      'I can organise a story with linkers (after, before, when).',
    ],
    functions: ['narrating', 'sequencing past events', 'creating suspense'],
    structures: ['past-perfect'],
    lexicalFields: ['storytelling and suspense', 'houses, forests and weather', 'emotions in narratives'],
    items: 75,
    pron: ["'d /d/ for had in connected speech", 'dramatic pausing and stress'],
    mediation: 'Summarise a short story for someone who missed it.',
    skins: ['film', 'anime', 'gaming', 'nature'],
    notes: 'Past perfect only after past simple and past continuous are secure; confirm with the English Grammar Profile.',
  },
  {
    title: 'Wish List',
    theme: 'Wishes, regrets and imagining change',
    hook: "Ava keeps a wish list she is afraid to show anyone. Can you encourage her to share it?",
    release: 'A short blog post: three things I wish were different and why',
    canDo: [
      'I can say what I wish were different about my life or world.',
      'I can express feelings about things I cannot change.',
    ],
    functions: ['expressing wishes', 'expressing feelings', 'giving encouragement'],
    structures: ['wish-past-simple'],
    lexicalFields: ['school, home and friendships', 'feelings and personal growth', 'society and environment'],
    items: 75,
    pron: ['wish /wɪʃ/ - final /ʃ/', 'warm, supportive intonation'],
    mediation: 'Relay a friend\'s wish to a teacher in a polite and clear way.',
    skins: ['music', 'art', 'social', 'nature'],
  },
  {
    title: 'Study Abroad',
    theme: 'Rules, expectations and cultures',
    hook: "An exchange student arrives next week and Vee asks Mia and Theo to prepare the guide. Write the one that will save their first month.",
    release: 'An advice email for a new exchange student',
    canDo: [
      'I can explain what is necessary and what is not, and give advice to a visitor.',
      'I can write an informal email and use linkers to contrast ideas.',
    ],
    functions: ['explaining rules and customs', 'giving advice', 'contrasting ideas'],
    structures: ['obligation-contrast', { id: 'linking-although' }],
    lexicalFields: ['school life abroad', 'customs and etiquette', 'accommodation and daily life'],
    items: 75,
    pron: ["don't have to vs mustn't: stress and vowel", 'linking words: although /ɔːlˈðəʊ/'],
    mediation: 'Explain the school rules in a leaflet to a new student who does not read English well.',
    skins: ['travel', 'food', 'fashion', 'football'],
  },
  {
    title: 'Teen Talk Show',
    theme: 'Hosting a show: everything at B1',
    hook: "Vee has given you a late-night slot. Interview your guests, check facts and keep the audience on your side.",
    release: 'A five-minute talk-show episode recorded with a guest',
    canDo: [
      'I can keep a conversation going, check information and show interest.',
      'I can use common phrasal verbs naturally in everyday talk.',
    ],
    functions: ['hosting and interviewing', 'checking information', 'agreeing and disagreeing'],
    structures: ['question-tags', { id: 'phrasal-verbs-separable' }],
    lexicalFields: ['entertainment and media', 'everyday phrasal verbs', 'interview language'],
    items: 75,
    pron: ['rising and falling tags (confirmation vs real questions)', 'stress in phrasal verbs'],
    mediation: 'Introduce a guest by relaying key facts from a profile, and summarise their answers for the audience.',
    skins: ['film', 'music', 'social', 'gaming', 'football'],
    notes: 'Level check Season: E8 includes the B1 level check (separate from XP).',
  },
];
