// B2 (16 Seasons, 128 sessions, ~4,050 cumulative items). CEFR B2: understands the main ideas of complex text; interacts with
// fluency and spontaneity; produces clear, detailed text and explains a viewpoint with advantages and disadvantages.
// Student-led tasks, opinion defence, summarising and mediation every Season. Supports: none by default (optional).
// Input texts ~300-500 words [U]. Topics are school-safe: no dating/sexuality, alcohol, drugs, gambling, graphic violence, partisan politics.
import type { RawSeason } from '../authoring';

export const B2_SEASONS: RawSeason[] = [
  {
    title: 'Been There, Doing That',
    theme: 'Long-term projects and ongoing effort',
    hook: "Everyone in Vee's class has been working on a personal project all term. Whose has actually moved forward?",
    release: 'A progress report on a project I have been working on, spoken and written',
    canDo: [
      'I can describe an activity that has been going on and its present results.',
      'I can give a clear, detailed account of progress to an audience.',
    ],
    functions: ['describing ongoing activity', 'reporting progress', 'explaining causes of results'],
    structures: ['present-perfect-continuous'],
    lexicalFields: ['projects and goals', 'effort and progress', 'study and sport'],
    items: 80,
    pron: ["'ve been /əv bɪn/ in connected speech", 'sentence stress in progress reports'],
    mediation: 'Summarise for the group the progress described in a long message from a team member.',
    skins: ['fitness', 'tech', 'music', 'art', 'gaming'],
  },
  {
    title: 'What Might Have Been',
    theme: 'Regrets and alternative histories',
    hook: "Theo failed his driving test by one point. Explore the five moments that might have changed it - and what he should have done.",
    release: 'A short reflective essay or talk: a decision I would change and why',
    canDo: [
      'I can talk about past situations and how they could have been different.',
      'I can express regret, relief and criticism appropriately.',
    ],
    functions: ['expressing regret', 'speculating about the past', 'criticising tactfully'],
    structures: ['third-conditional', { id: 'wish-past-perfect' }],
    lexicalFields: ['decisions and consequences', 'exams, sports and relationships', 'emotions about the past'],
    items: 80,
    pron: ["have /əv/ in connected speech (would've, could've)", 'emphasis for regret'],
    mediation: 'Relay a friend\'s regretful story to a teacher while keeping the key reasons.',
    skins: ['film', 'football', 'gaming', 'music'],
  },
  {
    title: 'Passive Power',
    theme: 'Systems, processes and who is responsible',
    hook: "A school report says 'mistakes were made' - but nobody says by whom. Ava is investigating for the school paper; help her see how the passive hides and reveals people.",
    release: 'A report on how a system works or who is responsible for a problem',
    canDo: [
      'I can describe processes and events when the agent is unknown or unimportant.',
      'I can write a formal factual report.',
    ],
    functions: ['describing processes', 'reporting facts', 'avoiding blame'],
    structures: ['passive-extended'],
    lexicalFields: ['systems and institutions', 'science and technology', 'news and public events'],
    items: 80,
    pron: ['weak forms of auxiliary verbs (been, being)', 'stress in long noun phrases'],
    mediation: 'Summarise a technical process from a text for someone with no background.',
    skins: ['tech', 'science', 'business', 'nature'],
  },
  {
    title: 'Reporting It',
    theme: 'Reporting conversations and interviews',
    hook: "Mia's interview notes are mixed up. Work out who asked what and who answered - and report it so the truth survives.",
    release: 'A written report of an interview I conducted',
    canDo: [
      'I can report questions, requests and commands accurately.',
      'I can choose suitable reporting verbs.',
    ],
    functions: ['reporting questions and requests', 'summarising an interview', 'conveying attitude with reporting verbs'],
    structures: ['reported-questions-commands'],
    lexicalFields: ['interviews and journalism', 'reporting verbs', 'attitudes and opinions'],
    items: 80,
    pron: ['stress and intonation in indirect questions', 'rhythm in long reported clauses'],
    mediation: 'Report a long conversation to someone who was not there, selecting the key points.',
    skins: ['social', 'film', 'music', 'business'],
  },
  {
    title: 'Who Is He Anyway?',
    theme: 'Biographies and profile writing',
    hook: "Mia must write a profile of a mysterious school donor for the yearbook. Add the extra details that tell the real story.",
    release: 'A profile of an interesting person with extra information',
    canDo: [
      'I can add non-essential information to a sentence in a natural way.',
      'I can write a lively, detailed profile.',
    ],
    functions: ['describing people', 'adding extra information', 'writing profiles'],
    structures: ['non-defining-relatives'],
    lexicalFields: ['people and achievements', 'careers and biography', 'places and institutions'],
    items: 80,
    pron: ['commas as pauses before who/which', 'falling tone on extra information'],
    mediation: 'Condense a long biography into a short introduction for a speaker.',
    skins: ['music', 'football', 'science', 'film', 'business'],
  },
  {
    title: 'Could Have, Should Have',
    theme: 'Blame, advice and criticism',
    hook: "Ava forgot to back up her project and lost everything. What should she have done - and what could her team have done for her?",
    release: 'A diplomatic feedback message: what could have been done differently',
    canDo: [
      'I can speculate about what happened and give polite criticism.',
      'I can use modals to express different degrees of possibility about the past.',
    ],
    functions: ['speculating about the past', 'criticising politely', 'taking responsibility'],
    structures: ['perfect-modals'],
    lexicalFields: ['mistakes and consequences', 'teamwork and projects', 'tech problems'],
    items: 80,
    pron: ['perfect modals: weak "have" /əv/', 'intonation for politeness'],
    mediation: 'Give feedback on a friend\'s plan to a teacher in a balanced, tactful way.',
    skins: ['tech', 'gaming', 'football', 'business'],
  },
  {
    title: 'The Future Is...',
    theme: 'Predicting and planning the next decade',
    hook: "Vee's time-capsule letter from 2025 asks: what will you be doing in 2035? Answer it - and prove it is realistic.",
    release: 'A letter to my future self (written) and a short vision talk (spoken)',
    canDo: [
      'I can say what will be happening or will be completed at a future time.',
      'I can write a clear, detailed text about my future plans.',
    ],
    functions: ['predicting', 'planning', 'talking about future achievements'],
    structures: ['future-continuous-perfect'],
    lexicalFields: ['future technology and society', 'careers and ambitions', 'time expressions for the future'],
    items: 80,
    pron: ['"will have" /wɪl əv/ in connected speech', 'rhythm in long future clauses'],
    mediation: 'Summarise two different predictions for the same topic from two sources.',
    skins: ['science', 'tech', 'nature', 'business'],
  },
  {
    title: 'Opinions That Matter',
    theme: 'Arguing a point of view',
    hook: "Vee runs a weekly debate club. This week's motion: 'School should start later.' Convince the room - politely.",
    release: 'A structured spoken argument (two minutes) and a written paragraph version',
    canDo: [
      'I can state and support an opinion with reasons and examples.',
      'I can soften or strengthen what I say to suit the audience.',
    ],
    functions: ['arguing a case', 'conceding a point', 'hedging and emphasising'],
    structures: ['hedging-stance', { id: 'linking-however-despite' }],
    lexicalFields: ['education and society', 'media and technology debates', 'opinion and argument language'],
    items: 80,
    pron: ['contrastive stress in arguments', 'intonation for conceding and challenging'],
    mediation: 'Summarise both sides of a debate fairly for a judge who missed it.',
    skins: ['social', 'tech', 'fitness', 'music', 'business'],
  },
  {
    title: 'Get It Done',
    theme: 'Services, problems and polite complaints',
    hook: "Ava's phone screen is cracked, her laptop is slow and her bike is stolen. She needs help - and the shops are not making it easy.",
    release: 'A role-play: making a complaint and asking for a solution',
    canDo: [
      'I can say that I arranged for someone else to do something.',
      'I can ask and answer polite indirect questions.',
    ],
    functions: ['making complaints', 'asking indirectly', 'arranging services'],
    structures: ['causative-have-get', { id: 'embedded-questions' }],
    lexicalFields: ['repairs, services and shopping', 'complaints and refunds', 'customer service language'],
    items: 80,
    pron: ['politeness intonation in indirect questions', 'linking in "have it done"'],
    mediation: 'Help a younger sibling understand a warranty or return policy.',
    skins: ['tech', 'fashion', 'business', 'travel'],
  },
  {
    title: 'Unless You Do',
    theme: 'Conditions, deals and negotiation',
    hook: "Ava and Theo want the same band room. Negotiate a deal that works for both - with conditions neither can break.",
    release: 'A negotiation role-play and the written agreement that follows',
    canDo: [
      'I can state conditions and negotiate an agreement.',
      'I can use a range of conditional structures to be precise.',
    ],
    functions: ['negotiating', 'setting conditions', 'making deals and compromises'],
    structures: ['conditionals-extended'],
    lexicalFields: ['negotiation and agreements', 'rules and fairness', 'money and time'],
    items: 80,
    pron: ['stress on key conditions', 'intonation in polite bargaining'],
    mediation: 'Mediate between two people who have different needs by suggesting a compromise.',
    skins: ['business', 'music', 'gaming', 'football'],
  },
  {
    title: 'Remember That!',
    theme: 'Memory, habits and meaning-changing verbs',
    hook: "Theo remembers locking the door. Mia remembers to lock the door. Who is right, and why does the difference matter?",
    release: 'A short talk or essay about memory and how it shapes our habits',
    canDo: [
      'I can use common verbs followed by -ing or to and understand the change in meaning.',
      'I can make accurate choices about articles and generic reference in a formal text.',
    ],
    functions: ['explaining differences in meaning', 'talking about memory and habit', 'writing accurately'],
    structures: ['gerund-infinitive-meaning', { id: 'articles-nuance' }],
    lexicalFields: ['memory and psychology', 'habits and self-improvement', 'language and meaning'],
    items: 80,
    pron: ['verb + to: weak "to" /tə/', 'stress for contrast in near-identical pairs'],
    mediation: 'Explain a short scientific text on memory to a friend in simpler words.',
    skins: ['science', 'fitness', 'music', 'tech'],
  },
  {
    title: 'The Big Picture',
    theme: 'Emphasis and focus in speaking and writing',
    hook: "Theo says it was not the goal that won the match - it was the pass before it. Work out what really matters in the story.",
    release: 'A short speech or article using emphasis to make one clear point',
    canDo: [
      'I can give emphasis to the part of a sentence that matters most.',
      'I can structure a talk to guide the listener.',
    ],
    functions: ['emphasising', 'structuring a talk', 'contrasting ideas'],
    structures: ['cleft-sentences'],
    lexicalFields: ['sport and teamwork', 'argument and persuasion', 'media and speeches'],
    items: 80,
    pron: ['nuclear stress and focus', 'pause and emphasis in speeches'],
    mediation: 'Pick out the main point of a long speech and re-express it in two sentences.',
    skins: ['football', 'film', 'social', 'music'],
  },
  {
    title: 'Cut the Words',
    theme: 'Concise, elegant writing',
    hook: "Vee has set a challenge: write a news story in half the words without losing anything important. How short can you go?",
    release: 'A shortened version of my own text, showing what I cut and why',
    canDo: [
      'I can write more concisely using participle clauses and ellipsis.',
      'I can edit my own text for clarity and style.',
    ],
    functions: ['editing and condensing', 'writing concisely', 'combining ideas efficiently'],
    structures: ['participle-clauses', { id: 'ellipsis' }],
    lexicalFields: ['journalism and writing', 'process language', 'academic style'],
    items: 80,
    pron: ['intonation in long compressed sentences', 'stress on key content words'],
    mediation: 'Condense a long email into a short summary that keeps all key points.',
    skins: ['social', 'film', 'science', 'business'],
  },
  {
    title: 'As Much As',
    theme: 'Comparing, measuring and describing change',
    hook: "Mia is choosing between two cities, two schools and two phones - but which is really better? Compare precisely, with numbers and evidence.",
    release: 'A comparison presentation with a chart and spoken commentary',
    canDo: [
      'I can compare things precisely and describe how they change together.',
      'I can describe a chart and draw a clear conclusion.',
    ],
    functions: ['comparing in detail', 'describing change and trends', 'drawing conclusions'],
    structures: ['comparison-extended'],
    lexicalFields: ['data, charts and trends', 'cities and lifestyle', 'technology and cost'],
    items: 80,
    pron: ['stress and rhythm in comparison pairs', 'intonation in lists and numbers'],
    mediation: 'Explain a chart or table from a text to a friend who cannot see it.',
    skins: ['business', 'tech', 'travel', 'science', 'fitness'],
  },
  {
    title: 'Say It Clearly',
    theme: 'Mediation: relaying, summarising and facilitating',
    hook: "Two exchange students speak English but not each other's culture. Vee asks you and Ava to be the bridge: help them understand and decide together.",
    release: 'A live mediation: summarising and relaying between two speakers, plus a written summary',
    canDo: [
      'I can summarise and relay information from one source or speaker to another.',
      'I can help others understand each other by explaining and checking.',
    ],
    functions: ['summarising', 'relaying information', 'facilitating discussion'],
    structures: ['reporting-verb-patterns'],
    lexicalFields: ['intercultural communication', 'meetings and teamwork', 'reporting and summarising'],
    items: 80,
    pron: ['clear chunking for relayed information', 'neutral and polite tone'],
    mediation: 'Run a mediation between two speakers with different views and produce a neutral summary.',
    skins: ['travel', 'business', 'social', 'music'],
  },
  {
    title: 'Debate League',
    theme: 'Putting B2 together: argument, cohesion and delivery',
    hook: "The semi-finals of Vee's debate league need a speaker who can argue either side. Show you can do both.",
    release: 'A full debate speech (three minutes) and a written case summary',
    canDo: [
      'I can present a clear, well-structured argument and respond to questions.',
      'I can link ideas into a cohesive text using a range of devices.',
    ],
    functions: ['debating', 'structuring an argument', 'responding to challenge'],
    structures: ['cohesion-devices'],
    lexicalFields: ['debate language', 'society and ethics', 'cohesion and signposting'],
    items: 80,
    pron: ['stress and pace in a speech', 'signposting intonation'],
    mediation: 'Chair a short discussion: summarise each speaker and invite responses.',
    skins: ['social', 'tech', 'business', 'nature', 'film'],
    notes: 'Level check Season: E8 includes the B2 level check (separate from XP).',
  },
];
