// C1 (16 Seasons, 128 sessions, ~5,300 cumulative items). CEFR C1: understands demanding, longer texts and implicit meaning;
// expresses ideas fluently and spontaneously; uses language flexibly for social, academic and professional purposes;
// produces clear, well-structured, detailed text on complex subjects. Teen-appropriate (15-18): school-safe topics.
// Shape: supports off; Language Lab (E3) notices register, collocation and stance in authentic text; E4 is a seminar, pitch or
// interview; mediation every Season; extensive reading/listening target for the Daily 10. Input texts ~500-800 words [U].
// Many C1 grammar placements and the pragmatic items (rhetoric, irony) are 'unverified' in structureLevels.ts: check the EGP.
import type { RawSeason } from '../authoring';

export const C1_SEASONS: RawSeason[] = [
  {
    title: 'Rarely Do We...',
    theme: 'Powerful openings and emphatic style',
    hook: "Vee challenges everyone to open a speech so strongly that nobody looks at their phone. Which opening works - and why?",
    release: 'A speech opening (90 seconds) using emphatic inversion, and a reflection on its effect',
    canDo: [
      'I can use inversion and fronting to add emphasis in speech and writing, and judge when it is too much.',
      'I can analyse how a speaker uses structure to persuade.',
    ],
    functions: ['emphasising', 'persuading', 'analysing style'],
    structures: ['inversion-negative'],
    lexicalFields: ['rhetoric and public speaking', 'rare and notable events', 'formal vocabulary'],
    items: 84,
    pron: ['emphatic stress and pause after the fronted element', 'pace and breath in a speech'],
    mediation: 'Condense a long speech into three key points for someone preparing a response.',
    skins: ['social', 'film', 'music', 'business'],
  },
  {
    title: 'Had I Known',
    theme: 'Hypothetical reasoning and regret in formal register',
    hook: "A mock trial at school has a verdict that hinges on one 'if'. Argue what would have happened - in the formal register a court expects.",
    release: 'A formal written statement and a spoken defence for a mock-trial case',
    canDo: [
      'I can speculate about past and present possibilities using inverted and mixed conditionals.',
      'I can adapt register for a formal audience.',
    ],
    functions: ['hypothesising', 'arguing formally', 'speculating about causes'],
    structures: ['inverted-conditionals', { id: 'mixed-conditionals' }],
    lexicalFields: ['law, fairness and justice', 'formal reasoning', 'causes and consequences'],
    items: 84,
    pron: ['intonation of formal hypothesising', 'contrastive stress in conditionals'],
    mediation: 'Explain the key arguments of both sides of a case to a neutral listener.',
    skins: ['film', 'business', 'social', 'science'],
  },
  {
    title: 'They Say...',
    theme: 'Reporting claims and evaluating sources',
    hook: "It is said that a famous image was never real. Evaluate the claim, the sources and the way the story is told.",
    release: 'A media-literacy analysis: how a claim is reported, and what I would check',
    canDo: [
      'I can report claims impersonally and evaluate how reliable a source is.',
      'I can write a clear analysis of a news story.',
    ],
    functions: ['reporting claims', 'evaluating sources', 'distancing from a claim'],
    structures: ['passive-reporting'],
    lexicalFields: ['media and misinformation', 'research and evidence', 'trust and credibility'],
    items: 84,
    pron: ['stress and intonation that signal doubt', 'rhythm of long formal sentences'],
    mediation: 'Summarise a complex article for a friend and flag which claims are weak.',
    skins: ['social', 'tech', 'film', 'science'],
  },
  {
    title: 'I Suggest That...',
    theme: 'Formal proposals and recommendations',
    hook: "The student council needs a formal proposal to change one school rule. Draft it so well that nobody can say no.",
    release: 'A formal proposal letter or report with recommendations',
    canDo: [
      'I can make formal recommendations and state preferences precisely.',
      'I can write a proposal with a clear structure and suitable tone.',
    ],
    functions: ['making formal proposals', 'recommending', 'stating preferences'],
    structures: ['subjunctive-mandative'],
    lexicalFields: ['school and community change', 'rules and policy', 'formal collocations'],
    items: 84,
    pron: ['formal intonation and pace', 'avoiding reduced forms in formal speech'],
    mediation: 'Turn a student\'s informal complaint into a polite formal request.',
    skins: ['business', 'social', 'nature', 'tech'],
  },
  {
    title: 'In Other Words',
    theme: 'Dense, abstract language and academic style',
    hook: "Vee hands you an academic paragraph that nobody can follow. Rewrite it so a smart 14-year-old understands - and keep the meaning.",
    release: 'A short academic-style paragraph and its plain-English version',
    canDo: [
      'I can use nominalisation and complex noun phrases to write concisely and formally.',
      'I can move between formal and plain versions of the same idea.',
    ],
    functions: ['writing academically', 'defining and explaining', 'simplifying complex ideas'],
    structures: ['nominalisation'],
    lexicalFields: ['academic vocabulary', 'science and research', 'abstract nouns'],
    items: 84,
    pron: ['stress in long noun phrases', 'rhythm in academic reading aloud'],
    mediation: 'Re-express a dense academic paragraph for a general audience.',
    skins: ['science', 'tech', 'nature', 'business'],
  },
  {
    title: 'What Matters Is...',
    theme: 'Focus, emphasis and storytelling',
    hook: "Every great story hides one sentence that changes everything. Find it, and learn how the author makes you notice it.",
    release: 'A short narrative that uses fronting and emphasis to build to a key moment',
    canDo: [
      'I can use cleft and fronted structures to shape what the reader notices.',
      'I can write a short story with controlled effect.',
    ],
    functions: ['storytelling', 'emphasising and contrasting', 'building to a climax'],
    structures: ['fronting-emphasis'],
    lexicalFields: ['literature and film', 'emotion and mood', 'narrative devices'],
    items: 84,
    pron: ['dramatic pacing and stress', 'pause and release in a climax'],
    mediation: 'Explain the effect of a famous passage to a friend who found it confusing.',
    skins: ['film', 'anime', 'music', 'art'],
  },
  {
    title: 'Having Said That',
    theme: 'Concise, sophisticated written style',
    hook: "Ava submits a sentence that is 62 words long and correct. Vee says it is still bad. Why - and how do you fix it?",
    release: 'An edited text showing how I tightened five sentences',
    canDo: [
      'I can use perfect participle clauses and reduced relatives to write more economically.',
      'I can edit complex sentences for clarity and style.',
    ],
    functions: ['editing and condensing', 'linking ideas economically', 'writing in a mature style'],
    structures: ['perfect-participle'],
    lexicalFields: ['writing and editing', 'journalism and essays', 'cause, sequence and result'],
    items: 84,
    pron: ['rhythm in participle-based sentences', 'stress on the main clause'],
    mediation: 'Edit another student\'s text so it keeps meaning but is shorter and clearer.',
    skins: ['social', 'film', 'science', 'business'],
  },
  {
    title: 'Reading Between the Lines',
    theme: 'Stance, nuance and implied meaning',
    hook: "'Admittedly, it was not a disaster.' What is the writer really saying? Decode the stance behind eight short messages.",
    release: 'A commentary on how a writer or speaker shows attitude',
    canDo: [
      'I can understand implied attitude and express my own stance with precision.',
      'I can hedge and qualify claims appropriately.',
    ],
    functions: ['expressing stance', 'hedging and qualifying', 'reading implied meaning'],
    structures: ['stance-adverbials'],
    lexicalFields: ['attitude and opinion', 'critical reading', 'evidence and argument'],
    items: 84,
    pron: ['intonation that shows attitude', 'stress on stance adverbials'],
    mediation: 'Tell a listener what an author really thinks, based on a passage.',
    skins: ['social', 'film', 'music', 'science'],
  },
  {
    title: 'Formal or Not?',
    theme: 'Register: choosing the right voice',
    hook: "The same request goes to a friend, a teacher and a company. Rewrite it three times - and spot why one of the replies backfires.",
    release: 'Three versions of one message in different registers, with notes on word choice',
    canDo: [
      'I can adjust register to audience and purpose in speech and writing.',
      'I can recognise when a formal or informal choice is inappropriate.',
    ],
    functions: ['adapting register', 'writing formal and informal messages', 'recognising tone'],
    structures: ['register-shift'],
    lexicalFields: ['formal and informal vocabulary', 'email and messaging conventions', 'workplace and school communication'],
    items: 84,
    pron: ['formal vs informal pronunciation and pace', 'tone of voice and politeness'],
    mediation: 'Relay an informal message in a formal register to a third party.',
    skins: ['business', 'social', 'tech', 'fashion'],
  },
  {
    title: 'Be That As It May',
    theme: 'Conceding and counter-arguing',
    hook: "A friend's argument is nearly right. Learn how to say 'granted' without giving up your own point.",
    release: 'A two-sided argument with concessions, spoken and written',
    canDo: [
      'I can concede a point while keeping my position.',
      'I can structure a balanced argument with advanced concession.',
    ],
    functions: ['conceding', 'counter-arguing', 'balancing viewpoints'],
    structures: ['concession-advanced'],
    lexicalFields: ['argument and persuasion', 'ethics and society', 'balanced judgement'],
    items: 84,
    pron: ['intonation of concession (rise then fall)', 'stress on the contrast'],
    mediation: 'Help two people with opposing views find the common ground in a text.',
    skins: ['social', 'film', 'business', 'nature'],
  },
  {
    title: "Needn't Have",
    theme: 'Precision with modals and obligation',
    hook: "Theo packed for a storm that never came. Was he foolish, careful or simply unlucky? Judge with exactly the right modal.",
    release: 'A short reflective text on a plan that did and did not work',
    canDo: [
      'I can use advanced modal forms to express obligation, expectation and judgement precisely.',
      'I can adjust the force of what I say with modal nuance.',
    ],
    functions: ['judging past decisions', 'expressing expectation', 'advising precisely'],
    structures: ['modal-nuance'],
    lexicalFields: ['planning and risk', 'travel and outdoors', 'work and responsibility'],
    items: 84,
    pron: ['weak and strong forms in modal chains', 'intonation of judgement'],
    mediation: 'Explain to a friend what a set of rules really requires, which parts are optional, and which are not.',
    skins: ['travel', 'fitness', 'business', 'nature'],
  },
  {
    title: 'Words That Fit',
    theme: 'Collocation, idiom and precision',
    hook: "'Heavy rain' but 'strong wind' - why? Hunt for the invisible rules behind natural English and break at least one on purpose.",
    release: 'A collocation and idiom map for a topic, with example sentences I wrote',
    canDo: [
      'I can use collocations and idioms precisely and avoid awkward word choices.',
      'I can replace repeated words with natural alternatives.',
    ],
    functions: ['choosing precise words', 'paraphrasing', 'using idiom'],
    structures: ['ellipsis-advanced'],
    lexicalFields: ['collocations and idioms', 'topic vocabulary in a chosen field', 'phrasal verbs and fixed expressions'],
    items: 84,
    pron: ['stress and rhythm in idioms', 'connected speech in fixed expressions'],
    mediation: 'Paraphrase a text using different but natural vocabulary for a different audience.',
    skins: ['music', 'film', 'football', 'social', 'business'],
  },
  {
    title: 'Mediating Worlds',
    theme: 'Mediation across cultures and viewpoints',
    hook: "Two teams from different countries must agree a joint project. You are the only person who understands both - make it work.",
    release: 'A live mediation of a short negotiation and a written summary',
    canDo: [
      'I can mediate between speakers with different viewpoints and summarise key decisions.',
      'I can convey the essence of long texts and discussions clearly.',
    ],
    functions: ['mediating', 'summarising for different audiences', 'facilitating agreement'],
    structures: ['discourse-markers-advanced'],
    lexicalFields: ['intercultural communication', 'meetings and negotiation', 'international projects'],
    items: 84,
    pron: ['clear signposting intonation', 'neutral and diplomatic tone'],
    mediation: 'Chair a mediation between two parties and produce a neutral written summary.',
    skins: ['business', 'travel', 'social', 'science'],
  },
  {
    title: 'The Art of Persuasion',
    theme: 'Rhetoric, advertising and public speaking',
    hook: "The best speeches use three tricks you already know. Spot them in ten clips and learn to use them ethically.",
    release: 'A persuasive speech or pitch (three minutes) with an annotated script',
    canDo: [
      'I can use rhetorical devices to persuade and recognise when others use them.',
      'I can deliver a structured, persuasive presentation.',
    ],
    functions: ['persuading', 'presenting', 'analysing persuasion'],
    structures: ['rhetorical-devices'],
    lexicalFields: ['advertising and marketing', 'speeches and campaigns', 'ethics of persuasion'],
    items: 84,
    pron: ['pace, pause and emphasis in speeches', 'rhetorical intonation (lists of three, rhetorical questions)'],
    mediation: 'Analyse an advert for a younger audience and explain how it tries to persuade.',
    skins: ['business', 'social', 'film', 'music'],
  },
  {
    title: 'Wit and Irony',
    theme: 'Humour, understatement and cultural nuance',
    hook: "'Not bad at all' can mean two opposite things. Learn the signals of English humour and when not to take words literally.",
    release: 'A short comic or satirical piece (school-safe) with notes on how the humour works',
    canDo: [
      'I can recognise irony, understatement and humour, and use them tactfully.',
      'I can explain how tone changes meaning.',
    ],
    functions: ['joking and teasing tactfully', 'understanding irony', 'managing tone'],
    structures: ['irony-understatement'],
    lexicalFields: ['humour and satire', 'idioms and cultural references', 'tone and attitude'],
    items: 84,
    pron: ['intonation that signals irony', 'timing and pause in humour'],
    mediation: 'Explain a joke or ironic comment to someone from another culture.',
    skins: ['film', 'social', 'music', 'anime'],
  },
  {
    title: 'Capstone Portfolio',
    theme: 'Putting it all together: a student-led final project',
    hook: "Vee closes the programme with one question: what do you want the world to understand, and how will you say it in English?",
    release: 'A capstone portfolio: a spoken presentation, a written piece and a reflection on my progress',
    canDo: [
      'I can plan, produce and present a substantial project in English on a topic I choose.',
      'I can reflect on my progress and set goals for continued learning.',
    ],
    functions: ['presenting a project', 'reflecting on learning', 'setting goals'],
    structures: ['text-cohesion'],
    lexicalFields: ['project work and presentation', 'academic and professional skills', 'self-assessment'],
    items: 84,
    pron: ['sustained clear delivery', 'signposting in long presentations'],
    mediation: 'Summarise for an examiner the key insights from a complex source used in my project.',
    skins: ['science', 'business', 'art', 'tech', 'social', 'nature'],
    notes: 'Level check Season: E8 includes the C1 level check (separate from XP) and the final portfolio review.',
  },
];
