CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;

CREATE TABLE IF NOT EXISTS public.email_send_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id TEXT,
  template_name TEXT NOT NULL,
  recipient_email TEXT NOT NULL,
  status TEXT NOT NULL,
  error_message TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_send_log_message_id_created_at
  ON public.email_send_log (message_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_send_log_created_at
  ON public.email_send_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_send_log_template_name
  ON public.email_send_log (template_name);
CREATE INDEX IF NOT EXISTS idx_email_send_log_status
  ON public.email_send_log (status);

ALTER TABLE public.email_send_log ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.suppressed_emails (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  reason TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_suppressed_emails_email
  ON public.suppressed_emails (email);

ALTER TABLE public.suppressed_emails ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.email_unsubscribe_tokens (
  token TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_unsubscribe_tokens_email
  ON public.email_unsubscribe_tokens (email);

ALTER TABLE public.email_unsubscribe_tokens ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.email_send_state (
  id INTEGER PRIMARY KEY,
  batch_size INTEGER NOT NULL DEFAULT 10,
  send_delay_ms INTEGER NOT NULL DEFAULT 200,
  auth_email_ttl_minutes INTEGER NOT NULL DEFAULT 15,
  transactional_email_ttl_minutes INTEGER NOT NULL DEFAULT 60,
  retry_after_until TIMESTAMPTZ,
  last_rate_limit_reason TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.email_send_state ENABLE ROW LEVEL SECURITY;

INSERT INTO public.email_send_state (
  id,
  batch_size,
  send_delay_ms,
  auth_email_ttl_minutes,
  transactional_email_ttl_minutes
)
VALUES (1, 10, 200, 15, 60)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.email_queue_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue_name TEXT NOT NULL,
  payload JSONB NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 5,
  visible_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  claimed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_queue_messages_lookup
  ON public.email_queue_messages (queue_name, visible_at, created_at);
CREATE INDEX IF NOT EXISTS idx_email_queue_messages_expires_at
  ON public.email_queue_messages (expires_at);

ALTER TABLE public.email_queue_messages ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.email_queue_dlq (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_message_id BIGINT,
  queue_name TEXT NOT NULL,
  payload JSONB NOT NULL,
  attempts INTEGER NOT NULL,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_queue_dlq_queue_name_created_at
  ON public.email_queue_dlq (queue_name, created_at DESC);

ALTER TABLE public.email_queue_dlq ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.set_email_send_state_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_email_send_state_updated_at ON public.email_send_state;
CREATE TRIGGER trg_email_send_state_updated_at
BEFORE UPDATE ON public.email_send_state
FOR EACH ROW
EXECUTE FUNCTION public.set_email_send_state_updated_at();

CREATE OR REPLACE FUNCTION public.enqueue_email(_queue_name TEXT, _payload JSONB)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  ttl_minutes INTEGER;
  new_id BIGINT;
BEGIN
  SELECT CASE
    WHEN _queue_name = 'auth_emails' THEN auth_email_ttl_minutes
    ELSE transactional_email_ttl_minutes
  END
  INTO ttl_minutes
  FROM public.email_send_state
  WHERE id = 1;

  INSERT INTO public.email_queue_messages (
    queue_name,
    payload,
    expires_at
  )
  VALUES (
    _queue_name,
    _payload,
    now() + make_interval(mins => COALESCE(ttl_minutes, 60))
  )
  RETURNING id INTO new_id;

  RETURN new_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.read_email_batch(_queue_name TEXT, _batch_size INTEGER DEFAULT NULL)
RETURNS TABLE (
  id BIGINT,
  payload JSONB,
  attempts INTEGER,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  WITH picked AS (
    SELECT q.id
    FROM public.email_queue_messages q
    WHERE q.queue_name = _queue_name
      AND q.visible_at <= now()
    ORDER BY q.created_at ASC
    LIMIT COALESCE(
      _batch_size,
      (SELECT batch_size FROM public.email_send_state WHERE id = 1),
      10
    )
    FOR UPDATE SKIP LOCKED
  ),
  claimed AS (
    UPDATE public.email_queue_messages q
    SET attempts = q.attempts + 1,
        claimed_at = now(),
        visible_at = now() + interval '30 seconds'
    FROM picked
    WHERE q.id = picked.id
    RETURNING q.id, q.payload, q.attempts, q.expires_at, q.created_at
  )
  SELECT claimed.id, claimed.payload, claimed.attempts, claimed.expires_at, claimed.created_at
  FROM claimed;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_email(_queue_name TEXT, _message_id BIGINT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  DELETE FROM public.email_queue_messages
  WHERE id = _message_id
    AND queue_name = _queue_name;

  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count > 0;
END;
$$;

CREATE OR REPLACE FUNCTION public.move_to_dlq(_queue_name TEXT, _message_id BIGINT, _error_message TEXT DEFAULT NULL)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  moved_count INTEGER;
BEGIN
  WITH moved AS (
    DELETE FROM public.email_queue_messages
    WHERE id = _message_id
      AND queue_name = _queue_name
    RETURNING id, queue_name, payload, attempts
  )
  INSERT INTO public.email_queue_dlq (
    original_message_id,
    queue_name,
    payload,
    attempts,
    error_message
  )
  SELECT id, queue_name, payload, attempts, _error_message
  FROM moved;

  GET DIAGNOSTICS moved_count = ROW_COUNT;
  RETURN moved_count > 0;
END;
$$;