// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krhrohkbwlgqsmdkpxqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyaHJvaGtid2xncXNtZGtweHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjczMzgsImV4cCI6MjA2NTE0MzMzOH0.xEo_YXwVXmE_co7ULTDV2HJx7Bo8KxP-VrXGLUE37HQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);